### ISSUE TITLE
Unable to load DLL 'wslapi.dll'

### ISSUE THREAD

**Issue by keenbaffling** [DDoSolitary/LxRunOffline#10]
Hi,

I'm trying to setup ubuntu-17.10 using this command
`C:\Users\klintz>lxrunoffline install -n ubuntu-17.10-amd64 -f D:\Programs\windows\ubuntu-17.10-server-cloudimg
-amd64.tar.gz -d D:\wsl`

And I'm getting this error.

`Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'wslapi.dll': The specified module could
not be found. (Exception from HRESULT: 0x8007007E)
   at LxRunOffline.WslWinApi.WslRegisterDistribution(String distributionName, String tarGzFilename)
   at LxRunOffline.Wsl.InstallDistro(String distroName, String tarGzPath, String targetPath)
   at LxRunOffline.Program.<>c.<Main>b__0_2(InstallOptions opts)
   at LxRunOffline.Program.Main(String[] args)`

Am I doing it right? Need your help.

Here's my current windows version.
![image](https://user-images.githubusercontent.com/19745874/33512180-9afccf68-d765-11e7-90da-ec0cea191485.png)

Thanks!

**Comment by Biswa96** [comment]
Try the older versions v1.1. The new version is for Fall Creators update.

**Comment by DDoSolitary** [comment]
@Biswa96 is right. I've also added compatibility information to README.md (ec6b0adf74cfd3e14a07092e650df8ea16f474b8).
