### ISSUE TITLE
Windows 1903: Couldn't set the case sensitive attribute 

### ISSUE THREAD

**Issue by SamuelDeal** [DDoSolitary/LxRunOffline#100]
When I use LxRunOffline to install a new distribution, I have this error:

```
[ERROR] Couldn't set the case sensitive attribute of the directory "\\?\C:\ProgramData\my_distrib\rootfs\".
Reason: The request is not supported.
```
The same tar.gz works well on other computers with builds 1803 and 1809.
This is run as admin and C: is an NTFS drive.

**Comment by DDoSolitary** [comment]
Have you enabled the "Windows Subsystem for Linux" feature?

**Comment by DDoSolitary** [comment]
Closing as no response.

**Comment by KnowingNothing** [comment]
I met the same issue and I am sure that I have turned on "Windows Subsystem for Linux".
I am using Windows 11.

**Comment by XiaoTonyLuo** [comment]
> 

me too.

**Comment by XiaoTonyLuo** [comment]
> I met the same issue and I am sure that I have turned on "Windows Subsystem for Linux". I am using Windows 11.

me too.
```
[ERROR] Couldn't set the case sensitive attribute of the directory "\\?\C:\Users\win\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\".
Reason: Indicates that the directory trying to be deleted is not empty.
```

**Comment by tomgross** [comment]
I have a similar issue on move
Windows version 20H2 (OS build 19042.1415)

PS D:\> LxRunOffline.exe m -n Ubuntu -d D:\wsl\Ubuntu\
[ERROR] Couldn't set the case sensitive attribute of the directory "\\?\D:\wsl\Ubuntu\temp\".
Reason: An invalid parameter was passed to a service or function.

**Comment by WK-ING** [comment]
Same issue with LxRunOffline-v3.5.0-mingw. 
I tried another version of LxRunOffline and solved the problem : https://ddosolitary-builds.sourceforge.io/LxRunOffline/LxRunOffline-v3.5.0-11-gfdab71a-msvc.zip

**Comment by DDoSolitary** [comment]
@XiaoTonyLuo It's a different and known issue #150

**Comment by DDoSolitary** [comment]
@tomgross The error message (reason part) is different from OP's. Please open a separate issue if you're still having touble.
