### ISSUE TITLE
can't set default user

### ISSUE THREAD

**Issue by kongdd** [DDoSolitary/LxRunOffline#101]
1. 当没有从appstore 安装ubuntu1804的时候，没有ubuntu.exe或ubuntu1804.exe，因此也就不能按照微软的教程设置default user.
 - Ubuntu18-04 (installed by appstore)
 - ubuntu1804 (imported by LxRunOffline)

2. 当安装Ubuntu18-04之后，`ubuntu1804 config --default-user kong`设置的是Ubuntu18-04的用户，而非`ubuntu1804`

**Comment by DDoSolitary** [comment]
`LxRunOffline su -n ubuntu1804 -v your-user-id`
