### ISSUE TITLE
Issue with tmux when I custom my bashrc

### ISSUE THREAD

**Issue by dovankhai** [DDoSolitary/LxRunOffline#102]
* Before I not use tmux
![image](https://user-images.githubusercontent.com/24471733/68940041-b3400580-07d4-11ea-85ba-c3126ccb4b9e.png)

* After I use tmux
![image](https://user-images.githubusercontent.com/24471733/68940073-c9e65c80-07d4-11ea-94e9-aa97c3ee917c.png)

**Comment by DDoSolitary** [comment]
This isn't an issue of this project. Please report it to [Microsoft/WSL](https://github.com/Microsoft/WSL)

**Comment by FreakLevel** [comment]
Only a suggestion: Maybe you should test with Cmder or if you're a insider preview with Windows Terminal Preview.
