### ISSUE TITLE
Not export a distribution's filesystem to a .tar.gz file

### ISSUE THREAD

**Issue by dovankhai972** [DDoSolitary/LxRunOffline#103]
* I can not export the distribution's filesystem
![image](https://user-images.githubusercontent.com/39219821/69621815-5fee7280-1072-11ea-8acd-3a7d834454a9.png)

*  Export configuration of a distribution to an XML is fine.
![image](https://user-images.githubusercontent.com/39219821/69621885-7d234100-1072-11ea-9df3-ca766e351472.png)

You can help me to this issue?

**Comment by DDoSolitary** [comment]
To avoid potential problems, LxRunOffline will check if the installation directory of the distro is being used before performing the export action. It is failing because you put the LxRunOffline executable inside the distro's installation directory.
