### ISSUE TITLE
Importing file names that are invalid on Windows

### ISSUE THREAD

**Issue by Konfekt** [DDoSolitary/LxRunOffline#107]
WSL replaces in file names the characters `<>":|?* ` which are invalid in an NTFS file name. LxRunOffline, when importing, does not seem to do such thing, aborting the operation.

Therefore, before *exporting* the tar, the user should check, say by `ls -a **/*[\<\>\":\|?\*]*(D)` on ZSH for invalid characters in file names.

**Comment by DDoSolitary** [comment]
It seems that I've handled most of the special characters but forgot the quotation mark `?`.

**Comment by DDoSolitary** [comment]
In theory other special characters are already properly handled. Please let me know if it's not working.

**Comment by Konfekt** [comment]
Thank you. For what it's worth, the distribution was exported by `wsl` (and not `lxrunoffline`). Doubling the distribution worked fine.
