### ISSUE TITLE
如何安装wsl2的ubuntu19.10的rootfs??

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#108]
http://cloud-images.ubuntu.com/releases/eoan/release-20191217/

这个提供了wsl版本。应该用这个么？？还是用别的什么。比如azure版本？？？

没有办法默认安装wsl2版本么？？？

**Comment by expnkx** [comment]
还有这玩意能装aarch linux一类的么？

**Comment by DDoSolitary** [comment]
> 这个提供了wsl版本。应该用这个么？？还是用别的什么。比如azure版本？？？

wsl版应该可以。azure版不行，因为那个是vhd格式的。

> 没有办法默认安装wsl2版本么？？？

wsl2是用vhdx来存放linux的文件的，这个暂时还没有支持，所以只能先安装wsl1，然后再用官方的`wsl --set-version 2`命令转换成wsl2

> 还有这玩意能装aarch linux一类的么？

可以，[Wiki](https://github.com/DDoSolitary/LxRunOffline/wiki)里有相关信息

**Comment by expnkx** [comment]
> > 这个提供了wsl版本。应该用这个么？？还是用别的什么。比如azure版本？？？
> 
> wsl版应该可以。azure版不行，因为那个是vhd格式的。
> 
> > 没有办法默认安装wsl2版本么？？？
> 
> wsl2是用vhdx来存放linux的文件的，这个暂时还没有支持，所以只能先安装wsl1，然后再用官方的`wsl --set-version 2`命令转换成wsl2
> 
> > 还有这玩意能装aarch linux一类的么？
> 
> 可以，[Wiki](https://github.com/DDoSolitary/LxRunOffline/wiki)里有相关信息

我是这么尝试的安装的ubuntu-19.10wsl版本。不过不知道能不能直接装wsl2的，感觉应该是有办法的。

我还想试试centos8，不过感觉官方没提供，只能装centos7的。

**Comment by DDoSolitary** [comment]
> 我是这么尝试的安装的ubuntu-19.10wsl版本。不过不知道能不能直接装wsl2的，感觉应该是有办法的。

理论上可行，但是这个项目暂时不支持。如果通过微软官方方法装的话，也可以先`wsl --set-default-version 2`，再从应用商店装

> 我还想试试centos8，不过感觉官方没提供，只能装centos7的。

可以试试用centos给docker做的镜像：https://github.com/CentOS/sig-cloud-instance-images/blob/CentOS-8-x86_64/docker/centos-8-container.tar.xz

**Comment by wz1765** [comment]
Use distro `https://lxrunoffline.apphb.com/download/Ubuntu/eoan`
Finish~
```
PS C:\Users\Administrator> LxRunOffline version
LxRunOffline v3.4.0
PS C:\Users\Administrator> wsl
root@MicroWin10-1203:/mnt/c/Users/Administrator# sudo lsb_release -a
sudo: lsb_release: command not found
root@MicroWin10-1203:/mnt/c/Users/Administrator# cat /etc/issue
Ubuntu 19.10 \n \l
```
