### ISSUE TITLE
虽然说问题有点蠢，不过还是想报告一下。怎么在msys2终端里用这个？？

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#109]
感觉cmd和powershell太难用了。不知道你能不能把msys2的路径搞对了？？？
![image](https://user-images.githubusercontent.com/57303909/72872606-c29f6b80-3cbb-11ea-90d1-ecc0f40246dc.png)

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/72872831-478a8500-3cbc-11ea-8e83-0570ced3cc61.png)
看样还不是msys2终端的问题。感觉不支持注册wsl2????不知道什么原因。我记得我以前成功的呀

**Comment by expnkx** [comment]
我电脑加了块1tb的固态硬盘硬盘重装了，结果不知道如何把原来安装的vhdx给重新加载。有什么办法么？
![image](https://user-images.githubusercontent.com/57303909/72873075-dd261480-3cbc-11ea-9c83-06a20ebd7409.png)

**Comment by expnkx** [comment]
完了。原来的ubuntu没了呜呜呜呜

**Comment by expnkx** [comment]
unlvs@DESKTOP-C4VAUFM MINGW64 /d/Downloads/LxRunOffline-v3.4.0
$ ./LxRunOffline.exe i -n Ubuntu-19.10 -f F:\\original\\ext4.vhdx -d F:\\rootfs
[ERROR] Error occurred while processing the archive: Unrecognized archive format

**Comment by DDoSolitary** [comment]
3.4.0暂时不支持wsl2，我本来打算今天发布3.4.1的，但是CI脚本出了点问题，所以得过几天了，急着用的话可以去按readme里的说明去下载development builds

**Comment by expnkx** [comment]
> 3.4.0暂时不支持wsl2，我本来打算今天发布3.4.1的，但是CI脚本出了点问题，所以得过几天了，急着用的话可以去按readme里的说明去下载development builds

我直接把原来的vhdx删了

**Comment by DDoSolitary** [comment]
草

**Comment by expnkx** [comment]
> 草

什么情况。。。你吓着我了

**Comment by DDoSolitary** [comment]
那issue我关了

顺便，如果你没删的话，正确的做法是把ext4.vhdx放到一个空文件夹里（不能是分区的根目录），然后运行`LxRunOffline register -n Ubuntu-19.10 -d <那个放vhdx的文件夹的路径>`

**Comment by expnkx** [comment]
> 那issue我关了
> 
> 顺便，如果你没删的话，正确的做法是把ext4.vhdx放到一个空文件夹里（不能是分区的根目录），然后运行`LxRunOffline register -n Ubuntu-19.10 -d <那个放vhdx的文件夹的路径>`

谢谢你了。下次再重装就有办法了

**Comment by DDoSolitary** [comment]
因为我写这个项目的时候主要用的Visual Studio，Makefile的支持是后来才加上去的。。

**Comment by expnkx** [comment]
> 因为我写这个项目的时候主要用的Visual Studio，Makefile的支持是后来才加上去的。。

vc真的太坑了。用着受罪。

还有个小建议，建议不要使用std::endl，直接用'\n'

**Comment by DDoSolitary** [comment]
之前考虑过改用cmake，但是当时VS2019才刚出cmake还不支持，就搁置了

**Comment by expnkx** [comment]
> 之前考虑过改用cmake，但是当时VS2019才刚出cmake还不支持，就搁置了

感觉我这次编译gcc10.0.1没绿屏。应该能编译出来。编译出来给你试试如何？GCC是目前三个编译器里C++20支持最好的。

**Comment by DDoSolitary** [comment]
> 还有个小建议，建议不要使用std::endl，直接用'\n'

这个说法我第一次听说，待会儿去了解一下

> GCC是目前三个编译器里C++20支持最好的。 

我暂时不考虑使用C++20的特性，因为目前来看没有编译器完整支持了C++20，写代码的时候还要考虑特定编译器支持是很难受的（参考前端开发时的浏览器支持），并不是所有想尝试编译这个项目的人都在使用最新版本的gcc

> 用gcc编译win下一定要加-s，不然二进制爆涨10倍都是调试信息

但是调试信息是有必要的。我觉得Makefile应该默认保留调试信息，否则会给想要调试的人带来很多麻烦。相反，对于不需要调试信息的情况，比如发布新版本，只要运行一下strip就行了

**Comment by expnkx** [comment]
> > 还有个小建议，建议不要使用std::endl，直接用'\n'
> 
> 这个说法我第一次听说，待会儿去了解一下
> 
> > GCC是目前三个编译器里C++20支持最好的。
> 
> 我暂时不考虑使用C++20的特性，因为目前来看没有编译器完整支持了C++20，写代码的时候还要考虑特定编译器支持是很难受的（参考前端开发时的浏览器支持），并不是所有想尝试编译这个项目的人都在使用最新版本的gcc
> 
> > 用gcc编译win下一定要加-s，不然二进制爆涨10倍都是调试信息
> 
> 但是调试信息是有必要的。我觉得Makefile应该默认保留调试信息，否则会给想要调试的人带来很多麻烦。相反，对于不需要调试信息的情况，比如发布新版本，只要运行一下strip就行了

std::endl是输出'\n'+刷新缓冲区，实际根本没必要，cin和cerr有tie，你用了就自动刷新cout了，调用endl相当于直接系统调用，开销巨大。

主要是gcc在win下生成的各种没用的信息太多了。经常动不动就好几mb，其实就是20kb的hello world.

**Comment by expnkx** [comment]
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slio50-avoid-endl

**Comment by DDoSolitary** [comment]
> std::endl是输出'\n'+刷新缓冲区，实际根本没必要，cin和cerr有tie，你用了就自动刷新cout了，调用endl相当于直接系统调用，开销巨大。

有道理，我待会儿去改了

> 主要是gcc在win下生成的各种没用的信息太多了。经常动不动就好几mb，其实就是20kb的hello world.

我说了这不是没用的信息，你还让不让人调试了。。

> 即使是50%的二进制膨胀都成异常处理被大规模(50%项目)禁用的理由了。

就我所知二进制膨胀主要导致的问题是发布的文件会下载更慢、占用更多硬盘空间（尤其是在嵌入式开发时这很要命），二在本地开发时，相比于更好的调试体验，这点硬盘空间完全时affordable的。但是我说了，调试信息造成的二进制文件过大可以通过在发布时运行strip轻松解决，所以只要记得这一步，根本称不上什么问题。而异常处理这个功能不是仅面向开发者的，在发布版中相关信息同样也要存在，所以要优化二进制文件体积的话就只能禁用掉

**Comment by expnkx** [comment]
> > std::endl是输出'\n'+刷新缓冲区，实际根本没必要，cin和cerr有tie，你用了就自动刷新cout了，调用endl相当于直接系统调用，开销巨大。
> 
> 有道理，我待会儿去改了
> 
> > 主要是gcc在win下生成的各种没用的信息太多了。经常动不动就好几mb，其实就是20kb的hello world.
> 
> 我说了这不是没用的信息，你还让不让人调试了。。
> 
> > 即使是50%的二进制膨胀都成异常处理被大规模(50%项目)禁用的理由了。
> 
> 就我所知二进制膨胀主要导致的问题是发布的文件会下载更慢、占用更多硬盘空间（尤其是在嵌入式开发时这很要命），而在本地开发时，相比于更好的调试体验，这点硬盘空间完全是affordable的。但是我说了，调试信息造成的二进制文件过大可以通过在发布时运行strip轻松解决，所以只要记得这一步，根本称不上什么问题。而异常处理这个功能不是仅面向开发者的，在发布版中相关信息同样也要存在，所以要优化二进制文件体积的话就只能禁用掉

对呀。所以其实-Ofast或是cmake Release就应该自动-s，可是就是没有。 :(

**Comment by expnkx** [comment]
可怜。编译32位的mingw gcc又失败。只能编译出来64位的。编译32位的能编译出来，很大概念直接绿屏。我刚才又绿屏了

**Comment by DDoSolitary** [comment]
> 对呀。所以其实-Ofast或是cmake Release就应该自动-s，可是就是没有。 :( 得手工-s

-Ofast并没有表达出“不要调试信息”或是“发布”的语义，直接自动删除调试信息并不妥当；不过cmake Release自动strip倒是挺合理的，可能是考虑到有时需要调试仅在release版中存在的神奇bug吧

**Comment by expnkx** [comment]
> > 对呀。所以其实-Ofast或是cmake Release就应该自动-s，可是就是没有。 :( 得手工-s
> 
> -Ofast并没有表达出“不要调试信息”或是“发布”的语义，直接自动删除调试信息并不妥当；不过cmake Release自动strip倒是挺合理的，可能是考虑到有时需要调试仅在release版中存在的神奇bug吧

很奇怪的是gcc在linux下就不生成那么多信息，在win下就会。

**Comment by DDoSolitary** [comment]
vc默认情况下体积更小的原因我觉得是把调试信息都扔到pdb文件里去了吧。。

**Comment by expnkx** [comment]
> vc默认情况下体积更小的原因我觉得是把调试信息都扔到pdb文件里去了吧。。

不是。vc永远体积特别大。所有函数的函数表都会生成，而且strip无效

**Comment by DDoSolitary** [comment]
我是说gcc不strip的情况下（

**Comment by expnkx** [comment]
> 我是说gcc不strip的情况下（

没看过。233。 不知道什么原因。我记得就算你用-S编译也看不出来。

**Comment by expnkx** [comment]
-S生成的汇编是完全一样的，不管开不开-s。估计可能是链接的问题。链接里的垃圾太多了。
这是不开-s的
![image](https://user-images.githubusercontent.com/57303909/72886055-1d928c00-3cd7-11ea-8374-8d32ecbf296b.png)
这是开了-s的
![image](https://user-images.githubusercontent.com/57303909/72886095-313df280-3cd7-11ea-88b3-0719797beb7b.png)

生成的汇编是完全一样的，但编译出来的二进制不一样大。

**Comment by DDoSolitary** [comment]
你看汇编没有用，汇编里没有调试信息，要看object file

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/72886338-9c87c480-3cd7-11ea-9f2f-92eb2ecd4795.png)
直接用-c生成的.o也没变化

**Comment by DDoSolitary** [comment]
欸这样的吗，看来调试信息是linker加上的 😄

**Comment by expnkx** [comment]
> 欸这样的吗，看来调试信息是linker加上的 😄

我估计可能是链接别的crt什么的，那些没strip

**Comment by DDoSolitary** [comment]
突然发现，这楼已经歪到哪里去都不知道了（

**Comment by expnkx** [comment]
我这里关了异常和rtti是直接terminate的，二进制体积降到18kb
![image](https://user-images.githubusercontent.com/57303909/72886565-043e0f80-3cd8-11ea-94e1-6528fb3f4312.png)

**Comment by expnkx** [comment]
> 突然发现，这楼已经歪到哪里去都不知道了（

想请你帮个忙。不太懂https，你能帮写一个么？

**Comment by DDoSolitary** [comment]
近期应该没空，除了这个项目的CI脚本要修，我还有一个项目要做安卓10的适配，一个项目最近核心功能刚刚写完，单元测试什么的完全没动过，学校还有一个比赛要肝，过年还有各种事要忙。。

**Comment by expnkx** [comment]
> 近期应该没空，除了这个项目的CI脚本要修，我还有一个项目要做安卓10的适配，一个项目最近核心功能刚刚写完，单元测试什么的完全没动过，学校还有一个比赛要肝，过年还有各种事要忙。。

你是本科生么？

**Comment by DDoSolitary** [comment]
> 你是本科生么？

是

>  我不想用openssl，太麻烦了。:(

个人建议直接用现有的加密库，除非你真的很nb，你自己写的实现无论性能还是安全性和现有的库是没法比的。我觉得用openssl太麻烦只是你的错觉，事实是用C/C++的库都很麻烦（

**Comment by expnkx** [comment]
> > 你是本科生么？
> 
> 是
> 
> > 我不想用openssl，太麻烦了。:(
> 
> 个人建议直接用现有的加密库，除非你真的很nb，你自己写的实现无论性能还是安全性和现有的库是没法比的。我觉得用openssl太麻烦只是你的错觉，事实是用C/C++的库都很麻烦（

实话讲我一点不相信openssl一类的性能的安全性。基本上用C语言写的没几个性能高的。

**Comment by expnkx** [comment]
> > 你是本科生么？
> 
> 是

本科生就这么厉害了。。自愧不如。。。 :(

**Comment by DDoSolitary** [comment]
> 加个好友吧。就算你没空，你能指点指点我也好。

技术相关的交流我更习惯用邮箱，地址是公开的，在GitHub账号页面可以看到

> 我想搞这玩意出来把stdio,流,asio,charconv,fmt,llfio,boost json一类的全部干死。

那我大概帮不到你，我拼了老命也做不出这种水平的东西（

> 最大的问题还是编译太烦了。openssl光编译都麻烦

不用自己编译，linux或者msys的话直接用软件包，msvc的话可以用vcpkg

**Comment by expnkx** [comment]
> > 我想搞这玩意出来把stdio,流,asio,charconv,fmt,llfio,boost json一类的全部干死。
> 
> 那我大概帮不到你，我拼了老命也做不出这种水平的东西（
> 

charconv和fmt其实已经死了。。。C++17这么长时间了，gcc和clang都实现不出来charconv.连libstdc++的作者都承认charconv是个错误。根本就没有算法能实现，实现出来也不会有人用，还容易缓冲区溢出。

**Comment by DDoSolitary** [comment]
> 实话讲我一点不相信openssl一类的性能的安全性。基本上用C语言写的没几个性能高的，一个例子就是isspace从来不会内联（因为没事干折腾现场一类的），最后都得手写，math.h因为折腾全局的错误码，有线程安全一类的问题，导致大规模的开-Ofast,实际上成了一种C语言方言，ISO C标准委员会对这事非常的不爽。特别是错误码，90%以上的C语言CVE安全漏洞都和错误码有关

这和语言无关，如果你用C写的话，你敢说你不会犯你说的这些错误吗，如果你不用C写的话，其他语言也有现有的库。。

**Comment by expnkx** [comment]
> > 实话讲我一点不相信openssl一类的性能的安全性。基本上用C语言写的没几个性能高的，一个例子就是isspace从来不会内联（因为没事干折腾现场一类的），最后都得手写，math.h因为折腾全局的错误码，有线程安全一类的问题，导致大规模的开-Ofast,实际上成了一种C语言方言，ISO C标准委员会对这事非常的不爽。特别是错误码，90%以上的C语言CVE安全漏洞都和错误码有关
> 
> 这和语言无关，如果你用C写的话，你敢说你不会犯你说的这些错误吗，如果你不用C写的话，其他语言也有现有的库。。

这完全是语言设计缺陷导致的结果。安全漏洞50%上是因为C语言，统计数据已经完全证明了。

别的语言有异常呀，这一类事就相对少的多。

**Comment by DDoSolitary** [comment]
> charconv和fmt其实已经死了。。。C++17这么长时间了，gcc和clang都实现不出来charconv.连libstdc++的作者都承认charconv是个错误。根本就没有算法能实现，实现出来也不会有人用，还容易缓冲区溢出。就像boost expected,boost outcome,errno和异常的关系一样，都是轮子。

C++的字符串处理目前确实是一坨屎，但是你想干死的这些东西实际上分属不同的领域，stdio，iostream，asio，llfio是IO，charconv，fmt是字符串处理

**Comment by expnkx** [comment]
> > charconv和fmt其实已经死了。。。C++17这么长时间了，gcc和clang都实现不出来charconv.连libstdc++的作者都承认charconv是个错误。根本就没有算法能实现，实现出来也不会有人用，还容易缓冲区溢出。就像boost expected,boost outcome,errno和异常的关系一样，都是轮子。
> 
> C++的字符串处理目前确实是一坨屎，但是你想干死的这些东西实际上分属不同的领域，stdio，iostream，asio，llfio是IO，charconv，fmt是字符串处理

其实完全是相同的领域，都是io。字符串处理不过是一种io设备。

**Comment by DDoSolitary** [comment]
IO负责的是数据的输入和输出，字符串处理负责的是数据的处理

**Comment by expnkx** [comment]
> IO负责的是数据的输入和输出，字符串处理负责的是数据的处理

你觉得printf("Hello World")是数据的输出还是数据的处理？

**Comment by DDoSolitary** [comment]
先处理，再输出

**Comment by expnkx** [comment]
> 先处理，再输出

你觉得是怎么处理的？

**Comment by DDoSolitary** [comment]
你所谓的在缓冲区里直接完成处理不过是一边处理一边把数据给IO进行输出，而不是全部处理完了再输出罢了

**Comment by DDoSolitary** [comment]
两者尽管耦合更紧密了，但仍然是有边界的

**Comment by DDoSolitary** [comment]
另外，现在的话题已经完全off topic了，和这个项目完全没有关系，建议用其他方式（如邮箱、论坛等）继续讨论

**Comment by DDoSolitary** [comment]
> 你之前搞OI也应该听说过有很多人直接处理输入不用scanf,printf会极大提高性能，甚至是１０倍的性能。

这和你的论点是相悖的，这么做的结果是让CRT处理IO，自己的代码做字符串处理，反而使两者解耦了。

**Comment by expnkx** [comment]
> > 你之前搞OI也应该听说过有很多人直接处理输入不用scanf,printf会极大提高性能，甚至是１０倍的性能。
> 
> 这和你的论点是相悖的，这么做的结果是让CRT处理IO，自己的代码做字符串处理，反而使两者解耦了。

如果你真的完全做字符串处理，根本就是做不了的，比如举个例子。输入有缓冲区是固定长芦，你数字长度却是无限长的。你怎么办。
