### ISSUE TITLE
Version 1.1 Unable to Install Fedora - Error 0x80070003

### ISSUE THREAD

**Issue by Dennis-Cao** [DDoSolitary/LxRunOffline#11]
Hi,
I am stuck working on a system that does not have the Fall Creator's Update, thus I am also stuck with using the 1.1 version of LxRunOffline (As I do not have the required .dll files mentioned here: https://github.com/DDoSolitary/LxRunOffline/issues/10).

After following all of the instructions on the wiki page here: https://github.com/DDoSolitary/LxRunOffline/wiki/Fedora , I run 

`.\LxRunOffline.exe /install`

and specify the fedora .tar.gz and a .ico icon file. I get the following output after specifying the tar and ico locations:

```
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical 
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Error: 0x80070003
```

System details:
OS Name: Windows 10 Enterprise
Version: 1607
OS Build: 14393.447

**Comment by Biswa96** [comment]
Those distros that I've written in wiki were installed in Fall Creators update. I've not tried them in old windows 10 build. Did you get that docker image correctly? Which version of fedora did you try?
I'll then try that in my old VM and inform you.

**Comment by Dennis-Cao** [comment]
I tried using two versions of fedora. 
Version 27 from here: https://github.com/fedora-cloud/docker-brew-fedora/blob/27/x86_64/fedora-27-x86_64-20171110.tar.xz

And Version 21  from here: https://github.com/fedora-cloud/docker-brew-fedora/blob/21/fedora-21-release.tar.xz

I then followed the instructions on the wiki to convert the .tar.xz to .tar.gz.

**Comment by Biswa96** [comment]
OK, I'll try it. Why not you install new Windows 10 builds? Does Ubuntu works with normal process?

**Comment by Dennis-Cao** [comment]
Ubuntu works fine.

The windows build is out of my control; laptop is also not connected to the network. That's why I am using this offline installer.

**Comment by Dennis-Cao** [comment]
Just tried with the --hard-dereference option, different error in same location: 0x800706f8

**Comment by Dennis-Cao** [comment]
Wait hold on, the --hard-dereference worked with fedora 27; just failed with fedora 21. This is probably sufficient for my needs.
