### ISSUE TITLE
你这个MinGW版本的LxRunOffline开了优化么？

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#111]
https://github.com/DDoSolitary/LxRunOffline/blob/master/Makefile
没看到你脚本里-Ofast或是-O3。 还有-DNDEBUG什么的

**Comment by expnkx** [comment]
我编译出来的体积比你的稍微小了一点
![image](https://user-images.githubusercontent.com/57303909/73129880-96d1fd80-3fbb-11ea-8347-0efb5dc90747.png)

**Comment by DDoSolitary** [comment]
没开，我当时写Makefile的主要目的是方便想使用MinGW编译的开发者，而不是用于发布

**Comment by DDoSolitary** [comment]
Makefile默认开优化也显然是错误操作，我在考虑加一个target或者索性改用cmake
