### ISSUE TITLE
代码里感觉太多ub了。

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#112]
比如这个fs.cpp  违反严格别名机制。不能小转大我记得。
	const auto bi = std::make_unique<char[]>(il);
	const auto pi = reinterpret_cast<FILE_FULL_EA_INFORMATION *>(bi.get());

最好还是糊一个位转换，不要用reinterpret_cast。 reinterpret_cast基本都是错误的。
https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8

建议看看这个视频
https://www.youtube.com/watch?v=_qzMpk-22cc

还有尽可能不要使用unique_ptr来管理非new的资源，这类还需要糊异常处理，光用unique_ptr往往擦不干净，还容易导致泄漏。针对每个资源专门写一个5法则类是最好的，语义还清晰，不折腾指针。

智能指针实际上和裸指针一样的有害

**Comment by expnkx** [comment]
这里报的警告。用位转换应该是对吧。虽然我也不确定。
https://en.cppreference.com/w/cpp/numeric/bit_cast

你用memcpy应该不会报警告的。我是自己糊的bit_cast，感觉没报警告，应该是对的

LxRunOffline/main.cpp:165:18: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'HRESULT (*)(PCWSTR, PCWSTR, BOOL, DWORD*)' {aka 'long int (*)(const wchar_t*, const wchar_t*, int, long unsigned int*)'} [-Wcast-function-type]
  165 |    auto launch = reinterpret_cast<HRESULT(__stdcall *)(PCWSTR, PCWSTR, BOOL, DWORD *)>(GetProcAddress(hw, "WslLaunchInteractive"));
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by DDoSolitary** [comment]
> 这里报的警告。用位转换应该是对吧。虽然我也不确定。

这个应该是没问题的

https://en.cppreference.com/w/cpp/language/reinterpret_cast

> 8\) On some implementations (in particular, on any POSIX compatible system as required by dlsym), a function pointer can be converted to void* or any other object pointer, or vice versa. If the implementation supports conversion in both directions, conversion to the original type yields the original value, otherwise the resulting pointer cannot be dereferenced or called safely.

`GetProcAddress` 的情况和 `dlsym` 类似

**Comment by expnkx** [comment]
> n

难说。毕竟不知道mingw里自带的有没有处理这些东西。vc是没有严格别名机制优化的，而gcc是会优化的。

**Comment by DDoSolitary** [comment]
> 比如这个fs.cpp 违反严格别名机制。不能小转大我记得。

确实。。这里原来我用的C-style cast，后来想把代码里所有C-style cast，去了就全部改了，当时没考虑到strict aliasing rules。。

> 还有尽可能不要使用unique_ptr来管理非new的资源，这类还需要糊异常处理，光用unique_ptr往往擦不干净，还容易导致泄漏。

我就是不想手写专门的类才用的 `unique_ptr`。。

**Comment by expnkx** [comment]
> > 比如这个fs.cpp 违反严格别名机制。不能小转大我记得。
> 
> 确实。。这里原来我用的C-style cast，后来想把代码里所有C-style cast，去了就全部改了，当时没考虑到strict aliasing rules。。
> 
> > 还有尽可能不要使用unique_ptr来管理非new的资源，这类还需要糊异常处理，光用unique_ptr往往擦不干净，还容易导致泄漏。
> 
> 我就是不想手写专门的类才用的 `unique_ptr`。。

c style cast也是不对的。c style cast会调用reinterpret cast的。根本不行。

unique_ptr是垃圾设计。除了让对象movable以外根本没用。

**Comment by DDoSolitary** [comment]
> 最好还是糊一个位转换，不要用reinterpret_cast。 reinterpret_cast基本都是错误的。

这里的情况其实有点难以处理，我暂时没有用C++20的计划，所有不能用 `bit_cast`；而 `FILE_FULL_EA_INFORMATION` 的实际长度和结构体里定义的长度又是不同的，所以也不能用 `memcpy` 的方法

**Comment by expnkx** [comment]
> > 最好还是糊一个位转换，不要用reinterpret_cast。 reinterpret_cast基本都是错误的。
> 
> 这里的情况其实有点难以处理，我暂时没有用C++20的计划，所有不能用 `bit_cast`；而 `FILE_FULL_EA_INFORMATION` 的实际长度和结构体里定义的长度又是不同的，所以也不能用 `memcpy` 的方法

bit_cast其实就是memcpy实现的.C++20主要是能让bit_cast能在constexpr语义下用和能对象不初始化就能转。

**Comment by DDoSolitary** [comment]
另外，我一直在考虑要不要用Rust重写这个项目，我会的C++其实应该是一种“OI dialect”，很多写法都是以前搞OI的时候积累下来的经验，但没有系统的学习过，结果如你所见，很容易写出一些“it works”，但是却不符合标准的错误代码，而因为现在大学里破事太多我也没有时间重新系统学习一遍。。

**Comment by expnkx** [comment]
> 另外，我一直在考虑要不要用Rust重写这个项目，我会的C++其实应该是一种“OI dialect”，很多写法都是以前搞OI的时候积累下来的经验，但没有系统的学习过，结果如你所见，很容易写出一些“it works”，但是却不符合标准的错误代码，而因为现在大学里破事太多我也没有时间重新系统学习一遍。。

Rust屁事更多真的。调用C和C艹的API那是非常非常的痛苦

**Comment by DDoSolitary** [comment]
> Rust屁事更多真的。调用C和C艹的API那是非常非常的痛苦

我没有真的去做也就是考虑到目前项目里有大量的winapi的调用，用Rust的话势必要引入大量的unsafe代码。。

**Comment by expnkx** [comment]
> > Rust屁事更多真的。调用C和C艹的API那是非常非常的痛苦
> 
> 我没有真的去做也就是考虑到目前项目里有大量的winapi的调用，用Rust的话势必要引入大量的unsafe代码。。

真的很难的。你光把api糊一遍就基本上是一整个大项目了。boost winapi都几十万行

**Comment by expnkx** [comment]
其实自己糊一个类相比unique_ptr浪费不了多少时间，说不定还节约时间，api糊干净了，代码自然异常安全，非常的干净。任何错误都会立即报告。

同时建议使用T const&而不是const T&。

T const &
T const * const &
从右往左读
const和volatile的规则，从右往左读，没有左边的再修释右边的

**Comment by DDoSolitary** [comment]
>  const和volatile的规则，从右往左读，没有左边的再修释右边的

这我知道，单纯的习惯问题。。

**Comment by expnkx** [comment]
> > const和volatile的规则，从右往左读，没有左边的再修释右边的
> 
> 这我知道，单纯的习惯问题。。

并不是单纯的习惯问题。

我以前和你习惯是一样的。但把const写左边实际上是让规则变的复杂。

const是先修释左边的，没有左边的再修释右边的。

而写成右边的好处就在于可以把规则简化为
const修释左边的
