### ISSUE TITLE
Registering new distro "cannot recognise filesystem version"

### ISSUE THREAD

**Issue by xnegra80** [DDoSolitary/LxRunOffline#114]
I am not sure is it an ArchLinux problem. I downloaded Arch using the {distro}\{version} link and installed it. Then I manually duplicate the folder of the whole file system and tried to register it as a new distro. I have try exporting a config file and importing it but it still gives the same error. I have read the config file and it doesnt contain a filesystem version tag? its 2 in the case of arch.

cheers

是因這config沒有標明嗎？

**Comment by DDoSolitary** [comment]
> Then I manually duplicate the folder of the whole file system and tried to register it as a new distro. 

That won't work because some special file attributes required by WSL will not be copied if you copy the files using Windows Explorer.

**Comment by DDoSolitary** [comment]
The file system detection logic I wrote also relies on these attributes.

**Comment by xnegra80** [comment]
Ah i see. This happened because I was trying to sync my wsl to a cloud to I can use it on multiple devices. Should I install it on a usb drive instead? or is there another better way to do this. I am developing and I prefer my environment to be linux but i find it annoying to reconfigure it on multiple wsl instances.

**Comment by DDoSolitary** [comment]
Unfortunately, I don't know any cloud sync service that keeps the extended attributes required by WSL. As a workaround, you can install it into a vhdx disk and sync the disk file. However, that means you will have to upload the whole disk file after even trivial changes on the disk. So, in general, I think using a USB drive would be the optimal solultion.
