### ISSUE TITLE
提示文件被占用

### ISSUE THREAD

**Issue by lain-github** [DDoSolitary/LxRunOffline#118]
对wsl进行备份操作时, 提示文件被占用, 无权访问, 不知道是为什么, 我是重启电脑之后操作的.

[ERROR] Couldn't open the directory "\\?\C:\Users\LAIN\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\".
Reason: 另一个程序正在使用此文件，进程无法访问。

**Comment by DDoSolitary** [comment]
无法复现，建议尝试：

- 使用 `wsl -t` 命令完全关闭ubuntu后再尝试执行操作

或

- 使用资源管理器或一些第三方工具查看占用相关文件的进程

**Comment by lain-github** [comment]
> 
> 
> 无法复现，建议尝试：
> 
>     * 使用 `wsl -t` 命令完全关闭ubuntu后再尝试执行操作
> 
> 
> 或
> 
>     * 使用资源管理器或一些第三方工具查看占用相关文件的进程
可能是因为我本身就用wsl的命令行操作导致的, 现在用poweshell好了.
