### ISSUE TITLE
错误信息刷的太慢。原因是默认的cout流与stdio.h都没有缓冲。

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#119]
建议写到ostringstream里之后一次fwrite全部写掉。

**Comment by DDoSolitary** [comment]
我觉得没有必要，输出错误信息又不是常态，输出大量的错误信息就更加少见

**Comment by expnkx** [comment]
> 我觉得没有必要，输出错误信息又不是常态，输出大量的错误信息就更加少见

输出错误信息是常态。这种错误只发生在少量条件下的假设本来就是有问题的。
实话讲真的卡。光打个LxRunOffline就得刷好几下

**Comment by expnkx** [comment]
流这种out<<a<<b<<c的模式对非缓冲流非常不友好。每个数字输出都得刷新一次缓冲区。

**Comment by expnkx** [comment]
当然用我io库会更好很多。没有这些坑。二进制体积也小。相反流和stdio.h的坑太多了。
