### ISSUE TITLE
LxRunOffline 进行迁移操作时候停不下来

### ISSUE THREAD

**Issue by wkissw** [DDoSolitary/LxRunOffline#122]
版本：v3.4.1
原位置： D:\05.VM\WSL
迁移后位置： D:\05.VM\WSL\Ubnutu
执行命令： LxRunOffline.exe m -n Ubuntu -d D:\05.VM\WSL\Ubnutu

命令停不下来，不断生成新的文件夹
D:\05.VM\WSL\Ubnutu\Ubnutu\Ubnutu\Ubnutu\Ubnutu\Ubnutu\Ubnutu\Ubnutu\Ubnutu\........
![Snipaste_2020-05-13_11-02-50](https://user-images.githubusercontent.com/18184630/81766957-d7716a80-9509-11ea-9f63-f726e68b8470.png)

**Comment by DDoSolitary** [comment]
估计时因为原位置和新位置嵌套了，所以程序在枚举原位置里的文件的时候把复制产生的新文件也算进去了。

**Comment by DDoSolitary** [comment]
这个用法我不打算支持，不过会对这类情况加个检测直接报错退出。建议先把原位置移动到一个名字不同的新位置，再移动到目标位置
