### ISSUE TITLE
Move temp folder to ram disk

### ISSUE THREAD

**Issue by ertwro** [DDoSolitary/LxRunOffline#124]
Hi, I would like to move the temp folder that's normally located next to rootfs to ram in wsl1. Since there's no way to create a joint or symlink that would be recognized I would like to do this with this tool maybe.

**Comment by DDoSolitary** [comment]
Sorry, LxRunOffline is unable to perform this task, and I'm not aware of any approach to achieve this.

BTW, as far as I know the temp folder doesn't store any regular files and it has 0 bytes on disk according to the Windows's property page. So I doubt there will by any performance improvements by doing so.
