### ISSUE TITLE
找不到库。我装了也没找到。

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#125]
D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/11.0.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -larchive
D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/11.0.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ltinyxml2
D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/11.0.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llzma

**Comment by DDoSolitary** [comment]
怎么装的

**Comment by DDoSolitary** [comment]
我自己就用msys编译的，没有碰到过这样的问题，我感觉是你没装好（

**Comment by DDoSolitary** [comment]
Closing as no response
