### ISSUE TITLE
我找到你这个库很多性能问题。而且我随便改动一下性能就能提升一倍。我都没改几行

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#126]
同时建议把所有函数全部内联和常量表达式掉，同时不要用滥用翻译单元。inline函数linker会直接丢掉多的。你用翻译单元就会导致二进制膨胀

**Comment by expnkx** [comment]
https://github.com/expnkx/LxRunOffline/commit/6300a38a6334cdc2d4dbf90312ef320ea087db54

**Comment by DDoSolitary** [comment]
我不认为输出错误信息的些许差异是什么“性能问题”，没必要在这种地方追求性能。
另外我觉得我这称不上滥用翻译单元，与其为了inline把所有代码糊成一坨放在一个文件里，不如把lto开起来（回头就开，vs的release应该是默认开了的）

**Comment by expnkx** [comment]
> 我不认为输出错误信息的些许差异是什么“性能问题”，没必要在这种地方追求性能。

这就和假定异常只发生在少数情况下一样的问题。你这种假设是错误的

> 另外我觉得我这称不上滥用翻译单元，与其为了inline把所有代码糊成一坨放在一个文件里，不如把lto开起来（回头就开，vs的release应该是默认开了的）

这和lto没有任何关系。如果你不写inline，编译器不管你用到没用到那个函数都会生成。开lto并不会移除掉无用函数。

**Comment by expnkx** [comment]
https://godbolt.org/z/PoDJ97

比如这个f()函数我根本没用到，但编译器还是把这个生成了。开lto也不会移除。必须写inline编译器才会移除无用函数。

inline的意思根本就不是内联。就是告诉linker如果碰到重复定义就抛弃。这种情况下编译器才敢把函数移除，否则谁知道是否有负作用？

**Comment by DDoSolitary** [comment]
> 这就和假定异常只发生在少数情况下一样的问题。你这种假设是错误的。我已经很明显的感觉到慢了。

如果你指的是你的commit里改的那些帮助信息，我坚持认为为了对它进行性能优化而引入额外的库或是增加额外的复杂性是没有必要的。如果你觉得这种差异无法忍受，或者是你的use case需要大量反复调用help，请不要使用这个项目，自己fork自己编译去。

> 比如这个f()函数我根本没用到，但编译器还是把这个生成了。开lto也不会移除。必须写inline编译器才会移除无用函数。

如果f我根本没用到，我应该做的不是把它标上inline而是把它删了

**Comment by DDoSolitary** [comment]
至于重复定义，我没有在header里放任何除了template以外的函数，所以其他函数不存在重复定义的问题，而就这少数几个函数（我没记错的话好像就一个吧），造成的二进制膨胀我认为可以忽略不计。而且我印象中template的重复定义应该是会被linker移除的（我不是很确定）

**Comment by expnkx** [comment]
> > 这就和假定异常只发生在少数情况下一样的问题。你这种假设是错误的。我已经很明显的感觉到慢了。
> 
> 如果你指的是你的commit里改的那些帮助信息，我坚持认为为了对它进行性能优化而引入额外的库或是增加额外的复杂性是没有必要的。如果你觉得这种差异无法忍受，或者是你的use case需要大量反复调用help，请不要使用这个项目，自己fork自己编译去。
> 
> > 比如这个f()函数我根本没用到，但编译器还是把这个生成了。开lto也不会移除。必须写inline编译器才会移除无用函数。
> 
> 如果f我根本没用到，我应该做的不是把它标上inline而是把它删了

我没有commit.只是证明你这里性能确实有问题。因为你用的宽字符，C++ wfstream locale转码特别特别慢。

"如果f我根本没用到，我应该做的不是把它标上inline而是把它删了"
你想把它删掉的正确做法就是加inline. inline就是告诉linker丢弃同样函数。

template自带inline. 但只要是翻译单元，都会膨胀。header only是最好的。

**Comment by expnkx** [comment]
建议你读下这篇论文
https://www.usenix.org/system/files/conference/usenixsecurity18/sec18-quach.pdf



```cpp

Unused Functions. Static analysis during compilation
can efficiently remove dead code at a basic block level,
however, entire unused functions are not eliminated.
Consider the following program:
int f() { return 1; }
int main() { return 0; }
Both gcc and clang retain the function f in
the above code even under optimization level
-O3. Removal of unused functions require additional non-standard often-unused compiler
(-fdata-sections -ffunction-sections -Os)
and linker (-Wl,--gc-sections) optimization flags.
Even so, unused functions in dynamically loaded
libraries can not be eliminated during compile time
```cpp

**Comment by expnkx** [comment]
养成所有函数写inline的好习惯。不要用static。

**Comment by DDoSolitary** [comment]
> 我并没有commit.只是证明你这里性能确实有问题。因为你用的宽字符，C++ wfstream locale转码特别特别慢。

我说的是你的comment里链接的那条commit，是名词，不是动词。
如果你希望优化输出的性能，请先证明在某种正常而且要求高性能的使用情况下输出会成为瓶颈，不要告诉我你希望输出帮助信息高性能。

>  你想把它删掉的正确做法就是加inline. inline就是告诉linker丢弃同样函数。

请理清楚逻辑
首先，如果是普通函数，放到header里的话我肯定加inline，但是我就没放到header里，而没放到header里的话，如果它还没被用到，就说明整个项目都没用到，那我留着它干什么，直接把代码删了就完事了。
完全没用到的函数是代码本身的问题，应该自己删掉，而不应该依赖编译器处理。
然后如果是template函数，没用到就不会实例化，自然不存在任何问题。

> template自带inline. 但只要是翻译单元，都会膨胀。各种各样的OOP虚函数膨胀就更厉害了，因为编译器根本没办法干掉无用的虚函数。header only是最好的

谁跟你说template自带inline，就我所知不是，请拿出证据
一个虚函数只会被生成一次吧，如果它无用，同样把函数删了就是

> 你把这个<<全去掉都会提高性能。简尔言之不用C++流就是最好的。msvc的流比gcc还要慢10倍，所以你这里就是非常非常慢。

把多个<<合成一个确实是有道理的，我会改的

> 建议你读下这篇论文

我这会儿没工夫细看，但是就你引用的这部分来说是无法说服我的

首先我还是那句话，既然这个f完全没被用到，就应该把这部分代码删了，而不是等着编译器把它扔掉
然后编译器不扔掉f很正常，因为编译时不知道其他翻译单元有没有用到这个函数，所以不能指望编译时优化
而且解决方法很简单，第一开启lto，这个函数就会被扔掉了，第二，把函数声明成static，编译器就会知道这个函数只在这个翻译单元里被使用，没用到也会被删掉。（以上两条我刚刚都测试了，确实被删掉了，这也说明了你说的“比如这个f()函数我根本没用到，但编译器还是把这个生成了。开lto也不会移除。”是错误的）

**Comment by DDoSolitary** [comment]
关于输出的性能问题，我整理了一下，我的代码里大概就三类输出：

- 帮助信息：只一次输出少量信息，没必要优化，但是合并多个<<会加的
- 错误信息：只输出一次就会退出程序，而且输出的量比帮助信息还少，更没必要优化
- 警告信息：这是确实存在一些问题的，有时候如果给的安装包里面有很多不支持的文件（设备文件之类的），就会输出不少警告信息，影响安装速度，我会考虑通过缓冲然后一次性输出之类的方法改进

**Comment by expnkx** [comment]
"首先，如果是普通函数，放到header里的话我肯定加inline，但是我就没放到header里，而没放到header里的话，如果它还没被用到，就说明整个项目都没用到，那我留着它干什么，直接把代码删了就完事了。"

首先我不是来改你项目的。我是告诉你哪里会有问题而已。我不可能提交代码的。只是因为我教授需要我找些项目证明一下把流换掉可以提高性能我好写在论文里。


这里问题在于如果整个项目你也没用到，编译器也不会把函数删掉。这就是蠢的地方了。你要是不信你可以试试编译一个项目出来，你不写inline，那个函数还会在二进制里。

**Comment by expnkx** [comment]
"谁跟你说template自带inline，就我所知不是，请拿出证据"

关于名词和动词的问题。对于汉语这种语言而已本身动词不过是一种名词而已。

模板,constexpr和类内成员函数默认inline.
https://stackoverflow.com/questions/3694899/c-template-and-inline

现在inline的意思就是防止编译器违反ODR. 有了inline以后当链接器看到不同翻译单元的多重定义的时候就会丢弃。
模板如果不隐含内联那你不是炸了？

**Comment by DDoSolitary** [comment]
第一，在编译器蠢之前，首先是写代码的人蠢。写代码的人不应该依赖编译器把根本没用到的函数删掉，而是应该自己把没用的代码删掉。就算自己没发现，也可以通过ide的静态分析发现。这种事就根本不应该让编译器去管。

第二，它没删掉是因为你没用好，我说了，开了lto就删掉了，你没开却怪它没删掉不是很搞笑

> 首先我不是来改你项目的。我是告诉你哪里会有问题而已。我不可能提交代码的。只是因为我教授需要我找些项目证明一下把流换掉可以提高性能我好写在论文里。

我并不是对你提出改动的建议这件事本身有意见，问题是你提出的建议大多是站不住脚的，无论这些改动是否是要放到我的代码里，它们站不住脚这点是不会改变的

**Comment by DDoSolitary** [comment]
>  模板如果不隐含内联那你不是炸了？

好吧我理解错你的意思了，我是指模板不会默认进行字面意义上的”内联“

**Comment by expnkx** [comment]
> 第一，在编译器蠢之前，首先是写代码的人蠢。写代码的人不应该依赖编译器把根本没用到的函数删掉，而是应该自己把没用的代码删掉。就算自己没发现，也可以通过ide的静态分析发现。这种事就根本不应该让编译器去管。
> 
> 第二，它没删掉是因为你没用好，我说了，开了lto就删掉了，你没开却怪它没删掉不是很搞笑

不不不。开lto并不会把无用函数代码删掉,这是一种常见的误解。必须得用违反标准的-ffunction-sections -fdata-sections -Wl,--gc-sections才能干掉一部分，并不能干掉全部，（就是那篇安全论文说的），包括glibc, libstdc++都需要这么干才能干掉一部分。而且违反标准。不写inline是第一大二进制膨胀的根源。很多人误把inline理解成展开是完全不正确的。如果你不需要强制的外部链接，全部都应该inline掉。

**Comment by DDoSolitary** [comment]
> 不不不。开lto并不会把无用函数代码删掉,这是一种常见的误解

我说了，我测试的结果是可以，你这么说就很讽刺
