### ISSUE TITLE
Can't move docker-desktop and docker-desktop-data

### ISSUE THREAD

**Issue by xspeed1989** [DDoSolitary/LxRunOffline#127]
[ERROR] Couldn't open the directory "\\?\\\?\C:\Users\John\AppData\Local\Docker\wsl\distro\".
Reason: 文件名、目录名或卷标语法不正确。
PS D:\Software\LxRunOffline> .\LxRunOffline.exe move -n docker-desktop-data -d E:\WSL\docker-desktop
[ERROR] Couldn't open the directory "\\?\\\?\C:\Users\John\AppData\Local\Docker\wsl\data\".
Reason: 文件名、目录名或卷标语法不正确。

**Comment by lscgzwd** [comment]
the same.

**Comment by xspeed1989** [comment]
> the same.

If you are a c/c++ developer, you can modify the source and compile by yourself
you can find MoveFile function in main.cpp, just trim left 3 charaters at the srcpath

**Comment by xspeed1989** [comment]
The issue still exists

**Comment by xspeed1989** [comment]
> > the same.
> 
> If you are a c/c++ developer, you can modify the source and compile by yourself
> you can find MoveFile function in main.cpp, just trim the left 3 characters of the src path

The issue still exists

**Comment by xspeed1989** [comment]
> > the same.
> 
> If you are a c/c++ developer, you can modify the source and compile by yourself
> you can find MoveFile function in main.cpp, just trim the left 3 characters of the src path

@DDoSolitary 
The issue still exists

**Comment by DDoSolitary** [comment]
@xspeed1989 Couldn't reproduce locally. Which version are you using?

**Comment by yunnysunny** [comment]
When use LxRunOffline-v3.5.0-msvc.zip , it will come up the error above. But weh use LxRunOffline-v3.5.0-mingw.zip , it works ok.
