### ISSUE TITLE
你好，关于你所谓的lto是否移除无用函数的问题，我试了下。

### ISSUE THREAD

**Issue by expnkx** [DDoSolitary/LxRunOffline#129]
写了个hello world。我试了三种情况。第一种是开-flto,第二种是开-fdata-sections -ffunction-sections -Wl-gc-sections.第三种是开 -fdata-sections -ffunction-sections -Wl-gc-sections -flto
![image](https://user-images.githubusercontent.com/57303909/84991228-3da66a00-b114-11ea-8f25-6985bb1267a8.png)

![image](https://user-images.githubusercontent.com/57303909/84991294-544cc100-b114-11ea-90c4-82decb16be66.png)

可以看到lto并不能移除无用函数。

**Comment by DDoSolitary** [comment]
首先，你这测试方法就导致测试结果没有意义，比较gc-sections和lto的文件大小只能说明在前者在优化二进制大小上效果更好，并不能说明lto不能移除无用函数，建议用lto和没有lto的编译结果进行比较
第二，就算比较有没有lto的编译结果，单纯比较代码大小意义不大，因为lto做的事情不止一件，没法控制变量，我的测试方法是用nm查看编译结果里的符号，看有没有那个无用函数的符号
第三，抱歉我之前忘了说了，我测试的是-O3和-flto -O3这两者，也就是都开了-O3优化。我刚刚又试了一下，只有lto确实还是不够，得lto加上O3才会移除无用函数

**Comment by expnkx** [comment]
> 首先，你这测试方法就导致测试结果没有意义，比较gc-sections和lto的文件大小只能说明在前者在优化二进制大小上效果更好，并不能说明lto不能移除无用函数，建议用lto和没有lto的编译结果进行比较
> 第二，就算比较有没有lto的编译结果，单纯比较代码大小意义不大，因为lto做的事情不止一件，没法控制变量，我的测试方法是用nm查看编译结果里的符号，看有没有那个无用函数的符号
> 第三，抱歉我之前忘了说了，我测试的是-O3和-flto -O3这两者，也就是都开了-O3优化。我刚刚又试了一下，只有lto确实还是不够，得lto加上O3才会移除无用函数
> 第四，测试的话还请把测试用代码放出来

```cpp
#include<iostream>
int main()
{
    std::cout<<"Hello World\n";
}
```

**Comment by DDoSolitary** [comment]
我的测试代码：
```c++
int orz() {
    return 1;
}

int main() {
    return 0;
}
```

编译命令：

```
g++ t.cpp -O3 -o t.exe
g++ t.cpp -flto -O3 -o t_lto.exe
```

测试结果：

```
$ nm t.exe | grep orz
0000000000401550 T _Z3orzv
$ nm t_lto.exe | grep orz
0000000000000000 A _Z3orzv
```

可见开启lto以后只剩一个空的符号了，生成的代码已被移除
这个类型为A（absolute）的符号应该是lto工作时生成的，不指向特定代码

**Comment by DDoSolitary** [comment]
你这测试代码就很离谱，不测试特定函数能说明什么？
就像我之前说的，只能说明这些参数在优化代码大小方面的效果，不能说明lto能否移除无用函数
另外这个issue就真的off topic了，和我这项目半毛钱关系都没有
