### ISSUE TITLE
Install to different drive than the LxRunOffline executable

### ISSUE THREAD

**Issue by DDoSolitary** [DDoSolitary/LxRunOffline#13]
It seems that the only solution is to copy the executable to the target drive automatically.

**Comment by Biswa96** [comment]
Does not the `Directory.Move` method work?

**Comment by DDoSolitary** [comment]
Directory.Move only works when moving within the same drive. Moving between drives always require copy&delete, which causes loss of NTFS extended attributes.

**Comment by Biswa96** [comment]
OK, that's weird. Even also the `move rootfs D:\` command in Command Prompt does not work to move rootfs directory. It shows `Access is denied`. But if I move directory with just Ctrl+X and Ctrl+V, then change `BasePath` registry of that distro, it works.

**Comment by DDoSolitary** [comment]
Ctrl+X&Ctrl+V automatically falls back to copy&delete when necessary, but it is strange that this method works with WSL. When I tested several months ago, all NTFS extended attributes lost after copying between drives, maybe Microsoft has fixed the problem. I'll test it and if it works, I can use Directory.Copy when Directory.Move is inappropriate.

**Comment by DDoSolitary** [comment]
Well, Windows showed that there are several files already exist even when I was copying to an empty directory. I don't know what happened. But after I chose to overwrite them, bash can be lauched without problems and file permission is fine. It seems that Windows do copy NTFS extended attributes.

**Comment by DDoSolitary** [comment]
Microsoft/WSL#997

**Comment by DDoSolitary** [comment]
Fixed in e9321e9ae42b640331801680fdca9681349619de.
