### ISSUE TITLE
Recursive loop when moving a WSL2 distro to a subfolder of its current folder

### ISSUE THREAD

**Issue by minorgod** [DDoSolitary/LxRunOffline#130]
I just had a strange thing happen LxRunOffline v3.4.1 to move a kali-linux distro. I had just accidentally moved it to a new location that did not contain a subfolder for the distro....

```lxrunoffline move -n kali-linux -d C:\wsl\```

This resulted in my .vhdx and other distro files just getting dumped into the main C:\wsl\ folder with no "kali-linux" sub-directory. Since I wanted the files in a sub-directory called "kali-linux" I then ran:

```lxrunoffline move -n kali-linux -d C:\wsl\kali-linux\```

This seemed to take forever compared to the first move, but after about 15-20 minutes it finally failed with an error saying there was not enough room on my drive. The distro files were still in their original location, but there was also a new "kali-linux" directory next to them. I opened it and found copies of the distro files along with another "kali-linux" sub-directory. I opened that and there was yet another set of distro files and another "kali-linux" sub-dir. This continued indefinitely...: 

```C:\wsl\kali-linux\kali-linux\kali-linux\kali-linux\kali-linux\kali-linux\....```

Fortunately it did not cause any permanent issues. I simply deleted the first "kali-linux" dir to free up all the lost HD space. Then I re-did the move, but first moved the distro to a new temporary root directory with the desired sub-directory structure...

```lxrunoffline move -n kali-linux -d C:\wsl-temp\kali-linux\```

Then I ran:

```lxrunoffline move -n kali-linux -d C:\wsl\kali-linux\```

This procedure worked fine -- my distro was now successfully moved to C:\wsl\kali-linux\.

**Comment by DDoSolitary** [comment]
It seems to be the same issue as #122, which has been fixed. Could you please try the [latest dev build](https://dl.bintray.com/ddosolitary/dev-releases/LxRunOffline/) and let me know if the bug still exists?
