### ISSUE TITLE
sudo causes powershell error when running wsl 2

### ISSUE THREAD

**Issue by finsterdexter** [DDoSolitary/LxRunOffline#137]
What I did to install this distro:

1. Removed all microsoft store distros. At this point `wsl -l` shows no distros.
2. Downloaded Ubuntu 20.04 from the tianon source.
3. `.\LxRunOffline.exe i -n UF -d D:\WSL\UbuntuFocal -f .\focal.tar.gz -s`
4. `wsl --set-version UF 2`
5. Run `wsl` and find that I'm running bash as root.
6. Add a user in wsl.
7. `.\LxRunOffline.exe set-uid -n UF -v 1000`

At this point, I run `wsl` and attempt to install wget:

```
finster@finster-pc:~$ sudo apt-get update
apt-get : The term 'apt-get' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ apt-get update
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (apt-get:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

finster@finster-pc:~$ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
```

As you can see, running `apt-get` under `sudo` causes a powershell error to pop up. Running without `sudo` uses the apt-get within the distro.

Another example:

```
finster@finster-pc:~$ which apt-get
/usr/bin/apt-get
finster@finster-pc:~$ sudo which apt-get
which : The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ which apt-get
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I should note that running any of these commands as root `wsl -u root` work as expected, i.e. `apt-get update` performs the update as expected. This is a super weird issue, and admittedly, I don't know enough about how the underlying wsl 2 system works to be able to figure this out.

**Comment by DDoSolitary** [comment]
Could you please check if you have anything named sudo or sudo.exe in your Windows PATH?

**Comment by finsterdexter** [comment]
holy cats, Yeah that's the problem. I feel like a doof. Thanks.
