### ISSUE TITLE
Wiki is incorrect about Fedora

### ISSUE THREAD

**Issue by luc-j-bourhis** [DDoSolitary/LxRunOffline#138]
The wiki says images can be found at https://lxrunoffline.apphb.com/download/Fedora, defaulting to rawhide, but this gives a 404. Either the wiki or  lxrunoffline.apphb.com should be updated.

**Comment by DDoSolitary** [comment]
It seems that the repo it relies on no longer provides the image named "rawhide". I just updated the website to use the latest version number, which should be the current development version. Could you please check if it works now?

**Comment by luc-j-bourhis** [comment]
https://lxrunoffline.apphb.com/download/Fedora does now get me to Fedora 33, i.e. what you wrote. The mention of rawhide should also be removed from the wiki. Thanks.

**Comment by DDoSolitary** [comment]
Well, they're generally the same thing. Rawhide is "the name given to the current development version of Fedora", according Fedora's [official wiki](https://fedoraproject.org/wiki/Releases/Rawhide). If you take a look at the file you downloaded, you'll find that it does use the rawhide repository (`/etc/yum.repos.d/fedora-rawhide.repo`). And on Docker Hub, the [Fedora's official images](https://hub.docker.com/_/fedora?tab=tags) also has its `33` and `rawhide` tags point to exactly the same image. So I don't see any problems calling the image you got "rawhide".

**Comment by luc-j-bourhis** [comment]
Oh, sorry, I didn’t notice that https://lxrunoffline.apphb.com/download/Fedora/rawhide works again! That was my point. Ok, so everything back in order. Thanks for maintaining those redirections: very time saving.
