### ISSUE TITLE
Import error Ubuntu 20.10

### ISSUE THREAD

**Issue by happysat** [DDoSolitary/LxRunOffline#142]
Trying to import previously made backup results in:

[ERROR] Couldn't create the file "\\?\C:\Ubuntu-20.10\rootfs\usr\lib\systemd\system\system-systemd\x2dcryptsetup.slice".
Reason: The system cannot find the path specified.

Guessing the * is a showstopper in filename x2dcryptsetup*.slice
Removing this file and backup/import again works.

**Comment by happysat** [comment]
Import works now, i tried a fresh build no problems.
Thanks for fixing DDoSolitary!

**Comment by Carsten87** [comment]
@DDoSolitary thanks for the great Tool. I ran into the same issue. Will this fix be released soon? The link to the patched build seems to be dead: https://dl.bintray.com/ddosolitary/dev-releases/LxRunOffline/LxRunOffline-v3.5.0-7-gf1a59d4-msvc.zip

**Comment by DDoSolitary** [comment]
@Carsten87 I moved hosting site of my dev builds. Now the files are available here: https://ddosolitary-builds.sourceforge.io/LxRunOffline/
