### ISSUE TITLE
Cannot call WSL in jetbrains development tool

### ISSUE THREAD

**Issue by mrcxs** [DDoSolitary/LxRunOffline#143]
How to register to the system layer so that the ide tool can open the wsl environment. The WSL installed in the store can be identified in the development tool. WSL running with LxRunOffline cannot be recognized by development tools.

**Comment by DDoSolitary** [comment]
It seems that JetBrains IDEs use the executables provided by store apps (e.g. ubuntu.exe) to launch WSL. I not sure about how they detect the store apps, but I don't think it can be easily configured on my side. I would suggest to contact JetBrains support or simply configure SSH server manually and use a Remote Host toolchain instead.

**Comment by Pikachews** [comment]
Although it can't be automatically placed by installing through LxRunOffline, it seems to be possible to manually configure. This seems to be working for me so far:

Create a batch file somewhere, probably next to where ever your distribution is, with the following contents:
```
C:\path\to\LxRunOffline.exe run -n <distro name> -c %2
```

Find the `wsl.distributions.xml` file for your respective Jetbrains application (e.g. for WebStorm installed through JetBrains Toolbox, it seems to be located in `C:\Users\<user>\AppData\Roaming\JetBrains\WebStorm<version>\options\wsl.distributions.xml`) and an entry pointing to your batch file:
```
        <descriptor>
          <id>UNIQUE_NAME</id>
          <microsoft-id>DISTRIBUTION_NAME</microsoft-id>
          <executable-path>C:\path\to\batch-file.bat</executable-path>
          <presentable-name>DISPLAY_NAME</presentable-name>
        </descriptor>
```

Restart the JetBrains application and the distribution you added should now show up.

**Comment by DDoSolitary** [comment]
It seems that the list of automatically detected distros is hard-coded so there's nothing I can do to make distros installed by LxRunOffline detectable: http://git.jetbrains.org/?p=idea/community.git;a=blob;f=platform/platform-impl/src/com/intellij/execution/wsl/WSLDistributionService.java;hb=HEAD
