### ISSUE TITLE
WSL Shell prompt doesn't show up for custom installation

### ISSUE THREAD

**Issue by VPraharsha3** [DDoSolitary/LxRunOffline#144]
I installed a rootfs tarball of Devuan [from here](https://jenkins.linuxcontainers.org/view/Images/job/image-devuan/architecture=amd64,release=beowulf,variant=default/) using LxRunOffline.
When i try launching the distro using `LxRunOffline run -n <DistroName>` the shell prompt of the distro doesn't show up and returns nothing but it is still running when i checked using `wsl -l -v` command. I've tried two different methods apart this, what am i missing here ? Am i using a wrong image ? 
![dev](https://user-images.githubusercontent.com/56556436/91638691-f0594980-ea2e-11ea-89e7-1e9c4afc1b0b.jpg)

I've tried alpine and it works fine.

**Comment by DDoSolitary** [comment]
Unable to reproduce on my machine. I tried the tarball from the link you provided and it works fine for me.

**Comment by VPraharsha3** [comment]
I've no clue. I followed the steps by first converting .xz to .gz, i've tried two different tools before using LxRunOffline

**Comment by VPraharsha3** [comment]
I figured it out, I tried `LxRunOffline` again but with the original .xz tarball file and it worked out well.
In Earlier case, to use it with a different distro launcher i had to convert .xz file to .gz for the launcher to pick it up. The conversion was not properly done as inspected with 7-zip.  I had to use `--hard-dereference` option with tar command to fix this.

**Comment by DDoSolitary** [comment]
I'm just about to set up a VM to test in the Windows version you're using. Glad to see that you've solved it yourself.

FWIW, if you want to change compression format of a tar file, it would be safer to use corresponding compression utilities directly, which will not touch the inner tar format. For example to convert rootfs.tar.xz to rootfs.tar.gz, you can simply run `xz -d rootfs.tar.xz` and then `gzip rootfs.tar`.

**Comment by VPraharsha3** [comment]
@DDoSolitary I was very much sure it wasn't an issue with **WSL**, I doubted the container image first and even decided making my own rootfs tarball.
