### ISSUE TITLE
Allow to specify the user in an argument with the "run" command

### ISSUE THREAD

**Issue by alisci01** [DDoSolitary/LxRunOffline#145]
Current WSL has the feature of specifying the user on the command line. While we can do this by resetting the default UID, the convenience of a user argument would be nice.

**Comment by DDoSolitary** [comment]
Unfortunately, Microsoft doesn't provide public API that allows specifying user on start. `wsl.exe` uses some private COM API that can't be relied upon.

**Comment by DDoSolitary** [comment]
If you just want to launch an interactive shell with a specific user, it can be simply done by `LxRunOffline run -n <distro name> -c "su - <user name>`

**Comment by jchomarat** [comment]
Hello,

I am not sure if it's related, but it would be great to be able to set a default user at the distro level, as we would do using the "[standard store approach](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#change-the-default-user-for-a-distribution)"

`<DistributionName> config --default-user <Username>`

One side effect I have for not being able to do it, is, when I use vscode and the Remote-WSL plugin, it logs in with Root - whereas on a terminal I can start my distro with the -u parameter to set my user to use as a login.

Cheers

**Comment by jchomarat** [comment]
My bad, came across

`
LxRunOffline.exe set-uid -n Name_of_Distro -v user_UID
`

So no issue on my side

**Comment by AlienKevin** [comment]
Note for those who don't know their UID (User Identifier), you can run
```
cat /etc/passwd | grep <username>
```
in your wsl terminal to get something like:
```
<username>:x:1000:1000:,,,:/home/<username>:/usr/bin/zsh
```
In the above case, `1000` is the UID for `<username>`.

Next, proceed to run the `set-uid` command as follows in Cmd:
```
LxRunOffline.exe set-uid -n Name_of_Distro -v UID
```

Reference: https://geek-university.com/linux/uid-user-identifier-gid-group-identifier/
