### ISSUE TITLE
[ERROR] the option '-d' is required but missing

### ISSUE THREAD

**Issue by shakthifuture** [DDoSolitary/LxRunOffline#146]
![image](https://user-images.githubusercontent.com/2995544/92991294-9d889300-f500-11ea-9ebf-8fad419d0957.png)

**Comment by shakthifuture** [comment]
Why I am getting this error?

**Comment by DDoSolitary** [comment]
This tool provides a conventional CLI interface and you're expected to run it with proper command line arguments. Meaning of these arguments are already explained in the image you posted.
