### ISSUE TITLE
"Directory not empty" error when reading existing distros

### ISSUE THREAD

**Issue by WitherZuo** [DDoSolitary/LxRunOffline#150]
尝试移动 Ubuntu WSL2 的位置时出错：
![image](https://user-images.githubusercontent.com/25317916/97376835-624bf300-18f9-11eb-9078-76e90f197cc3.png)

原因似乎是要删除的目录`\\?\C:\Users\thinkpad\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\`不为空？但是该目录是 Ubuntu 分发版的存放目录，人工删除会导致分发版无法识别……

**Comment by XuCpeng** [comment]
same problem

**Comment by mbryantII** [comment]
just encountered the same issue.

![image](https://user-images.githubusercontent.com/21065285/97609984-8bd84d80-19d1-11eb-898b-f6ff39c777aa.png)

**Comment by DDoSolitary** [comment]
Thanks for reporting this. I can reproduce the error on my PC as well, and I need some time to investigate.

**Comment by DDoSolitary** [comment]
I got a similar error when trying to set the flag directly using `fsutil file setCaseSensitiveInfo`. I'm not sure why this is happening. Probably Microsoft decides to make this flag changeable only for empty directories.

**Comment by DDoSolitary** [comment]
@XuCpeng  @mbryantII @WitherZuo Are you using Insider builds of Windows? I just did some testing and it seems that the latest stable build (19042) doesn't have this issue. Could you please provide the build number of your system so that I can find out the version that broke it?

**Comment by mbryantII** [comment]
I just updated last night, reran the scenario, and encountered the same issue.  Currently running on winver 2004 build 20246.1 (Dev Channel)

**Comment by yaodio** [comment]
When could we get the new release with this bug fix?

**Comment by winkee01** [comment]
My windows build is 21364.100 and the problem still exists.

**Comment by DDoSolitary** [comment]
@winkee01 What's the version of LxRunOffline you're using? Currently only the dev snapshots include the fix.

**Comment by winkee01** [comment]
> @winkee01 What's the version of LxRunOffline you're using? Currently only the dev snapshots include the fix.

V3.5.0

**Comment by DDoSolitary** [comment]
@winkee01 Please try this build: https://ddosolitary-builds.sourceforge.io/LxRunOffline/LxRunOffline-v3.5.0-11-gfdab71a-msvc.zip

**Comment by winkee01** [comment]
thank you, this time it works.

**Comment by winkee01** [comment]
But I guess it still has some bugs, because after I moved it to `D:\WSL\` directory, the directory `D:\WSL\` was removed, and subdirectories inside `D:\WSL\` were moved out. 
For example, I have `D:\WSL\ubuntu18.04\ext4.vhdx` already, and now I want to move ubuntu(20.04) to `D:\WSL\`, now my directory becomes:

```
D:\ubuntu18.04\ext4.vhdx
D:\ext4.vhdx
```

**Comment by 0rekur4m** [comment]
> @winkee01 Please try this build: https://ddosolitary-builds.sourceforge.io/LxRunOffline/LxRunOffline-v3.5.0-11-gfdab71a-msvc.zip

know it's been a while, but how can I try that build?

**Comment by kongdd** [comment]
> @winkee01 Please try this build: https://ddosolitary-builds.sourceforge.io/LxRunOffline/LxRunOffline-v3.5.0-11-gfdab71a-msvc.zip

This version also works for me. 
Wondering why not upload this version into the release page.

**Comment by moyans** [comment]
@DDoSolitary  "https://ddosolitary-builds.sourceforge.io/LxRunOffline/LxRunOffline-v3.5.0-11-gfdab71a-msvc.zip"  invalid url

**Comment by unity20221019** [comment]
can u upload this zip . now invalid url

**Comment by lsyxiaopang** [comment]
The url is invalid, maybe you need to fix it.

**Comment by Andy1208-lee** [comment]
> @DDoSolitary "https://ddosolitary-builds.sourceforge.io/LxRunOffline/LxRunOffline-v3.5.0-11-gfdab71a-msvc.zip" invalid url

I put it into my project and I have used it successfully. I hope it will be helpful to you。[https://github.com/Andy1208-lee/LxRunOffline](https://github.com/Andy1208-lee/LxRunOffline)

**Comment by Zxis233** [comment]
> > @DDoSolitary "https://ddosolitary-builds.sourceforge.io/LxRunOffline/LxRunOffline-v3.5.0-11-gfdab71a-msvc.zip" invalid url
> 
> I put it into my project and I have used it successfully. I hope it will be helpful to you。https://github.com/Andy1208-lee/LxRunOffline

Hey Bro Thanks a lot! U R the really HERO!
