### ISSUE TITLE
Add the package to Windows Package Manager

### ISSUE THREAD

**Issue by mbryantII** [DDoSolitary/LxRunOffline#151]
the windows package manager is becoming a positive tool, like other package managers that you have called out.  I fell that this could increase the coverage of your tool since the package manager is baked directly into windows.  

How to create the schema file
https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema

How to submit the manifest
https://docs.microsoft.com/en-us/windows/package-manager/package/repository

**Comment by DDoSolitary** [comment]
I don't have the time maintain packages for multiple package managers that I don't even use. Probably you can submit a package yourself if you have the time to maintain it (fix packaging issues, keep things up-to-date, etc).
