### ISSUE TITLE
duplicate operation is not recognizing required arguments

### ISSUE THREAD

**Issue by mbryantII** [DDoSolitary/LxRunOffline#152]
attempting to run the duplicate operation, the -n flag is not being recognized on LxRunOffline v3.5.0

`lxrunoffline duplicate -n Ubuntu-20.04 -d E:\wsl\`

returns
```
[ERROR] the option '-N' is required but missing

Options:
  -n arg                Name of the distribution
  -d arg                The directory to copy the distribution to.
  -N arg                Name of the new distribution.
  -c arg                The config file to use. This argument is optional.
  -v arg (=4294967295)  The version of filesystem to use, same as source if not
                        specified.

```

![image](https://user-images.githubusercontent.com/21065285/97610605-5849f300-19d2-11eb-960c-20a70be3a010.png)

**Comment by DDoSolitary** [comment]
`-N` is different from `-n`

**Comment by mbryantII** [comment]
I found out my mistake here, after you closed it. but once I ran the operation i get the same error that was found #150 

![image](https://user-images.githubusercontent.com/21065285/97677589-b49f2800-1a4f-11eb-884c-b9bb491dc460.png)
