### ISSUE TITLE
When used LxRunOffline to install CentOS 8 ，an error occurred

### ISSUE THREAD

**Issue by RayTigerZ** [DDoSolitary/LxRunOffline#154]
C:\tools\lxrunoffline\LxRunOffline.exe  i -n centos8 -d .\WSL\centos8\ -f .\CentOS-8.2.2004-x86_64-minimal.iso
[ERROR] Couldn't create the directory "\\?\F:\WSL\centos8\rootfs\.".
Reason: 文件名、目录名或卷标语法不正确。

**Comment by DDoSolitary** [comment]
You can not install from an ISO image.

**Comment by DDoSolitary** [comment]
You can find tar files needed by LxRunOffline here: https://cloud.centos.org/centos/. Files for x86_64 and with "layer" in there names are the ones that you need, for example: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Container-8.1.1911-20200113.3-layer.x86_64.tar.xz
