### ISSUE TITLE
Access is denied after moving existing installation.

### ISSUE THREAD

**Issue by alexsilva** [DDoSolitary/LxRunOffline#155]
I ran the command (no errors):
`LxRunOffline.exe move -n Ubuntu-20.04 F:\\`

But run after moving result in:
`LxRunOffline.exe run -n Ubuntu-20.04`
Access denied.

`wsl -d Ubuntu-20.04`
Access denied.

Via windows terminal:
```
Access denied.

[process terminated with code 4294967295]
```
All administrators have maximum permission

![image](https://user-images.githubusercontent.com/2024086/99985979-64389300-2d8d-11eb-8e92-79582bed87d6.png)

**Comment by DDoSolitary** [comment]
Don't move to root directories. Create a subdirectory and move into it instead.

**Comment by Cugtyt** [comment]
A temp workaround is to open C:\Windows\System32\wsl.exe as administor

**Comment by Cugtyt** [comment]
> 
> 
> Don't move to root directories. Create a subdirectory and move into it instead.

I moved to D:\\wsl\, same problem

**Comment by Cugtyt** [comment]
I just found the solution, <https://answers.microsoft.com/en-us/windows/forum/all/kb4565503-installed-then-wsl-2-failed-to-start/25794c4f-0b20-465e-bbdb-a8af3d9e0e88>:

brief steps:

find your `ext4.vhdx` (should be under your destination folder),  and add "full control" permission to the user
![图片](https://user-images.githubusercontent.com/16632454/102608018-3401cb80-4164-11eb-8c36-2ee9e3e66a2a.png)
