### ISSUE TITLE
su missing from help dialog

### ISSUE THREAD

**Issue by wintersnare** [DDoSolitary/LxRunOffline#156]
su, set-uid is a functional command that isn't listed in the help dialog.
same goes for sf, set-flags

![2020-11-28 12_13_16-Windows PowerShell](https://user-images.githubusercontent.com/6328213/100525158-2fed1a00-3173-11eb-976a-7a8357f8b2ab.png)

**Comment by DDoSolitary** [comment]
What terminal emulator are you using? I'm unable to reproduce this locally, and it seems that in your screenshot the terminal incorrectly renders the output of the command.

**Comment by wintersnare** [comment]
Sorry for the late reply. This was a screenshot of Powershell running under Windows Terminal.
However, upon checking this again using Powershell and CMD both are now rendering it correctly. 

Not sure what was causing this or why it's working now (I haven't changed any of my settings.)
Either way, this can be closed.
