### ISSUE TITLE
'Script not on PATH' problem

### ISSUE THREAD

**Issue by Honour-Van** [DDoSolitary/LxRunOffline#158]
(My WSL distro is Ubuntu 20.04)
Before moving the wsl to D:, my pip went well with its dependencies to get downloading tasks done quietly.
but now: 
```ps
WARNING: The scripts convert-caffe2-to-onnx and convert-onnx-to-caffe2 are installed in '/home/fhn/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
![image](https://user-images.githubusercontent.com/58389073/102564995-89fc5200-4117-11eb-9441-7073fc14b028.png)

It doesn't seem quite too fatal, but I'd like to solve it. It would be my privilege if the problem can be useful to this project.

**Comment by DDoSolitary** [comment]
It doesn't seems to be the fault of LxRunOffline.
