### ISSUE TITLE
Reason: Indicates that the directory trying to be deleted is not empty.

### ISSUE THREAD

**Issue by Cr1ft** [DDoSolitary/LxRunOffline#159]
An error was reported when I tried to move the WSL.

[ERROR] Couldn't set the case sensitive attribute of the directory "\\?\C:\Users\test\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\".
Reason: Indicates that the directory trying to be deleted is not empty.

**Comment by Cr1ft** [comment]
I don't know why Windows doesn't set the LocalState directory to case-sensitive by default.I can move the directory successfully after manually setting it to case-sensitive using Futil.exe.

**Comment by DDoSolitary** [comment]
Sorry for the delay. It seems to be the same issue as #150. The fix is committed but not yet released.

**Comment by winkee01** [comment]
I am today encountering the same issue, has the fix being committed?

**Comment by nour-s** [comment]
If you are still facing this issue today, just move the `ext4.vhdx` out of the LocalState folder, run 
```
fsutil file setCaseSensitiveInfo C:\Users\{User}\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\LocalState\ enable
```

and then move the `ext4.vhdx` back. Now you can use the LxRunOffline tool as before.

**Comment by pangdundun** [comment]
> If you are still facing this issue today, just move the `ext4.vhdx` out of the LocalState folder, run
> 
> ```
> fsutil file setCaseSensitiveInfo C:\Users\{User}\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc\LocalState\ enable
> ```
> 
> and then move the `ext4.vhdx` back. Now you can use the LxRunOffline tool as before.

Thanks!
