### ISSUE TITLE
move迁移问题

### ISSUE THREAD

**Issue by vzy2d** [DDoSolitary/LxRunOffline#160]

**Comment by vzy2d** [comment]
使用move移动名为 Ubuntu-18.04 的 WSL2 系统时，指定了一定与机器名字一样的文件夹作为目标文件夹，移动行为一直没有停止，强制关闭后发现一直在目标文件夹下创建新的同名文件夹循环复制相同的东西(如图所示)
![image](https://user-images.githubusercontent.com/25742504/106351233-fc1aa600-6315-11eb-95b7-5e8bd34332c1.png)

**Comment by vzy2d** [comment]
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎3/‎11
操作系统版本	19042.746
体验	Windows Feature Experience Pack 120.2212.551.0

**Comment by vzy2d** [comment]
执行的命令为
`.\LxRunOffline.exe m -n Ubuntu-18.04 -d D:\WSL\Ubuntu-18.04\`

**Comment by DDoSolitary** [comment]
它原来安装的位置在哪里？

**Comment by vzy2d** [comment]
> 它原来安装的位置在哪里？

是之前直接用应用商店安装的，应该在默认位置

**Comment by DDoSolitary** [comment]
本地测试了一下，无法复现。你说的这个现象和之前有人报告过的移动到原安装目录的子文件夹时出现的问题很像，既然原来是默认位置的话也就不可能是这种情况了。暂时想不出来是什么导致的。。

**Comment by vzy2d** [comment]
> 本地测试了一下，无法复现。你说的这个现象和之前有人报告过的移动到原安装目录的子文件夹时出现的问题很像，既然原来是默认位置的话也就不可能是这种情况了。暂时想不出来是什么导致的。。

嗯        不会导致数据丢失就问题不大
