### ISSUE TITLE
Import VHDX

### ISSUE THREAD

**Issue by mmiszczyk** [DDoSolitary/LxRunOffline#161]
I had a distro installed on an external drive (install through Windows Store, moved with LxRunOffline), and when the drive was disconnected, Windows got confused with it: when I tried to run it, it acted as if it was a first run, and when I listed location with LxRunOffline, it's in AppData (to be clear: I didn't try running it without a drive being disconnected, I just had it disconnected for a while and then reconnected it to run WSL). I still have a VHDX on my external drive, so it would be nice if I could import it with LxRunOffline, but it seems only .tar.gz files can be used for installation.

**Comment by DDoSolitary** [comment]
You can `unregister` and then `register` the distro to fix the incorrect path. I'm not sure about why the installation path is incorrect though. Probably the move operation failed so the path was not updated.

**Comment by mmiszczyk** [comment]
Makes sense, thanks. The incorrect path was probably caused by the fact that the image got corrupted, possibly by libguestfs when I mounted it on Linux. Windows saw the corrupted image and decided to do a clean reinstall silently, for some reason.

**Comment by abalter** [comment]
If I simply have a `ext4.vhdx` file, say copied from another machine, can I `register` it and then import it?

**Comment by DDoSolitary** [comment]
@abalter Yes, you can create a new directory, put the vhdx file into it, and import the directory.

**Comment by abalter** [comment]
So simply `folder/ext4.vhdx`?
