### ISSUE TITLE
wsl crashes after I used lxrunoffline to move it from c drive

### ISSUE THREAD

**Issue by dhirajnitk** [DDoSolitary/LxRunOffline#162]
I am unable to launch wsl after I used lxrunoffline to move the filesystem from c to another drive.

`wsl --list --verbose`

> Ubuntu-20.04    Stopped         1

I can see the ubuntu distribution in the drive. wsl is able to recognise the ubuntu so its a terminal launch issue
Is there any mean to login the output of wsl?

**Comment by DDoSolitary** [comment]
I don't have any idea on this. Could you please provide [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually)?
