### ISSUE TITLE
LXATTRB error when moving distribution to a new directory

### ISSUE THREAD

**Issue by isedwards** [DDoSolitary/LxRunOffline#163]
Using `LxRunOffline-v3.5.0-msvc` to move a WSL distribition to an external drive that uses `exFAT` I get the following error:

`LxRunOffline.exe m -n Debian -d debian`

```
[ERROR] Couldn't set the extended attribute "LXATTRB" of the file or directory "\\?\D:\WSL\debian\rootfs\".
Reason: The specified request is not a valid operation for the target device.
```

Is this a known issue?

**Comment by DDoSolitary** [comment]
Unfortunately, exFAT is not supported by WSL, which depends on NTFS extended attributes.

**Comment by isedwards** [comment]
I see. Thank you for the quick reply
