### ISSUE TITLE
dir is not empty

### ISSUE THREAD

**Issue by qian0817** [DDoSolitary/LxRunOffline#164]
I use the latest release to move and it failed. It looks very similar to #150 but the directory is different.
![image](https://user-images.githubusercontent.com/45898769/115103678-61317f80-9f86-11eb-8461-fdd75b9d2afd.png)

**Comment by DDoSolitary** [comment]
It seems to be a different issue. Unfortunately, it's pretty hard to figure out why the deletion process failed, but you can use the following procedure to manually complete the interrupted move operation:

1. `LxRunOffline unregister -n Ubuntu`
2. `LxRunOffline register -n Ubuntu -d D:\wsl\ubuntu`
3. Check if the distro work properly.
4. Delete everything under `%LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState`

**Comment by qian0817** [comment]
> It seems to be a different issue. Unfortunately, it's pretty hard to figure out why the deletion process failed, but you can use the following procedure to manually complete the interrupted move operation:
> 
> 1. `LxRunOffline unregister -n Ubuntu`
> 2. `LxRunOffline register -n Ubuntu -d D:\wsl\ubuntu`
> 3. Check if the distro works properly.
> 4. Delete everything under `%LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState`
 
I have reinstalled WSL, and I can't reproduce this error.
