### ISSUE TITLE
Network is unusable in wsl2 that created by lxrunoffline

### ISSUE THREAD

**Issue by oska874** [DDoSolitary/LxRunOffline#165]
what i did are:
1. create a wsl1 ubuntu 18 with lxrunoffline
2. convert wsl1 to wsl2
3. run apt update, but failed, while the same source is ok in another wsl2 ubuntu in the same pc.
4. convert wsl2 to wsl1, the network is ok.

**Comment by DDoSolitary** [comment]
I doesn't seem to be caused by LxRunOffline. I would suggest ask at https://github.com/microsoft/wsl
