### ISSUE TITLE
lxrunoffline cannot export or duplicate wsl not created by lxrunoffline

### ISSUE THREAD

**Issue by oska874** [DDoSolitary/LxRunOffline#166]
when i try to export or duplicate a wsl image that installed by windows not by lxrunoffline, it always fail shows :

>`LxRunOffline.exe e -n ub18 -f d:\wsl\ub18.tar.gz`  or  >`LxRunOffline.exe d ub18 -d d:\wsl\ub18`

```
[ERROR] Couldn't set the case sensitive attribute of the directory "\\?\D:\wsl\ub18-1-1\".
Reason: {Access Denied}
A process has requested access to an object, but has not been granted those access rights.
```

**Comment by DDoSolitary** [comment]
Does it work if you install a new distro (either from Store or using LxRunOffline) and try to export/duplicate it?

Also, please provide the output of `icacls D:\wsl\ub18-1-1` and `dir /q D:\wsl\ub18-1-1`
