### ISSUE TITLE
still paths starting with "\\?\" problom

### ISSUE THREAD

**Issue by n00B-ToT** [DDoSolitary/LxRunOffline#167]
C:\Users\xxxx\Desktop\LxRunOffline-v3.5.0-10-gc8200f2-msvc>LxRunOffline.exe i -f F:\wsl\kali-linux-08-06-2019.appx -v 2 -d F:\wsl\kali -n kali_new
[ERROR] Couldn't create the file "\\?\F:\wsl\kali\rootfs\AppxMetadata\AppxBundleManifest.xml".
Reason: 系统找不到指定的路径。

**Comment by DDoSolitary** [comment]
It is wrong to install an appx file like this. #86
