### ISSUE TITLE
openSUSE Leap redirection link is broken

### ISSUE THREAD

**Issue by LosEagle** [DDoSolitary/LxRunOffline#169]
https://lxrunoffline.apphb.com/download/openSUSE/Leap-15.2 leads to 404

**Comment by DDoSolitary** [comment]
Unfortunately, the repo from which we take the rootfs images seems no longer maintained, so we need to find some other source.

**Comment by DDoSolitary** [comment]
Please check if this one works: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.2/images/openSUSE-Leap-15.1-OpenStack-rootfs.aarch64.tar.xz

**Comment by LosEagle** [comment]
I've installed it using ` LxRunOffline i -n openSUSE_Leap -d D:\WSL\openSUSE -f D:\Temp\wsl\openSUSE-Leap-15.1-OpenStack-rootfs.aarch64-0.0.4-Build1.206.tar.xz -s` and it seems to have installed without error, but starting it via ` LxRunOffline run -w -n "openSUSE_Leap"` doesn't do anything. Doesn't even output anything to the terminal.

**Comment by DDoSolitary** [comment]
You need a x86_64 version, not aarch64

**Comment by DDoSolitary** [comment]
https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.2/images/openSUSE-Leap-15.1-OpenStack-rootfs.x86_64-0.0.4-Build1.206.tar.xz

Could you please try this one

**Comment by LosEagle** [comment]
Oh, nvm I should've noticed that. Yup, seems to work fine 🙂👍

**Comment by DDoSolitary** [comment]
> Although, the install didn't seem to offer creating new user and dumped me straight into root. Is that supposed to happen?

It's expected behavior.

**Comment by DDoSolitary** [comment]
Unfortunately the cloud images aren't named consistently and seems hard to locate automatically with code. I'll leave the redirection link unchanged but mention the cloud images in wiki
