### ISSUE TITLE
Access Is Dennied

### ISSUE THREAD

**Issue by wangmiaowei** [DDoSolitary/LxRunOffline#170]
I meet this question:
C:\Users\Administrator>LxRunOffline move -n Ubuntu -d F:\Ubuntu
[WARNING] Ignoring an unsupported file "\\?\C:\Users\Administrator\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\dev\console" of type 0020000.
[ERROR] Couldn't set reparse information of the file "\\?\F:\Ubuntu\rootfs\dev\fd".
Reason: Access is denied.

**Comment by DDoSolitary** [comment]
What version of Windows and LxRunOffline are you using?

**Comment by yellowmarlboro** [comment]
@wangmiaowei 请问您是如何解决的？

**Comment by yellowmarlboro** [comment]
解决了，在这里
https://github.com/DDoSolitary/LxRunOffline/issues/155
