### ISSUE TITLE
Couldn't get the value "DistributionName" on Windows 11

### ISSUE THREAD

**Issue by WordlessEcho** [DDoSolitary/LxRunOffline#171]
```powershell
PS C:\Users\echo\Desktop> lxrunoffline.exe install `
>> -n AOSC `
>> -d C:\files\AOSC\ `
>> -f C:\Users\echo\Downloads\aosc-os_base+nvidia_20210602_amd64.tar.xz `
>> -s
[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache".
Reason: 系统找不到指定的文件。
// Reason: System could not found specific file.
```

**Comment by WordlessEcho** [comment]
![image](https://user-images.githubusercontent.com/12007025/123786425-3cee0980-d90c-11eb-9117-9e6e597583b4.png)

**Comment by Artoria2e5** [comment]
For exploring the bug further, run the command that lists distros. I think it's gonna fail too!

For an attempted workaround, try deleting the `AppxInstallerCache` entry. I think (more like *feel*) the code is expecting everything under the `Lxss` path to have a GUID.

For an attempted fix, I think the `list_distro_id` function is going to need to filter enum results to only include ones that are GUIDs.

**Comment by WordlessEcho** [comment]
> For exploring the bug further, run the command that lists distros. I think it's gonna fail too!
> 
> For an attempted workaround, try deleting the `AppxInstallerCache` entry. I think (more like _feel_) the code is expecting everything under the `Lxss` path to have a GUID and the... corresponding structure.
> 
> For an attempted fix in the code, I think the `list_distro_id` function is going to need to filter `RegEnumKeyEx` results to only include ones that are GUIDs.

This solve my problem. Thanks!

**Comment by armanexplorer** [comment]
> For exploring the bug further, run the command that lists distros. I think it's gonna fail too!
> 
> For an attempted workaround, try deleting the `AppxInstallerCache` entry. I think (more like _feel_) the code is expecting everything under the `Lxss` path to have a GUID and the... corresponding structure.
> 
> For an attempted fix in the code, I think the `list_distro_id` function is going to need to filter `RegEnumKeyEx` results to only include ones that are GUIDs.

I also had to delete `TryStoreWSL` to go forward.

**Comment by gsaf64** [comment]
> For exploring the bug further, run the command that lists distros. I think it's gonna fail too!
> 
> For an attempted workaround, try deleting the `AppxInstallerCache` entry. I think (more like _feel_) the code is expecting everything under the `Lxss` path to have a GUID and the... corresponding structure.
> 
> For an attempted fix in the code, I think the `list_distro_id` function is going to need to filter `RegEnumKeyEx` results to only include ones that are GUIDs.

I had to delete 'TryStoreWSL' in addition to 'AppxInstallerCache', leaving only GUID entries under 'Lxss'. After that, lxrunoffline works.
