### ISSUE TITLE
我移动docker后wsl找不到docker了

### ISSUE THREAD

**Issue by edcjian** [DDoSolitary/LxRunOffline#173]

**Comment by DDoSolitary** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E7%B2%BE%E7%A1%AE%E5%9C%B0%E6%8F%8F%E8%BF%B0%E9%97%AE%E9%A2%98%E5%B9%B6%E8%A8%80%E4%B9%8B%E6%9C%89%E7%89%A9
