### ISSUE TITLE
Doesn’t seem to support ISO? I want to install manjaro, or where is the tar.gz package needed for manjaro installation?

### ISSUE THREAD

**Issue by kamjin3086** [DDoSolitary/LxRunOffline#175]
I downloaded an x64 iso package from manjaro.org, intending to install it on wsl2, but I tried to install the ISO file, the command is as follows:

.\LxRunOffline.exe install -n Manjaro -f'E:/manjaro-kde-21.0.7-210614-linux510.iso' -d'D:\WslDisk\Manjaro' -r root.x86_64

LxRunOffline does not support ISO installation, can there be a new version of tar.gz from Manjaro? I need a corresponding tar.gz download address, thank you very much

Looking forward to your reply

**Comment by DDoSolitary** [comment]
Yes ISO is not and will not be supported. It seems that Manjaro doesn't release rootfs tarballs so it's impossible to install it directly.
