### ISSUE TITLE
export WSL2

### ISSUE THREAD

**Issue by BA7JCM** [DDoSolitary/LxRunOffline#178]
when I want to use it to export WSL2 ,it say "The action/argument "export" doesn't support WSL2."

**Comment by BA7JCM** [comment]
Windows version:10.0.19042.1052
lxrunoffline version:3.5.0-msvc

**Comment by DDoSolitary** [comment]
As the error messages says, the export feature doesn't support WSL2 currently. It is pretty hard to implement this as there's no easy way to read the ext4 partition in ext4.vhdx. I have some ideas in my mind but haven't found time to work on this.

**Comment by BA7JCM** [comment]
> As the error messages says, the export feature doesn't support WSL2 currently. It is pretty hard to implement this as there's no easy way to read the ext4 partition in ext4.vhdx. I have some ideas in my mind but haven't found time to work on this.

还是去那个中文issue里说吧
