### ISSUE TITLE
can't start wsl after disk move 

### ISSUE THREAD

**Issue by iPwnXX** [DDoSolitary/LxRunOffline#179]
I tried to move wsl to D disk using this tool's command. After finish moving, the new wsl can'be open from terminal:   

![image](https://user-images.githubusercontent.com/40853420/129655352-7074e489-b2fe-47a4-93b9-f61c77c0df7b.png)

and can't be open from disk either:   

![image](https://user-images.githubusercontent.com/40853420/129655247-fe5746ab-08e4-4908-a029-ca75d316392f.png)   
(saying the disk is not initialized.)

Is there any way to fix this problem?

**Comment by DDoSolitary** [comment]
The error shown when opening the vhdx file is irrelevant. It contains an ext4 partition, which Windows doesn't recognize.

Seems to be a Windows Terminal issue microsoft/WSL#6995

**Comment by iPwnXX** [comment]
After following instructions from https://github.com/microsoft/WSL/issues/6995#issuecomment-849248855, new problems appears, saying 'Access Denied' (拒绝访问).  Administrator mode doesn't help either.
Solved this problem thanks to https://github.com/DDoSolitary/LxRunOffline/issues/155#issuecomment-748026395
