### ISSUE TITLE
采用LxRunOffline工具导出wsl2后，出错

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [DDoSolitary/LxRunOffline#187]
![image](https://user-images.githubusercontent.com/28779327/144980725-21401b07-6c8a-40ae-99ca-91333c2cf5a8.png)
![image](https://user-images.githubusercontent.com/28779327/144980766-78e2d86b-829e-4e29-a913-34f8833e5c1f.png)
![image](https://user-images.githubusercontent.com/28779327/144980789-34534727-c07b-47b2-85cb-8c1dbcea7634.png)
![image](https://user-images.githubusercontent.com/28779327/144980906-456e937c-9ffe-4859-a262-ce7c153f5546.png)

**Comment by DDoSolitary** [comment]
到底是移动还是导出

**Comment by DDoSolitary** [comment]
重启系统后是否仍然报错

**Comment by wangwenqiangGitHub** [comment]
> 到底是移动还是导出

我就是用这个软件安装的archlinux, 直接指定到D盘，开始能用，重启后报错

**Comment by wangwenqiangGitHub** [comment]
LxRunOffline.exe sm -n ArchLinux这个命令还能查到位置，但是wsl不行找到

**Comment by DDoSolitary** [comment]
麻烦完整描述一下从安装开始你做的所有操作。。
直接安装出来不可能是 WSL2

**Comment by wangwenqiangGitHub** [comment]
> 



> 麻烦完整描述一下从安装开始你做的所有操作。。 直接安装出来不可能是 WSL2

wsl --set-version ArchLinux 2

**Comment by wangwenqiangGitHub** [comment]
![image](https://user-images.githubusercontent.com/28779327/144999803-a9a3a5c6-38b4-4ff2-8a72-943774b40705.png)

**Comment by wangwenqiangGitHub** [comment]
![image](https://user-images.githubusercontent.com/28779327/185576790-b946d9ca-27f7-4440-a07b-c450df5073ac.png)
![image](https://user-images.githubusercontent.com/28779327/185576852-e12e4d9c-2fcb-4faf-8baf-15225907e0c5.png)
I move arch in to D:\wsl\ ; but when i open wsl2 erro

**Comment by wangwenqiangGitHub** [comment]
I find the cause ; have to modify **C:\Users\戴尔\.wslconfig** file;
```
[wsl2]
#kernel=C:\\temp\\myCustomKernel
memory=4GB # Limits VM memory in WSL 2 to 4 GB
processors=2 # Makes the WSL 2 VM use two virtual processors
```
