### ISSUE TITLE
Implement NTFS extended attribute manipulation

### ISSUE THREAD

**Issue by DDoSolitary** [DDoSolitary/LxRunOffline#19]
This will solve the installation location problem of `WslRegisterDistribution` and provide a better `LxRunOffline move` implementation.

**Comment by DDoSolitary** [comment]
Something like this: https://github.com/RoliSoft/WSL-Distribution-Switcher/blob/master/ntfsea/ntfsea.c

**Comment by Biswa96** [comment]
I successfully implement that DLL to read/write Lxss attributes. But if the distribution has multiple files then does one have to apply those attributes recursively with all files? That's not seem to efficient.
Also I find another repo to read lxss attributes [dmex/lxssattr](https://github.com/dmex/lxssattr).

**Comment by DDoSolitary** [comment]
Yes, it has to be done recursively. However, I don't think it is inefficient, before applying any attributes, the file should be copied or extracted from an archive, which should also be done recursively. So the operations won't be much slower.

**Comment by DDoSolitary** [comment]
C++ side implementation has been done: 9d56eea22c075c115b494527596fe16fa621439e, ad5b4a684bf1ec27d28ed1995c1eec5d9d0b3707.

I'll implement copying/extracting using C#.

**Comment by DDoSolitary** [comment]
Extraction can be done with [DiscUtils](https://github.com/DiscUtils/DiscUtils), which supports Tar and SquashFS.

**Comment by Biswa96** [comment]
Microsoft has released the functions documentation: [ZwQueryEaFile()](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-zwqueryeafile), [ZwSetEaFile()](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-zwseteafile) etc. But one need Visual Studio with WDK.

**Comment by DDoSolitary** [comment]
> When I open your new DLL project in Visual Studio it shows many error, may be the project file has some errors.

Did you install Win SDK 10.0.14393? I can open it with a fresh VS installation.

**Comment by DDoSolitary** [comment]
> But one need Visual Studio with WDK.

WDK would get this simple project too complex, I think...

**Comment by Biswa96** [comment]
Oh.. I missed to edit the SDK version in project file. I've latest version of SDK. I'll try with WDK and inform.

**Comment by Biswa96** [comment]
Can I add that CPP file as a header file .h to be included in another cpp file to make one executable file?

**Comment by DDoSolitary** [comment]
Technically it's possible, and legally you can as you don't violet the MIT license.

**Comment by Biswa96** [comment]
If I compile that DLL, I've not to add LoadLibrary function to pinvoke ntdll. But I've to add that if I add those functions as CPP file.

**Comment by DDoSolitary** [comment]
Are you compiling using `cl.exe` or a VS project?

**Comment by Biswa96** [comment]
Yes, you may see my repo's test branch. I've also tried with adding ntdll.lib.

**Comment by DDoSolitary** [comment]
![image](https://user-images.githubusercontent.com/25856103/35478587-11358656-041c-11e8-9de4-8a3666e4cfdd.png)

You need to set the AdditionalDependencies to include ntdll.lib to link against ntdll.dll

**Comment by DDoSolitary** [comment]
https://github.com/DDoSolitary/LxRunOffline/blob/master/LxssEa/LxssEa.vcxproj#L58

https://github.com/DDoSolitary/LxRunOffline/blob/master/LxssEa/LxssEa.vcxproj#L76

**Comment by Biswa96** [comment]
I know that. But I'm talking about those functions like NtQueryEaFile() and NtSetEaFile(). Those two have to pinvoke from ntdll.dll.

**Comment by DDoSolitary** [comment]
No, you don't need to. Adding their definition in the code and linking using ntdll.lib is enough.

Also, the term P/Invoke means calling native/unmanaged code from managed code, not calling undocumented Windows functions, so it is inappropriate to use it here.

**Comment by Biswa96** [comment]
I've to add `extern "C"` to add those functions. By the way, I tried to run the program recursively but it seems high cpu usage during that process.

**Comment by DDoSolitary** [comment]
> I've to add `extern "C"` to add those functions.

Well, why did you remove it at first...

> By the way, I tried to run the program recursively but it seems high cpu usage during that process.

It is expected. Recursively traversing a directory does require some CPU power.

>  To decompress .tar.gz, I'm thinking about libarchive !?

I prefer to use C# libraries to avoid too much P/Invoke code. My current plan is to use DiscUtils for SquashFS and SharpZipLib+XZ.NET for .tar.gz and .tar.xz.

**Comment by DDoSolitary** [comment]
Well, I have to drop squashfs support, DiscUtils doesn't provide support LZMA compressed squashfs files.

**Comment by DDoSolitary** [comment]
Some todos:

- [ ] Support specifying a root directory in the tar archive.

- [ ] Add a command that duplicates an existing installation.

- [ ] Installation/moving doesn't work when part of the existing path has different cases with the specified path. e.g. `LxRunOffline install -n foo -f foo.tar.gz -d C:\Foo1\foo2` fails if `C:\Foo1` exists but actually is `C:\foo1`.

**Comment by Biswa96** [comment]
Where did you find the LxssEaData class? I read that heap allocation is slower. So why do you allocate arrays in heap not in stack?

**Comment by DDoSolitary** [comment]
> Where did you find the LxssEaData class?

I got its structure by changing the attributes of files in WSL and analyzing output from NtQueryEaFile.

> So why do you allocate arrays in heap not in stack?

Because I don't know how to dynamically allocate memory in the stack.

**Comment by Biswa96** [comment]
What is the magic behind this line?
`memcpy(eaInfo->EaName + LxssEaNameLength + 1, data, dataLength);`

**Comment by DDoSolitary** [comment]
I decided to use the maximum ea data size allowd (65535 bytes) to allocate memory and use `static` allocation which only allocates memory ones on each application run. I'll edit the code when I got some time. (after the final exams in my school 😄 )

---

> What is the magic behind this line?

According to the MS's documentation of [FILE_FULL_EA_INFORMATION](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ns-wdm-_file_full_ea_information):

> The value(s) associated with each entry follows the EaName array. That is, an EA's values are located at EaName + (EaNameLength + 1).
