### ISSUE TITLE
 Couldn't create the file "\\?\D:\wsl\rootfs\usr\lib\systemd\system\system\systemd\x2dcryptsetup.slice".   Reason: 系统找不到指定的路径。

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [DDoSolitary/LxRunOffline#193]
LxRunOffline版本: LxRunOffline-v3.5.0-33-gbdc6d7d-mingw
WSL : ubuntu20.04
有人遇到这个问题么。是因为我把这个文件拷贝到生成的system\system\systemd\x2dcryptsetup.slice还是不行，因为\字符引起的

**Comment by wangwenqiangGitHub** [comment]
https://ddosolitary-builds.sourceforge.io/LxRunOffline/；
换了这个分支的可以

**Comment by kakolukia** [comment]
> [https://ddosolitary-builds.sourceforge.io/LxRunOffline/；](https://ddosolitary-builds.sourceforge.io/LxRunOffline/%EF%BC%9B) 换了这个分支的可以

你好，你还有这个文件么？我在网上找的所有这版的下载链接都失效了
