### ISSUE TITLE
Suspicious link

### ISSUE THREAD

**Issue by Sgeo** [DDoSolitary/LxRunOffline#197]
https://github.com/DDoSolitary/LxRunOffline/wiki/Home/_compare/806ddfdc6cec4ed7de7251e9f9752250a05a6a13...dd64a8eb8d0f248a0489a3f37861aeff513541a0

earlste changed the link to a suspicious looking IP tracking link.

**Comment by DDoSolitary** [comment]
Thanks. It seems that you've reverted the commit and the spammer's account has already been banned.
