### ISSUE TITLE
[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache".

### ISSUE THREAD

**Issue by jieran233** [DDoSolitary/LxRunOffline#198]
When I run LxRunOffline, it shows a error message abour registry key like this:
``` 
[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache".
Reason: 系统找不到指定的文件。
```
P.S. 
 | 系统找不到指定的文件。 | `machine translation` The system could not find the specified file. |
|  ----  | ----  |

**Comment by jieran233** [comment]
I'm using `archlinux-2022.07.01-x86_64.iso` that download via tuna mirror, and checksum passed.
And my Windows Version is `10.0.22621`

**Comment by SIKtt** [comment]
I met the same question like this issue #195. You can delete `AppxInstallerCache` in `Software\\Microsoft\\Windows\\CurrentVersion\\Lxss\\`.

**Comment by SIKtt** [comment]
Another choice is creating `DistributionName REG_SZ Alpine (Alpine is an arbitrary)`  microsoft/WSL#3720. 
Maybe it throws `err_get_key_value` when empty cache entry like`{AppxInstallerCache}` or `{TryStoreWSL}` exist in ``Software\\Microsoft\\Windows\\CurrentVersion\\Lxss``. @DDoSolitary

**Comment by jieran233** [comment]
Thanks, I'll try your solution when I need.
