### ISSUE TITLE
Inconsistency in Fedora wiki page

### ISSUE THREAD

**Issue by jimorc** [DDoSolitary/LxRunOffline#23]
That page states that there are generally three ways to get the RootFS tarball, but then only two ways are mentioned. That is, unless the mirror in kernel.org is the third way. In that case, the text is confusing.

**Comment by DDoSolitary** [comment]
The wiki page was created by @Biswa96 and I guess he counted mirror.kernel.org as the third way.

**Comment by DDoSolitary** [comment]
I just updated the wiki pages and this page has been removed.

**Comment by Biswa96** [comment]
Though you deleted all wiki pages, I've seen that you are now working with downloading distro tarballs :+1: 
Do you want to extend that distro list? I've many more in my repo ( see .md file).

**Comment by Biswa96** [comment]
You may build Linux tarball in appveyor and deploy those in your repo so that user can download the tar.gz file directly from release.

**Comment by DDoSolitary** [comment]
@Biswa96 Actually I've considered the Win APIs were used for installation. But it doesn't make sense now because most if not all of the tar files provided by various distros have been supported.
