### ISSUE TITLE
How to run the installed distribution?

### ISSUE THREAD

**Issue by TomasHubelbauer** [DDoSolitary/LxRunOffline#24]
Hello, sorry to be a dumbo, but how do I run the installed distribution? With the ones installed through `wslconfig`, they have names corresponding to the distros, so I can just type the name into the terminal:

- `ubuntu`
- `opensuse-42`

I installed another Ubuntu distro using

```
lxrunoffline install -n Ubuntu1 -f ./ubuntu-xenial-core-cloudimg-amd64-root.tar.gz -d C:/Users/Tom/Desktop/wsl/demo
```

and I figured I could just do `ubuntu1`, but that doesn't seem to be the case?

I can use `wslconfig /s Ubuntu1` to make it a default and run it using `wsl` or `bash`, but that doesn't seem ideal. I would ultimately like to have taskbar shortcuts. I read [Getting Crazy with Windows Subsystem for Linux](https://brianketelsen.com/getting-crazy-with-windows-subsystem-for-linux/) where I found this tool, but the author uses WSLtty, but I would like to use the default Windows terminal that regular WSL uses.

**Comment by TomasHubelbauer** [comment]
I have tried researching how to make LNK files for WSL instances and I think there may be a way to adapt the Ubuntu LNK file created by Windows Store to point to a different instance, but I have not been able to figure out why as I'm not familiar enough with the file format. If you know how to create a LNK that would be also fine, my assumption that the instances created using this tool would be available as binaries in `%PATH%` may have been unfounded.

**Comment by DDoSolitary** [comment]
Use `LxRunOffline run -n Ubuntu1` or `LxRunOffline -n Ubuntu1 -c "some command to run"`

You can also lookup the corresponding GUID of a distro in `HKCU\Software\Microsoft\Windows\CurrentVersion\lxss`and use `wsl {GUID}`.
