### ISSUE TITLE
The redirect app seems to be offline

### ISSUE THREAD

**Issue by TomasHubelbauer** [DDoSolitary/LxRunOffline#25]
Hey, your redirect app for the FS images seems to be down:

https://lxrunoffline.apphb.com/ubuntu/xenial

Gives a 404. I downloaded the image directly from https://partner-images.canonical.com/core/xenial/current/ in the meantime.

**Comment by DDoSolitary** [comment]
You used a wrong URL, the correct one is https://lxrunoffline.apphb.com/download/ubuntu/xenial

**Comment by DDoSolitary** [comment]
OMG, I used the wrong URL in the Wiki...
