### ISSUE TITLE
Unable to load DLL 'LxssFileSystem.dll'

### ISSUE THREAD

**Issue by gravcat** [DDoSolitary/LxRunOffline#26]
As a new user, I've tried to install via chocolatey and via the GitHub release distribution. Both produce the following error on a windows 10 VM I'm trying this with:

```
.\LxRunOffline.exe install -n UbuntuFromMS -f "C:\Users\myuser\Downloads\16.04.2-server-clo
udimg-amd64-root.tar.gz" -d c:\wsl

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'LxssFileSystem.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LxRunOffline.FileSystem.GetFileHandle(String ntPath, Boolean directory, Boolean create, Boolean write)
   at LxRunOffline.FileSystem.ExtractTar(Stream stream, String tarRootPath, String targetPath)
   at LxRunOffline.Wsl.InstallDistro(String distroName, String tarPath, String tarRootPath, String targetPath)
   at LxRunOffline.Program.<>c.<Main>b__0_2(InstallOptions opts)
   at LxRunOffline.Program.Main(String[] args)
```
Attempted:
* I've confirmed that the dll is in the directory
* the directory is on the path
* executing from within the tools/lxrunoffline directory
* specifically writing the executable like .\LxRunOffline.exe rather than simply "LxRunOffline" and letting it discover it

Didn't find this problem in the issue tracker and am curious what makes me special for such a simple seeming error.

**Comment by DDoSolitary** [comment]
Is your Windows 32bit or 64bit?

**Comment by DDoSolitary** [comment]
And please try the [dev release](https://ci.appveyor.com/project/DDoSolitary/lxrunoffline/build/artifacts) which includes more compatibility checks.

**Comment by DDoSolitary** [comment]
Closing as no response.

**Comment by gravcat** [comment]
64 bit. Sorry for the no-response! I didn't see the emails while traveling.

**Comment by DDoSolitary** [comment]
That's OK. Then could you please try the latest release (v2.2.2)? Thanks.

**Comment by DDoSolitary** [comment]
This error often occurs when a 32-bit(WOW64) process tries to open 64-bit DLLs. I guess LxRunOffline was executed as a 32-bit process for some reason. The latest release checks for such problems.

**Comment by derchirurg** [comment]
Same issue for me with v2.2.2 release. Windows 10 Pro Release 1709

**Comment by DDoSolitary** [comment]
@gravcat @derchirurg I've figured it out. Please install [VC++ runtime 2017](https://go.microsoft.com/fwlink/?LinkId=746572).

**Comment by DDoSolitary** [comment]
5d27c9ab380c07790f1826d922ca38217e6f7337 aa08ce8531dfcf80fd6bf336460cea638b8a7c65

**Comment by cblp** [comment]
I have the same issue. Please mention VC++ Runtime installation in the instruction.

**Comment by DDoSolitary** [comment]
@cblp please try the latest version, it should no longer depend on VC++ runtime.

**Comment by cblp** [comment]
@DDoSolitary I use v2.2.2, the latest release as for today.
