### ISSUE TITLE
How to backup the installed distributions  and install  to another machine？

### ISSUE THREAD

**Issue by lihuixian001** [DDoSolitary/LxRunOffline#29]
I have installed a distribution called ubuntu1. I tried to compress it to ubuntu1.tar.gz, and then unzip and 
LxRunOffline register it , but run failed:
```
[LOG] Calling Win32 API WslLaunchInteractive.
[LOG] Exit code is 1.
```

**Comment by DDoSolitary** [comment]
How did you create the .tar.gz file (the command you used)?

**Comment by lihuixian001** [comment]
in wsl:

```
cd /
tar vzcpf /tmp/ubuntu_`date +%Y%m%d_%H`.tar.gz --exclude=/proc --exclude=/dev --exclude=/mnt --exclude=/media --exclude=/lost+found  --exclude=/tmp --exclude=/sys  --exclude=/run / > /tmp/ubuntu_`date +%Y%m%d_%H`.log 2> /tmp/ubuntu_`date +%Y%m%d_%H`.error
```

**Comment by DDoSolitary** [comment]
And how did you unzip it? I just created a .tar.gz file using the command you provided and installed it with `LxRunOffline install`. It worked without problems.

**Comment by DDoSolitary** [comment]
You can not extract this way because files created via `/mnt/*` paths lacksk NTFS extended attributes required by WSL.

And the error occurred when installing is because LxRunOffline currently doesn't support the GNU extensions of tar format. I'll try to fix it ASAP.

**Comment by DDoSolitary** [comment]
@lihuixian001 BTW, before this bug is fixed, you can use the `LxRunOffline duplicate` command and a USB stick to copy your installation to other machines.

**Comment by DDoSolitary** [comment]
Fixed in v3.
#36
