### ISSUE TITLE
where is placed the files after installation?

### ISSUE THREAD

**Issue by AndroidDesigner** [DDoSolitary/LxRunOffline#3]
hi.
I have used your method to install bashonwindows offline.
but I dont know where are placed the installed files.
I did a search for "C:\Users\USERNAME\AppData\Local\lxss" , but there is not lxss folder there. and only one Ixss folder is inside "C:\Windows\System32" that does not included this folders : 
C:\Users\USERNAME\AppData\Local\Lxss\home\USERNAME
C:\Users\USERNAME\AppData\Local\Lxss\root

thanks

**Comment by DDoSolitary** [comment]
The installation process is not controlled by my code but `lxrun.exe'. You can open a issue in the official repo of BashOnWindows(https://github.com/Microsoft/BashOnWindows) to ask for help.
