### ISSUE TITLE
yum/dnf doesn't work with fedora installation

### ISSUE THREAD

**Issue by AjawadMahmoud** [DDoSolitary/LxRunOffline#32]
I tried both fedora 26, and 27 using the API method to get the didcated file to install a `wsl` instance of fedora, which was succeful for both the versions. However, I couldn't get `yum/dnf` to work as they both fail with `seg fault`.
Any suggestions?

**Comment by DDoSolitary** [comment]
I'm sorry, but it isn't a place for WSL Q&A here, and I'm not a Fedora user. I think you can open an issue at https://github.com/Microsoft/WSL/issues.
