### ISSUE TITLE
LxRunOffline.exe install fails missing resolv.conf?

### ISSUE THREAD

**Issue by Trophime** [DDoSolitary/LxRunOffline#34]
Hi,
trying to build a custom Lxc container from a debian based docker (trophime/salome-8.4.0)
following notes found in [this article](https://medium.com/@gauravnelson/how-to-run-fedora-with-windows-subsystem-for-linux-wsl-a148902e5087), I got this error:
```
PS C:\LxRunOffline> .\LxRunOffline.exe install -n Salome -f C:\Users\trophime\Documents\SalomeLxc\salome-8.4.0_docker.tar.gz -d C:\Users\trophime\Documents\MySalomeLxc\
[ERROR] Couldn't open the file or directory "C:\Users\trophime\Documents\MySalomeLxc\rootfs\etc\resolv.conf".
```

the docker.tar.gz file is just obtained by using `docker save ...`
How to fix this issue?
Is there any way to build a custom lxc container?

Thanks for you work and any hints would be really appreciated
Best

**Comment by DDoSolitary** [comment]
Could you please share the `.tar.gz` file produced by `docker save`? I don't have a Linux box with Docker available right now so it's hard to see what's actually happening without the file. Thanks.

**Comment by Biswa96** [comment]
Ok I shall try that in my machine. Can you share a link of that docker file? Or the docker repository?

**Comment by Trophime** [comment]
The docker is stored in dockerhub and it is public:
```
docker pull trophime/salome-8.4.0:nvidia
```

**Comment by Biswa96** [comment]
OMG! That's 2 GB. Takes long to install....

**Comment by Trophime** [comment]
Find attached a zip archive containing all data needed to generate the docker
[UB16.zip](https://github.com/DDoSolitary/LxRunOffline/files/1833387/UB16.zip)

You would just need to register to [salome](http://www.salome-platform.org) to get HTTP credential
to get salome bin archives

**Comment by Biswa96** [comment]
Sorry, Sir, I don't install that huge in my machine and I've not those registration and nvidia GPU.  I've seen that your docker image comes from Ubuntu Xenial. If you can successfully install Ubuntu Xenial then it may be possible to install salome. You can try to add this command in `DockerFile` and then make the tar.gz file.

```
echo nameserver 8.8.8.8 >> /etc/resolv.conf
```

**Comment by Trophime** [comment]
You can reproduce the problem with ubuntu:bionic which is less than 100MB

**Comment by Biswa96** [comment]
I don't know about the download of docker pull command but you can download a ready-made Ubuntu Bionic .tar.gz file from GitHub . See this link: https://github.com/tianon/docker-brew-ubuntu-core/tree/dist-amd64/bionic
Or you can easily convert SqaushFS to .tar.gz. See this link: http://cloud-images.ubuntu.com/bionic/current/

**Comment by DDoSolitary** [comment]
@Trophime Or you can use the links provided on the [Wiki pages](https://github.com/DDoSolitary/LxRunOffline/wiki/).
