### ISSUE TITLE
Roadmap for v3.

### ISSUE THREAD

**Issue by DDoSolitary** [DDoSolitary/LxRunOffline#36]
- v3 will only support the upcoming Win 10 v1803.
- Rewrite the whole project in C++.
- Use libarchive to read tar files, which would solve https://github.com/DDoSolitary/LxRunOffline/issues/29#issuecomment-368284043.
- Take a look at `FileStatLxInformation` and `FileCaseSensitiveInformation`.

**Comment by Biswa96** [comment]
Did you know the struct that `FileStatLxInformation` returns?

**Comment by DDoSolitary** [comment]
> Did you know the struct that FileStatLxInformation returns?

I haven't investigated it. So I said  "Take a look at"... :smile:

> And don't remove the C# source codes. I like it.

I will delete them, but you can always browse them in the git commit history.

**Comment by TomasHubelbauer** [comment]
Do you think that as a convenience feature, a command for creating an icon and attaching it to the taskbar could be added?

Also, would be nice to be able to specify the input image using friendly name as opposed to the app you offer that redirects you to the files, but I expect there is a reason for why that's not already the case, so that's just a nice-to-have for me.

**Comment by Biswa96** [comment]
One idea. Can you hook the LxssManager service process?

**Comment by Biswa96** [comment]
One idea. Can you hook the LxssManager service process? There is a string in LxssManager.dll which execute bdstar to extract .tar.gz. If somehow the string can be change then LxssManager may extract .tar, .tar.xz, .squashfs etc.

**Comment by DDoSolitary** [comment]
> Take a look at `FileStatLxInformation` and `FileCaseSensitiveInformation`.

Just tested both of them. `FileCaseSensitiveInformation` worked well, but I got some problems on `FileStatLxInformation`.

- The returned `FILE_STAT_LX_INFORMATION` has all of the WSL-related fields zero even if `NtQueryInformationFile` is called on a WSL's file, and I don't how to get it working.

- As the structure has some read-only fields like `FileId` and `NumberOfLinks` I don't think it can be used by `NtSetInformationFile` to set the extended attributes. (though not tried yet)

So I decided to stick to `NtQueryEaFile` and `NtSetEaFile`.

**Comment by Biswa96** [comment]
Extended attribute `LXATTRB` can be added with `NtCreateFile()`. I don't find that LxssManager use that struct in latest Windows build.

**Comment by DDoSolitary** [comment]
v3 is ready.

**Comment by DDoSolitary** [comment]
@TomasHubelbauer I've reopened #27 and will implement this feature later.

**Comment by Biswa96** [comment]
Oooo, you're mimicking the behaviour of LxssManager.dll 👌 One thing I've to say. Microsoft WSL programmers are moving towards DRVFS like extended attributes. That is, `LXATTRB` may be replaced by the `FILE_STAT_LX_INFORMATION`. `wslconfig.exe /upgrade` is responsible to do this conversation.

**Comment by DDoSolitary** [comment]
@Biswa96 Really helpful information, could you please give the source?

**Comment by DDoSolitary** [comment]
BTW, the duplicate command of v3.0.1 has some known issues. Please use it with care.

**Comment by Biswa96** [comment]
Ya i also want to mimic that upgrade procedure. But I need some idea about doing the attribute change recursively without memory leaking/high cpu usage.

**Comment by Biswa96** [comment]
A makefile with gcc or g++ will be great.

**Comment by DDoSolitary** [comment]
Actually I have got one locally, I'll update it.

**Comment by DDoSolitary** [comment]
@Biswa96 Pushed. I'll add build instructions to README later.
