### ISSUE TITLE
Cannot run the system directly from different drive

### ISSUE THREAD

**Issue by GhostFairy** [DDoSolitary/LxRunOffline#38]
Hello! I'm trying to move the WSL system to another drive(such as D:) and run directly from there.

I've installed Ubuntu from Microsoft Store, and used LxRunOffline to duplicate the system and set duplicated system to default, and tried to run it but I couldn't.

`> LxRunOffline.exe duplicate -n Ubuntu -N UbuntuD -d D:\WSL\Ubuntu`
`> LxRunOffline.exe default -n UbuntuD`
`> bash`
`Error: 0x80070057`

but when I've duplicated the system into somewhere in C:, I can run it.
`> LxRunOffline.exe duplicate -n Ubuntu -N UbuntuC -d C:\WSL\Ubuntu`
`> LxRunOffline.exe default -n UbuntuC`
`> bash`
`To run a command as administrator (user "root"), use "sudo <command>".`
`See "man sudo_root" for details.`
`$`

How can I run my system from different drive? Any solution for this prolem?

EDIT:
I've also read Microsoft/WSL#7 threads, but legacy mode has already disabled.
Windows 10 build is 16299.309(Fall Creators).
Run as Administrator not worked.

**Comment by DDoSolitary** [comment]
Thank you for your information. I'll investigate it when I have time.

**Comment by DDoSolitary** [comment]
Could you please try to run with admin privilege?

**Comment by DDoSolitary** [comment]
Close as no response.

**Comment by sreekar2858** [comment]
Hi
Did you figure how to move the distro?

**Comment by DDoSolitary** [comment]
@sreekar2858 It seems that you're experiencing the same problem. I'll reopen this issue if you would like to help me fix it by providing some information because I can't reproduce this on my own machines.

**Comment by sreekar2858** [comment]
Oh thanks for the response.
Buy I think I got it figured out. I moved it to other drive it's working like a charm.
I didn't know how to install chocolatey, so did that and then ran lxrunoffline command, it's done.
