### ISSUE TITLE
could not open resolv.conf?

### ISSUE THREAD

**Issue by YAmikep** [DDoSolitary/LxRunOffline#39]
Anybody knows why I get this error?

```
PS D:\Dev\WSL\LxRunOffline-v2.2.2> D:\Dev\WSL\LxRunOffline-v2.2.2\LxRunOffline.exe install -n Ubuntu1604 -f ..\ubuntu-16.04-server-cloudimg-amd64.tar.gz -d ../Distros/Ubuntu1604
[ERROR] Couldn't open the file or directory "D:\Dev\WSL\Distros\Ubuntu1604\rootfs\etc\resolv.conf".
```

It happens with both of these images:
https://cloud-images.ubuntu.com/releases/artful/release/ubuntu-17.10-server-cloudimg-amd64.tar.gz
https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64.tar.gz

It works when using the tar files from `https://lxrunoffline.apphb.com/download/{distro}/{version}` as the Wiki suggested but I don't want to use them because those are Ubuntu core images which do not contain `sudo` (command not found) or updating the system did not work (`apt-get`).

Thanks

**Comment by DDoSolitary** [comment]
You used the wrong image files. These files don't directly contain root filesystem. You can download correct files using instructions in [Wiki](https://github.com/DDoSolitary/wiki)

**Comment by DDoSolitary** [comment]
You can use apt-get to install `ubuntu-minimal ubuntu-standard ubuntu-server` to create a Ubuntu Server installation from Ubuntu Core.
