### ISSUE TITLE
Cannot install on Windows 10 x64  v1603

### ISSUE THREAD

**Issue by TP73** [DDoSolitary/LxRunOffline#4]
Hello,

I can't seem to install this successfully. The files are downloaded to the folder "C:\Users\Admin\Downloads\". All the files has the block the file check removed. Please advise...

******************
C:\Users\Admin\Downloads\LxRunOffline-v1.1.0>LxRunOffline.exe /install
Enter path to the Ubuntu image file: C:\Users\Admin\Downloads\
Enter path to the icon file: C:\Users\Admin\Downloads\
Error: Failed to launch LxRun.
System.ArgumentException: STATUS_INVALID_PARAMETER_1: The given process file does not exist. (Code: 2)
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.CreateAndInject(String InEXEPath, String InCommandLine, Int32 InProcessCreationFlags, InjectionOptions InOptions, String InLibraryPath_x86, String InLibraryPath_x64, Int32& OutProcessId, Object[] InPassThruArgs)
   at LxRunOffline.Program.Main(String[] args)

**Comment by DDoSolitary** [comment]
You have to enable the `Windows Subsystem for Linux` feature first.

**Comment by TP73** [comment]
Thanks.

I still cannot seem to get this work. Here is what I followed so far...

1. Enabled Windows subsystem for Linux
2. Enabled developer mode
3. Downloaded stable release of LXRunoffline, Linux image and ubuntu icon
4. Open command prompt as an administrator
5. Type lxrunoffline /install from c:\Users\admin\download folder
6. Type the absolute path to the Linux image folder - c:\Users\admin\download folder (note - should I extract the .gz file or will the installer does that automatically?)
7. Type the absolute path to the ubuntu icon folder - c:\Users\admin\download folder

It tries to download from Windows store and fails as Windows store is removed from the image.

Is there anything I am missing or does it need any other pre-requisites to be installed prior? Any advice will be highly appreciated...

**Comment by DDoSolitary** [comment]
I don't think it is related to Windows Store. Although lxrun.exe says it downloads from Windows Store, it downloads files directly in fact.
There is no need to extract the .gz file, Windows does this automatically. (In fact, it won't work if you extract it. :smile:)
Could you please provide the error message you're getting now? Or are you still getting the same message even after enabling the subsystem for linux?
Besides, the latest release doesn't require absolute paths anymore, relative ones are supported now.

**Comment by TP73** [comment]
Please find below the error I receive while running the installer....
[LxRunOffline.docx](https://github.com/DDoSolitary/LxRunOffline/files/1069346/LxRunOffline.docx)

**Comment by DDoSolitary** [comment]
The path should include the filename. e.g. `c:\tmp\ubuntu.tar.gz`

**Comment by TP73** [comment]
Thanks very much. Once I had the complete path installation went fine.

How could I access bash prompt.....

**Comment by DDoSolitary** [comment]
You can find a shortcut in the Start menu.
Or just type `bash` in the command prompt.
