### ISSUE TITLE
Distros installed on windows insider build 17643 doesn't launch

### ISSUE THREAD

**Issue by problem233** [DDoSolitary/LxRunOffline#40]
中文：旧版本（RS4 的预览版）上安装的发布版现在仍然可以运行，但是在 Build 17643 上新安装的发布版无法运行，报 0x80070005 错误。安装的发布版是 Arch Linux。另外我发现新的 Arch Linux rootfs 压缩包里没有 /init，不知道是否有影响。

**Comment by Biswa96** [comment]
There is no need to have a init in distribution tarball. LxssManager service automatically adds that in rootfs folder at every launch time. Did you download the Arch tarball from the mentioned link?

**Comment by DDoSolitary** [comment]
我的insider build也才17134欸，你哪来的17643。。
init是不影响的，wsl用的init是微软提供的，就算本来有也会被覆盖掉

**Comment by yar999** [comment]
我的是17134.1 安装好运行 LxRunOffline.exe run -n ubuntu 的时候提示 0x80070005 ,用管理员模式运行一次 LxRunOffline.exe run -n ubuntu 进入wsl了, 退出 管理员模式, 在使用普通模式就正常了

**Comment by DDoSolitary** [comment]
@yar999 `LxRunOffline install`时有没有用管理员模式

**Comment by yar999** [comment]
没有哦

是普通用户模式 LxRunOffline install

**Comment by DDoSolitary** [comment]
那就有点奇怪了。。

**Comment by yar999** [comment]
之前 1709 用着很正常, 格式化c盘安装 1803 之后,  `LxRunOffline register -n ubuntu -d xxx`  提示什么是之前的版本安装的(具体错误提示忘记了), 后来重新 `LxRunOffline install` 安装没有报错, `LxRunOffline run` 的时候报错  0x80070005, 用管理员运行cmd 再 `LxRunOffline run` 进入ubuntu, 然后再从普通用户模式 `LxRunOffline run` 也正常了.

感谢 @DDoSolitary 提供这个工具,很方便

**Comment by problem233** [comment]
@DDoSolitary 欸，经测试我这里也是这个情况。
仍然是之前安装的那个 ArchLinux，直接run，错误: 0x80070005；在管理员用户下run了一下，正常，再用普通权限run，正常。

**Comment by DDoSolitary** [comment]
同17661无法复现。。迷。。

**Comment by DDoSolitary** [comment]
隔壁 #42 看来是相同的问题，这边就先close了
