### ISSUE TITLE
Other distros stopped working after the Windows April 2018 update

### ISSUE THREAD

**Issue by gaurav-nelson** [DDoSolitary/LxRunOffline#42]
With the latest update existing distros installed previously stopped working. But the officially installed Ubuntu is working fine. 

How to get around this?

Errors (mintty):
```
/bin/wslbridge: Exit 1.
wslbridge error: failed to start backend process
note: bash.exe output: Error: 0x80070005
```
Also: 
```
G:\LxRunOffline-v2.2.2>LxRunOffline.exe run -w -n ubuntu222
Error: 0x80070005
```

**Comment by makail** [comment]
This is happening to me also after upgrading to Windows 10 build 1803. I've tried installing fresh from Ubuntu packages and also installing Ubuntu from the Windows Store and then using LxRunOffline to move the install, both having the same result.

Let me know if you need more information. I can dig whatever you need up.

**Comment by DDoSolitary** [comment]
I haven't found out the actual reason for this problem but launching the distro with admin privilege may solve this problem, as reported by @yar999

**Comment by CopperKun** [comment]
I've got into the same problem

**Comment by gaurav-nelson** [comment]
@DDoSolitary With admin privileges I see the following warning:
```
[WARNING] You are running LxRunOffline with administrator privileges. It may cause problems.
Do you want to continue? (y/n):
```

**Comment by YAmikep** [comment]
Same issue here.
I used to use Wsltty `%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL="DISTRONAME" -h err --configdir="%APPDATA%\wsltty" -~` (in a shortcut) but this is not working anymore.

I tried to install a fresh new distro but it's not working either.

If I run a Powershell with admin privileges and then run `LxRunOffline.exe run -n DISTRONAME`, it seems to work.

**Comment by DDoSolitary** [comment]
Could you please check if broken distros can be launched by bash.exe(before running it as admin)

**Comment by YAmikep** [comment]
@DDoSolitary How do you launch other distros with `bash.exe`?

**Comment by AleckAgakhan** [comment]
The system attempts to inject new '/init' after being updated so it needs the distro to be started with administrative privileges. Just make first run of 'LxRunOffline.exe run -n <you-distro>' in cmd console that is started as 'Run as administrator'.

**Comment by gaurav-nelson** [comment]
Thanks @DDoSolitary @YAmikep @AleckAgakhan 
This issue is now resolved. I also noticed that you don't need admin rights if you do this using the `wslconfig` utility. Here is what worked for me:

```
C:\WINDOWS\system32>wslconfig.exe /l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
Fedora
Arch
Ubuntu2

C:\WINDOWS\system32>wslconfig.exe /s Ubuntu2

C:\WINDOWS\system32>bash
Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...
root@TEST:/mnt/c/Windows/System32# exit
logout

C:\WINDOWS\system32>
```

**Comment by DDoSolitary** [comment]
Hey guys, did you install your distribution on a non-system drive (e.g. D:)?

**Comment by Biswa96** [comment]
This is related to the folder permission. There is a workaround mentioned in this thread https://github.com/Microsoft/WSL/issues/3304#issuecomment-398489972

Let say you want to install in `D:\foo\bar`. Then run this command before installation: `icacls "D:\foo\bar" /grant Everyone:(OI)(CI)(F)`. You may replace `Everyone` with `%username%`. 

Hope this will solve your issue!

**Comment by DDoSolitary** [comment]
@Biswa96 I just tested it. Giving "Modify" permission to "Users" solves the issue. I'll try to integrate it into this project.

**Comment by DDoSolitary** [comment]
I don't want to "fix" a "bug" which is actually a Windows' bug. So I just added a warning message. Please wait for MS to fix it.

**Comment by PeterTheMaster1** [comment]
After updating to 1803 i had the same problem as some of you above "Error: 0x80070005"

As i have a lot of stuff installed on my ubuntu wsl, starting everything from scratch again wasnt an option for me.
Fortunately i still had a clean ubuntu wsl installation from 1709 to compare with a clean install on 1803 which works.

Only difference was the rootfs/init file. So i took winhex and copied the content of the working ubuntus init file to the old ubuntu init file. Problem solved

**Comment by mrdimfox** [comment]
I've still got this error on my Windows 10 build 1803.
I want to install Ubuntu Bionic on a non-system drive. I've created a folder "E:\WSL\bionic", run 
`icacls "E:\WSL\bionic" /grant "%USERNAME%":(OI)(CI)(F)`
before the installation. Then I've started this command from a non-admin powershell:
`LxRunOffline install -n bionic -f '.\tar\ubuntu-bionic-core-cloudimg-amd64-root.tar.gz' -d bionic`
Then I've tryied to make the first start of bash.exe with admin priveleges as @AleckAgakhan has recomended:
`LxRunOffline run -n bionic`
But I've got a error:
`Error: 0x80070002`

**Comment by Biswa96** [comment]
@mrdimfox Did you see any error during installation?
BTW, @ddosolitary The error messages can be retrieved with FormatMessage() (without manually writing).

**Comment by mrdimfox** [comment]
@Biswa96 I have no errors, but I have warings like
```[WARNING] Ignoring an unsupported file "dev/random" of type 8192.
[WARNING] Ignoring an unsupported file "dev/null" of type 8192.
[WARNING] Ignoring an unsupported file "dev/ptmx" of type 8192.
[WARNING] Ignoring an unsupported file "dev/urandom" of type 8192.
[WARNING] Ignoring an unsupported file "dev/tty" of type 8192.
[WARNING] Ignoring an unsupported file "dev/zero" of type 8192.
[WARNING] Ignoring an unsupported file "dev/full" of type 8192.```

**Comment by mrdimfox** [comment]
Hm, I suddenly notice that I have a different error code than topicstarter. May be I am writing in the wrong thread.

**Comment by DDoSolitary** [comment]
@Biswa96 The error code is directly output by WSL. Actually `WslLaunchDistributionInteractive` returns `S_OK` even if there's an error so there's nothing I can do. All other error codes returned by Win32 API calls are converted into error messages before being printed.

**Comment by DDoSolitary** [comment]
@mrdimfox please open a new issue, thanks.
