### ISSUE TITLE
ArchLinux does not install on 1803

### ISSUE THREAD

**Issue by p-A-uLo** [DDoSolitary/LxRunOffline#43]
Is windows 1803 supported by version 2.2.2 ?
I tried to install archlinux but wslconfig /l says no distro is installed.
Tried to create the shortcut with distro key, answer is the same.

**Comment by DanielChesters** [comment]
Hi, 

I succeded to install ArchLinux on Windows 10 (1803) with LxRunOffline 2.2.2 (wslconfig /l return ArchLinux extra installed distro on my machine) but when I try to run ArchLinux, I have an error 0x80070005.

**Comment by DDoSolitary** [comment]
@DanielChesters Not the same issue. Please see #42.

**Comment by p-A-uLo** [comment]
Hello DDoSolitary, I think it's related. After reading the posts in 
#42, I just run bash once with admin privileges and it fixed the issue. It seems non officially supported distros need wsl to perform a file system tweak which requires admin rights.
ArchLinux is now listed correctly when I run wslconfig /l.
I close this issue as its title does not reflect precisely the problem. Maybe it could be a good idea to reopen one mentioning error 0x80070005.

Thanks for your work on this, it's really cool to have our favourite distribution running on wsl.
