### ISSUE TITLE
After moving, home directory is lost

### ISSUE THREAD

**Issue by Menooker** [DDoSolitary/LxRunOffline#45]
I installed WSL Ubuntu 16 using "lxrun /install" and I moved the installed Ubuntu using LxRunOffline using command :
LxRunOffline move -n Legacy -d d:\WSL\ubuntu

As a result, only rootfs is move. But the home directory is not mounted in lxss/rootfs/home but in lxss/home. So my home directory is lost forever.

**Comment by DDoSolitary** [comment]
I'm really sorry for the data loss. It is fixed because the whole installation directory is moved now.

**Comment by Menooker** [comment]
Thank you for your bug fix! Your tool is useful & important in many cases and I still like it a lot.
