### ISSUE TITLE
Failed to duplicate a distribution

### ISSUE THREAD

**Issue by JaimeChavarriaga** [DDoSolitary/LxRunOffline#49]
I am trying to duplicate a distribution and got an error.

**Using the 3.0.1 version**
I got an error message indicating a problem with the registry. After running the command, the registry is modified and the the following lxrunoffline commands gets error. If I have a running linux window it got an error too and the system halts. To restore the registry values I must close the linux windows and run again the linux distribution.

```
C:\wsl>lxrunoffline version
LxRunOffline v3.0.1

C:\wsl>lxrunoffline list
Ubuntu-18.04

C:\wsl>lxrunoffline duplicate -n Ubuntu-18.04 -d c:\wsl\copy -N copy
[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\{C383C0DA-8922-4B53-B019-4110BA9EC5EB}".
Reason: The system cannot find the file specified.

C:\wsl>lxrunoffline list
[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\{C383C0DA-8922-4B53-B019-4110BA9EC5EB}".
Reason: The system cannot find the file specified.
```

I must mention that the registry looks unmodified when I use Powershell. The values remains the same before and after running the commands.

```
PS> (Get-ChildItem "HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss" -Recurse)

    Hive: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss

Name                           Property
----                           --------
{D935AE08-6853-4418-B736-C50C9
C6EEABD}
{e45b4078-48eb-4564-b597-8b9de State              : 1
1fd44b6}                       DistributionName   : Ubuntu-18.04
                               Version            : 1
                               BasePath           : C:\Users\Jaime
                               Chavarriaga\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79
                                                    rhkp1fndgsc\LocalState
                               PackageFamilyName  : CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc
                               KernelCommandLine  : BOOT_IMAGE=/kernel init=/init ro
                               DefaultUid         : 1000
                               Flags              : 7
                               DefaultEnvironment : {HOSTTYPE=x86_64, LANG=en_US.UTF-8,
                                                    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bi
                               n:/usr/games:/usr/local/games,
                                                    TERM=xterm-256color}
```
---
**Using the 2.2.2 version**
Here, I got an error because the software cannot copy a file

```
C:\wsl>lxrunoffline duplicate -n Ubuntu-18.04 -d c:\wsl\copy -N copy
[ERROR] Couldn't open the file or directory "C:\wsl\copy\rootfs\etc\alternatives\mpicc".
```
In the original linux distribution, this files is a symbolic link to a command.

```
$ ls -al /etc/alternatives/mpicc
lrwxrwxrwx 1 root root 20 May 24 20:19 /etc/alternatives/mpicc -> /usr/bin/mpicc.mpich

$ ls -al /usr/bin/mpicc.mpich
-rwxr-xr-x 1 root root 9518 Sep 25  2017 /usr/bin/mpicc.mpich
```

**Comment by DDoSolitary** [comment]
v3.0.1 has a bug of duplicating, please try the dev releases.

**Comment by JaimeChavarriaga** [comment]
I got another error using the `LxRunOffline-v3.0.1-21-gd18b49a.zip (USE MSYS=false)` dev release. According to the messages, it is not able to get access to the extended attributes of the files in the source distribution folder.

---
**Running as a normal user**

When I run the program as a normal user, I got first some errors related to the attributes of the target folder.

    C:\>lxrunoffline version
    LxRunOffline v3.0.1-21-gd18b49a

    C:\>lxrunoffline duplicate -n Ubuntu-18.04 -d d:\wsl\ubuntu -N ubuntu18
    [ERROR] Couldn't set the case sensitive attribute of the directory "\\?\d:\wsl\ubuntu\".
    Reason: {Access Denied}
    A process has requested access to an object, but has not been granted those access rights.

    [WARNING] You may have run into a known bug of Windows (https://github.com/Microsoft/WSL/issues/3304). Please try giving "Delete subfolders or files" permission of the target directory to the current user or simply running this tool with admin privilege.

Checking the warning, I grant additional permissions to the user used to create the copy

    C:\>whoami
    test\jaime

    C:\>icacls D:\wsl /grant "jaime:(OI)(CI)(F)"

Then, a different error appeared. It was related to the access to metadata of the files in the distribution to copy.

    C:\>lxrunoffline duplicate -n Ubuntu-18.04 -d d:\wsl\ubuntu -N ubuntu18
    [ERROR] Couldn't get extended attributes of the file or directory "\\?\C:\Users\nnn\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\bin\bash".
    Reason: {Access Denied}
    A process has requested access to an object, but has not been granted those access rights.

As a result, the folder is created and a `bash` file is copied, but the rest of the filesystem does not. In addition, the new distribution (ubuntu18) is registered but it is not usable.

To test again, first I must unregister the target distribution and delete the target folder. 

    C:\>lxrunoffline unregister -n ubuntu18
    C:\>rmdir /q /s d:\wsl\ubuntu 

---
**Running as an Administrator**

The same error ocurrs when I run the command as an administrator

    D:\>lxrunoffline duplicate -n Ubuntu-18.04 -d d:\wsl\ubuntu -N ubuntu18
    [ERROR] Couldn't get extended attributes of the file or directory "\\?\C:\Users\nnn\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\bin\bash".
    Reason: {Access Denied}
    A process has requested access to an object, but has not been granted those access rights.

Before trying the copy, I had not started any WSL window/shell program. I restarted the computer and tested again and resulted in the same errors. I tried in two different computers with the same results.

**Comment by DDoSolitary** [comment]
Copying distros installed by LxRunOffline works well for me, and Microsoft Store is crashing on my machine so I can't test it...

@Biswa96 Could you please take a look?

**Comment by JaimeChavarriaga** [comment]
I just duplicated two distributions installed from the Windows Store: The copy resulted without displaying any error. The process copied files and registry settings. However, I was not able to start any command in the resulting copies. Probably I am missing something.

**No Messages during the copy**
```
C:\>lxrunoffline list
Ubuntu-18.04
kali-linux

C:\>lxrunoffline duplicate -n Ubuntu-18.04 -d c:\wsl\installed\ubuntu -N ubuntu

C:\>lxrunoffline duplicate -n kali-linux -d d:\wsl\installed\kali -N kali

C:\>lxrunoffline list
Ubuntu-18.04
kali-linux
kali
ubuntu
```

**Nothing happens when I try to run the copies**

```
C:\>lxrunoffline run -n Ubuntu-18.04 -w -c pwd
/home/test

C:\>lxrunoffline run -n ubuntu -w -c pwd

C:\>lxrunoffline run -n Ubuntu-18.04 -w -c "lsb_release -a"
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

C:\>lxrunoffline run -n ubuntu -w -c "lsb_release -a"

C:\>lxrunoffline run -n kali-linux -w -c pwd
/home/test

C:\>lxrunoffline run -n kali -w -c pwd
```

**Comment by JaimeChavarriaga** [comment]
I think the last development version corrected the error related to read the registry values.

I downloaded the development version (as a .zip file) from the [CI server](https://ci.appveyor.com/project/DDoSolitary/lxrunoffline/), extracted the files in a folder and included that folder in the PATH environment variable.
* For the v3.0.1-23-g9210be8, go to the `Artifacts` link in the [last job page](https://ci.appveyor.com/project/DDoSolitary/lxrunoffline/build/job/4paiq5y253snk2q6)

---
**Results when I ran the command**

I just ran the command to duplicate an Ubuntu 18 distribution, using the administrator user. I got no errors during the copy, but I cannot run any command in it. I have the same results running the command as a normal user.

```
D:\wsl>lxrunoffline version
LxRunOffline v3.0.1-23-g9210be8

D:\wsl>lxrunoffline duplicate -n Ubuntu-18.04 -d d:\wsl\ubuntu-copy -N ubuntu-copy

D:\wsl>lxrunoffline run -n ubuntu-copy -w -c "lsb_release -a"
```

**Comment by DDoSolitary** [comment]
With the help of Biswa96 I just successfully installed Ubuntu form store and reproduced the access denied error when reading extended attributes.
@JaimeChavarriaga It seems that you have worked around the error. How did you do it? Thanks.

**Comment by DDoSolitary** [comment]
I just tried fetching the attributes using [this tool](https://github.com/dmex/lxssattr) and it worked fine, so obviously there's something wrong in my code. I'll try to debug when I've got some time.

**Comment by Biswa96** [comment]
@DDoSolitary I use these two tools:
1. http://www.zezula.net/en/fstools/filetest.html
2. http://hex.pp.ua/ntfs-stream-explorer-eng.php

**Comment by JaimeChavarriaga** [comment]
In my computer, I only got errors copying a distribution installed from the windows store when I have not set the [permissions](https://github.com/Microsoft/WSL/issues/3304) in the target folder.

```
C:\>lxrunoffline version
LxRunOffline v3.0.1-23-g9210be8

C:\>mkdir wsl-2

C:\>lxrunoffline list
Ubuntu

C:\>lxrunoffline duplicate -n Ubuntu -d C:\wsl-2\copy -N Ubuntu-copy
[ERROR] Couldn't set the case sensitive attribute of the directory "\\?\C:\wsl-2\copy\".
Reason: {Access Denied}
A process has requested access to an object, but has not been granted those access rights.

[WARNING] You may have run into a known bug of Windows (https://github.com/Microsoft/WSL/issues/3304). Please try giving "Delete subfolders or files" permission of the target directory to the current user or simply running this tool with admin privilege.

C:\>whoami
test\jaime

C:\>icacls C:\wsl-2 /grant "jaime:(OI)(CI)(F)"
processed file: C:\wsl-2

C:\>lxrunoffline uninstall -n Ubuntu-copy

C:\>lxrunoffline duplicate -n Ubuntu -d C:\wsl-2\copy -N Ubuntu-copy
```
---
Do you have some tests I can do to get more information?

**Comment by JaimeChavarriaga** [comment]
Although I got no errors during the copy, I cannot run the resulting copy. 

I compared the event logs produced running the Ubuntu installed from the Windows Store (that works correctly) and the duplicated one (that fails)
- I captured the event logs following the instructions in [the WSL troubleshooting page](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#starting-bash-gives-an-error-code)
- I installed the [Windows Driver Kit (WDK)](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) and used the [TraceView](https://docs.microsoft.com/es-es/windows-hardware/drivers/devtest/traceview) to read the ETL files.

The main differences between the `lxcore_kernel` logs are two messages present only in the copy that fails:

```
Name		: Microsoft.Windows.Subsystem.LxCore 
Event ID	: 4631  
Level		: 2 (Error)   
Message		: {"name":"DevLogWritten","instanceId":"FE316EAC-B962-4B7A-AEF8-1258C3030D94",
                  "LxPid":4,"LxTid":4,"EventInfo->Level":6,"Tag":"init",
                  "Message":"(4) ERROR: CreateProcessEntry:2783: chdir failed 13\n",
                  "FormattedMessage":true,"RawMessage":""}

Name		: Microsoft.Windows.Subsystem.LxCore 
Event ID	: 4631  
Level		: 2 (Error)   
Message		: {"name":"DevLogWritten","instanceId":"FE316EAC-B962-4B7A-AEF8-1258C3030D94",
                  "LxPid":4,"LxTid":4,"EventInfo->Level":6,"Tag":"init",
                  "Message":"(4) FATAL_ERROR: CreateProcessEntry:2792: execvpe /bin/bash failed 13\n",
                  "FormattedMessage":true,"RawMessage":""}
```

The other log files (`lxcore_service`, `lxcode_adss` and `lxcore_user`) are basically equal.

Checking the Streams (Extended attributes) of the `rootfs` and the `rootfs/init` files with the [lxssattr](https://github.com/dmex/lxssattr), they look with the same linux permissions.

**Comment by DDoSolitary** [comment]
Please try the latest dev release. Hopefully the bug has been fixed.

**Comment by JaimeChavarriaga** [comment]
I was able to duplicate distributions installed from the Windows Store using the dev release. I tested on two computers and it works for me.
