### ISSUE TITLE
Unknown error in injected C++ completion routine. (Code: 15)

### ISSUE THREAD

**Issue by wlmnzf** [DDoSolitary/LxRunOffline#5]
It doesn't work in my computer,I'm sorry I don't know why!

> Error:
 Failed to launch LxRun.
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
   在 EasyHook.RemoteHooking.CreateAndInject(String InEXEPath, String InCommandLine, Int32 InProcessCreationFlags, InjectionOptions InOptions, String InLibraryPath_x86, String InLibraryPath_x64, Int32& OutProcessId, Object[] InPassThruArgs)
   在 LxRunOffline.Program.Main(String[] args)

**Comment by DDoSolitary** [comment]
Did you `unblock` the binary files? Please take a look at #1

**Comment by DDoSolitary** [comment]
Closing as no response.

**Comment by QGB** [comment]
@DDoSolitary   i unblocked the binary files . And ` Set-ExecutionPolicy Unrestricted`, but still encounter
```
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
```

**Comment by DDoSolitary** [comment]
@QGB What Windows version are you using? The v1.x releases are obsolete and only works on Windows 10 v1709 or earlier.

**Comment by QGB** [comment]
@DDoSolitary    Windows 10.0 Build 18363 
EasyHook 2.7

**Comment by DDoSolitary** [comment]
@QGB build 18363 is v1909, which is no longer supported by the v1.x releases. Compatibility info: https://github.com/DDoSolitary/LxRunOffline#compatibility

Please use the latest release.
