### ISSUE TITLE
[Feature Request] Actions to store/apply registry configurations

### ISSUE THREAD

**Issue by JaimeChavarriaga** [DDoSolitary/LxRunOffline#53]
Adding actions to manage a pre-defined set of configuration values in the registry can improve the process to backup/restore distributions. A custom `.wslconf` file or a `.reg` registry export can be used to store and apply these values.

For instance, it can be useful to backup and restore distributions. Nowadays, to backup a distro:
  - **Backup:** (1) making a `.tar.gz` of the `/` root directory in the linux, (2) storing the corresponding registry values 
  - **Restore:** (1) uninstalling the distribution to avoid conflicts with the name (1) installing the `.tar.gz` using lxRunOffline and the same name for the distribution and (2) setting the configuration values in the registry. Note that restoring in this way, it creates a new UUID in the registry and any registry export must be modified.

---
**Suggested action: get / backup a configuration**

A **get-wslconf** action that gets the configuration stored in the registry
```
# shows the configuration information
C:\wsl> lxrunoffline get-wslconf -n Ubuntu-18.04
UUID={474fefcd-71b7-44d8-af0a-15bbfb5314c9}
State=0x1
Version=0x1
BasePath="C:\\Users\\nnn\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\\LocalState"
PackageFamilyName="CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc"
KernelCommandLine="BOOT_IMAGE=/kernel init=/init ro"
DefaultUid=1000
Flags=0x7

[DefaultEnvironment]
HOSTTYPE=x86_64
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
TERM=xterm-256color


# stores the configuration into a wslconf file
C:\wsl> lxrunoffline get-wslconf -n Ubuntu-18.04 -f c:\wsl\configs\today.wslconf
```
---
**Suggested action: apply a configuration file**

A **set-wslconf** that sets into the registry the configuration stored in a .wslconf file
```
# stores the configuration into a wslconf file
C:\wsl> lxrunoffline set-wslconf -n Ubuntu-18.04 -f c:\wsl\configs\today.wslconf
[WARNING] The UUID of the Ubuntu-18.04 distro will not be overwritten
```

---
**Suggested improvement: install a distro using a wslconf file**

Add to the **install** action support to use `.wslconf` files during installation.

```
# installs c:\wsl\backups\today.tar.gz using a today.wslconf in the same folder
C:\> lxrunoffline install -n new -f c:\wsl\backups\today.tar.gz -d c:\wsl\distros\new 
There is an existing c:\wsl\backups\today.wslconf configuration. 
Do you want to apply that configuration? [Yes/No]

# installs using the wslconf file without asking confirmation if there is a wslconf file
C:\> lxrunoffline install -n new -q -f c:\wsl\backups\today.tar.gz -d c:\wsl\distros\new 

# installs using a wslconf file in another folder
C:\> lxrunoffline install -n new -f c:\wsl\backups\today.tar.gz -c c:\wsl\configs\today.wslconf -d c:\wsl\distros\new 
```

---
**Current solution: exporting registry values**

To export a complete configuration (including `KernelCommandLine`, `DefaultUid` and `DefaultEnvironment`, it is necessary to obtain the UUID and export the corresponding subtree. 

1. **Obtaining the UUID** can be achieved using Powershell or the `reg query command`

```
PS1> (Get-ChildItem HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss | ForEach-Object {Get-ItemProperty $_.PSPath} | select PSChildName, DistributionName)

PSChildName                            DistributionName
-----------                            ----------------
{474fefcd-71b7-44d8-af0a-15bbfb5314c9} Ubuntu-18.04
{491F0DE7-BA81-412F-899C-3168F550A0AB} Ubuntu-copy
```

2. **Exporting the configuration** can be performed using that UUID
```
C:\wsl>reg export HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss\{474fefcd-71b7-44d8-af0a-15bbfb5314c9} example.reg

C:\wsl>type example.reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\{474fefcd-71b7-44d8-af0a-15bbfb5314c9}]
"State"=dw
"DistributionName"="Ubuntu-18.04"
"Version"=dword:00000001
"BasePath"="C:\\Users\\nnn\\AppData\\Local\\Packages\\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\\LocalState"
"PackageFamilyName"="CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc"
"KernelCommandLine"="BOOT_IMAGE=/kernel init=/init ro"
"DefaultUid"=dword:000003e8
"Flags"=dword:00000007
"DefaultEnvironment"=hex(7):48,00,4f,00,53,00,54,00,54,00,59,00,50,00,45,00,3d,\
  00,78,00,38,00,36,00,5f,00,36,00,34,00,00,00,4c,00,41,00,4e,00,47,00,3d,00,\
  65,00,6e,00,5f,00,55,00,53,00,2e,00,55,00,54,00,46,00,2d,00,38,00,00,00,50,\
  00,41,00,54,00,48,00,3d,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,\
  61,00,6c,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,\
  73,00,72,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,\
  00,62,00,69,00,6e,00,3a,00,2f,00,73,00,62,00,69,00,6e,00,3a,00,2f,00,62,00,\
  69,00,6e,00,3a,00,2f,00,75,00,73,00,72,00,2f,00,67,00,61,00,6d,00,65,00,73,\
  00,3a,00,2f,00,75,00,73,00,72,00,2f,00,6c,00,6f,00,63,00,61,00,6c,00,2f,00,\
  67,00,61,00,6d,00,65,00,73,00,00,00,54,00,45,00,52,00,4d,00,3d,00,78,00,74,\
  00,65,00,72,00,6d,00,2d,00,32,00,35,00,36,00,63,00,6f,00,6c,00,6f,00,72,00,\
  00,00,00,00
```

3. **Importing the registry values** in the same location (i.e. to the same UUID -- the same distribution) using `reg import`

```
C:\wsl> reg import example.reg
``` 

**NOTE:** To apply that configuration into another distribution, it is necessary to alter the file and overwrite the UUID.

**Comment by DDoSolitary** [comment]
I plan to make the following changes:

- `export-reg` Export to a .reg file
- `import-reg` Import from a .reg file for an existing distro
- `install -R` Install a new distro using a .reg file

Please let me know if you have any suggestions.

**Comment by DDoSolitary** [comment]
Well, I closed it by accident...

**Comment by JaimeChavarriaga** [comment]
Great !!.  I think these `.reg` files will facilitate backuping and restoring distributions.

---
**NOTE:** For me, the only problem with the `.reg` format (at least, of the obtained from my tests) is the representation of the `DefaultEnvironment`. It is hard to modify using a text editor. 

```
"DefaultEnvironment"=hex(7):48,00,4f,00,53,00,54,00,54,00,59,00,50,00,45,00,3d,\
  00,78,00,38,00,36,00,5f,00,36,00,34,00,00,00,4c,00,41,00,4e,00,47,00,3d,00,\
  65,00,6e,00,5f,00,55,00,53,00,2e,00,55,00,54,00,46,00,2d,00,38,00,00,00,50,\
   :
```

However, this ´.reg´ is the standard file format.

**Comment by DDoSolitary** [comment]
After thinking over it again, I found out that using .reg files brings much complexity because I have to replace GUID and remove values like distro name when importing. Also I noticed that boost-program-options, which is currently used for command line argument processing, has support for config files so it seems nice to use it for saving registry config.
