### ISSUE TITLE
[Feature Request] Actions to backup/restore distributions

### ISSUE THREAD

**Issue by JaimeChavarriaga** [DDoSolitary/LxRunOffline#54]
Adding to LxRunOffline actions to backup and restore distributions can be really useful to developers or administrators using WSL to install and test multiple applications.

LxRunOffline can automate the tasks necessary backup and restore distributions: 
  - **Backup:** (1) making a `.tar.gz` of the `/` root directory in the linux, (2) storing the corresponding registry values 
  - **Restore:** (1) uninstalling the distribution to avoid conflicts with the name (1) installing the `.tar.gz` using lxRunOffline and the same name for the distribution and (2) setting the configuration values in the registry.

---
**Suggested action: backup a distro**

A **backup** action that creates two files: a `tar.gz` file with the filesystem content and a `.wslconf` (a file in a .ini or in another format) with the corresponding registry values
```
# creates c:\wsl\backups\today.tar.gz and c:\wsl\backups\today.wslconf
C:\> lxrunoffline backup -n Ubuntu-18.04 -f c:\wsl\backups\today.tar.gz

# creates c:\wsl\backups\today.tar.gz and c:\wsl\configs\today.wslconf
C:\> lxrunoffline backup -n Ubuntu-18.04 -f c:\wsl\backups\today.tar.gz -c c:\wsl\configs\today.wslconf
```

---
**Suggested action: restore a backup**

A **restore** action that takes the above two files and restore the distribution, possibly overwriting an existing one.
```
# restores c:\wsl\backups\today.tar.gz and c:\wsl\backups\today.wslconf
C:\> lxrunoffline restore -f c:\wsl\backups\today.tar.gz
There is an existing Ubuntu-18.04 distribution. 
Do you want to overwrite? [Yes/No]

# restores using a wslconf file in another folder
C:\> lxrunoffline restore -f c:\wsl\backups\today.tar.gz -c c:\wsl\configs\today.wslconf
There is an existing Ubuntu-18.04 distribution. 
Do you want to overwrite? [Yes/No]

# restores without asking for confirmation
C:\> lxrunoffline restore -q -f c:\wsl\backups\today.tar.gz
```

---
**Current solution**

1. **Creating the backup** running `tar` in the WSL linux distribution.  Note that it is necessary to ignore some folders (e.g. /mnt) in the copy. In the example, the files are created into a Windows folder: the `/mnt/c/tmp`.

```
    C:\wsl> lxrunoffline run -n Ubuntu-18.04 -w
    # cd /
    # tar vzcpf /mnt/c/tmp/ubuntu_`date +%Y%m%d_%H`.tar.gz --exclude=/proc --exclude=/dev --exclude=/mnt --exclude=/media --exclude=/lost+found  --exclude=/tmp --exclude=/sys  --exclude=/run / > /mnt/c/tmp/ubuntu_`date +%Y%m%d_%H`.log 2> /mnt/c/tmp/ubuntu_`date +%Y%m%d_%H`.error
```

2. **Storing some configuration in the registry** such as the default user, kernel commands and default environment.

```
    C:\wsl> lxrunoffline get-kernelcmd -n Ubuntu-18.04
    C:\wsl> lxrunoffline get-uid -n Ubuntu-18.04
    C:\wsl> lxrunoffline get-env -n Ubuntu-18.04
    C:\wsl> lxrunoffline get-flags -n Ubuntu-18.04
```

3. **Restoring the backup** by installing the resulting `.tar.gz` using lxRunOffline. To restore the distro using an existing name, it is necessary to `uninstall` that distribution first.

```
    C:\wsl> lxrunoffline install -n mybackup -d c:\wsl\mybackup -f c:\tmp\ubuntu_20180729_00.tar.gz
```

3. **Restoring the configuration** by hand.

```
    C:\wsl> lxrunoffline set-kernelcmd -n mybackup -v  ...
    C:\wsl> lxrunoffline set-uid -n mybackup -v  ...
    C:\wsl> lxrunoffline set-env -n mybackup -v  ...
    C:\wsl> lxrunoffline set-flags -n mybackup -v  ...
```

**Comment by DDoSolitary** [comment]
I'll work on this later because I want to refactor some of the code in `fs.cpp` to reduce duplicate code and make transition to the next Win10 release (there will be a major filesystem update) easier.
