### ISSUE TITLE
Norton and Defender flag as dangerous

### ISSUE THREAD

**Issue by matthewpersico** [DDoSolitary/LxRunOffline#57]
Windows Defender wouldn't let me run it and Norton deleted it from the disk. Latest version.

**Comment by Biswa96** [comment]
Virustotal doesn't shoe any serious warning. Here is the link of that zip package: https://www.virustotal.com/en/file/5851940f3746c8527a8b7d876547743e0bb8661996318b96bf313649718cdb1d/analysis/

**Comment by Biswa96** [comment]
Virustotal doesn't show any serious warning. Here is the link of that zip package: https://www.virustotal.com/en/file/5851940f3746c8527a8b7d876547743e0bb8661996318b96bf313649718cdb1d/analysis/

**Comment by JaimeChavarriaga** [comment]
Probably, it is related to potential malware based on WSL (a.k.a. Bashware)

- [Beware of the malware based on WSL](https://research.checkpoint.com/beware-bashware-new-method-malware-bypass-security-solutions/)
- [Executing malware in WSL](https://ibreak.software/2017/10/executing-windows-malware-in-windows-subsystem-for-linux-bashware/)

**Comment by matthewpersico** [comment]
I will try to free up some time to try again.

**Comment by DDoSolitary** [comment]
Please post the SHA512 checksum of the zip file so that I can see if it had been corrupted. It can be generated using `Get-FileHash` in PowerShell.
