### ISSUE TITLE
Can not run distro if no /bin/bash

### ISSUE THREAD

**Issue by shyam-saurabh** [DDoSolitary/LxRunOffline#59]
I installed alpine linux
`lxrunoffline install -n alpine -f ./alpine-minirootfs-3.8.1-x86_64.tar.gz -d ./alpine -r .`

then tried
`lxrunoffline r -n alpine`

which didn't work ofcourse since minirootfs dosen't provides /bin/bash instead it provides /bin/ash
so i tried
`lxrunoffline r -n alpine -c "/bin/ash"`
`lxrunoffline r -n alpine -c "/bin/sh"`

None worked while /bin/ash and /bin/sh are available on system no output no error just returns

Well i thought maybe i can install bash so i dug alpine guid from registry and used
`wsl {guid}`

and i was in then i did
`apk add bash`
`exit`

now when i tried 
`lxrunoffline r -n alpine -c "/bin/ash"`

i was in with /bin/ash as my shell
so if i don't have bash lxrunoffline dosen't allows running distro
take a look.

**Comment by DDoSolitary** [comment]
What is your Windows version? I couldn't reproduce it. On my machine, a direct `r` doesn't work (as expected, I'll probably add support for login shell settings in `passwd` later), but `r -c /bin/sh` worked well.

**Comment by DDoSolitary** [comment]
Well, it's Windows's problem which has already been fixed: https://github.com/Microsoft/WSL/issues/2372#issuecomment-364401708.

You need to update your Windows to get rid of this bug.

**Comment by shyam-saurabh** [comment]
yup can see its fixed in pre release i am still on default 17134.
thx for quick response
