### ISSUE TITLE
Error: 0x80010119

### ISSUE THREAD

**Issue by eksapetm** [DDoSolitary/LxRunOffline#6]
Hi,

I try to install Ubuntu with LxRunOffline but it fails:

c:\WSL\LxRunOffline-dev-9d7c59b>LxRunOffline.exe /install
Enter path to the Ubuntu image file: c:\WSL\16.04.2-server-cloudimg-amd64-root.tar.gz
Enter path to the icon file: c:\WSL\ubuntu.ico
Error: 0x80010119

WSL is enabled, Windows Defender is disabled, and I unblocked all the files in the LxRunOffline folder. I tried both the stable and the latest development build.

Do you have any idea what else I can do?

Thanks,

Maarten

**Comment by Biswa96** [comment]
* Does your user account have rights/ownership of that folder?
* Did you enable developer mode in settings app or with registry?
* Move those files to a new folder in User account directory (C:\users\username), the try that command.
* You may temporarily disabled UAC. See this [article](https://social.technet.microsoft.com/Forums/en-US/3a4e6c3d-dedf-4bb9-be3a-773031e31cb7/failed-to-initialize-security-error-code-0x80010119?forum=itprovistasecurity).

**Comment by eksapetm** [comment]
Thank you so much. Running LxRunOffline as administrator solved the problem!
