### ISSUE TITLE
Migrate of Ubuntu always ends with Couldn't open the file

### ISSUE THREAD

**Issue by dotSlashLu** [DDoSolitary/LxRunOffline#60]
Hi, thanks for this great project.

I run migrate command in CMD.exe as admin, but every time it fails with this 'couldn't open file' error without any reason:
```
C:\Users\J5RWGQ2\Downloads\LxRunOffline-v3.3.0>LxRunOffline.exe m -d D:\ -n Ubuntu
[ERROR] Couldn't open the file "\\?\C:\Users\J5RWGQ2\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\x86_64-linux-gnu\gconv\gconv-modules.cache".
Reason:
```

By the way, should I stop all WSL processes running when migrating? What if one of the running processes try to write to the file system while it's migrating? Will the migrated file system be damaged? If all the processes should be stopped, how? Since I don't know a way to 'shutdown' the WSL, actually I don't even know if it's possible to do so.

**Comment by DDoSolitary** [comment]
Yes, they should be stopped. Generally closing all bash windows should work. If not, stop the LxssManager service or simply reboot your system.

**Comment by DDoSolitary** [comment]
I'll investigate why it doesn't print any reason.

**Comment by DDoSolitary** [comment]
Output on my system:

`
C:\Users\DDoSolitary\Downloads>lxrunoffline move -n Ubuntu -d E:\
[ERROR] Couldn't open the file "\\?\C:\Users\DDoSolitary\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr\lib\x86_64-linux-gnu\gconv\gconv-modules.cache".
Reason: The process cannot access the file because it is being used by another process.
`

I'm not sure why it doesn't display the reason on your system.

**Comment by dotSlashLu** [comment]
Thanks. 

It seems all error messages are missing on my machine. I remember when I tried to migrated to an existing directory it reported no error message after failure yesterday either. 

I was running the latest release downloaded from github and my Windows is enterprise 1803.

**Comment by DDoSolitary** [comment]
https://ci.appveyor.com/api/buildjobs/6igvol594nllj1sb/artifacts/LxRunOffline-v3.3.0-4-g5f8419d.zip

Could you please try this build to see if the error messages work? Thanks.

**Comment by dotSlashLu** [comment]
This version prints error reasons as expected 👍 I'll close this issue.

**Comment by kongdd** [comment]
I can move WSL to another directory. But when exporting, I also come across this problem: "Can't open this file gconv-modules.cache".

**Comment by DDoSolitary** [comment]
@kongdd It seems to be a different problem. Please create a separate issue.
