### ISSUE TITLE
Debian 7 (Wheezy) will install but not run

### ISSUE THREAD

**Issue by semiaddict** [DDoSolitary/LxRunOffline#61]
First of all, thank you for this great tool !
I have successfully used it to install Debian 9 (Stretch), and would like to install Debian 7 (Wheezy) alongside Debian 9.

I have downloaded the tar file from https://lxrunoffline.apphb.com/download/debian/wheezy , and then installed it with the following command:
`LxRunOffline.exe i -n Debian7 -d Debian7 -f ../rootfs.tar.xz`

The installation succeeded with no error, but when I try to run the distribution with the below command, nothing happens, and no errors are thrown to cmd:
`LxRunOffline.exe r -n Debian7 -w`

I have tried to restart my machine, but that didn't change anything.

Is Debian Wheezy not supported?

PS: I'm running the LxRunOffline v3.3.0 binary on Windows 10 build 1803.

**Comment by Biswa96** [comment]
What you see in the Command Prompt window if you run simply `bash.exe` or `wsl.exe`? Can you collect the event logs as mentioned in [this instructions with logman.exe](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md)?

**Comment by semiaddict** [comment]
Thank you @Biswa96 for your time.

If I set the Debian7 disto to be the default one, running `bash.exe` or` wsl.exe` exits directly without outputting anything in the console.
If the Debian9 is the default one, it logs into the subsystem correctly.

I'm not sure I fully understand the instructions for logman.
However, here are the logs: [logman.zip](https://github.com/DDoSolitary/LxRunOffline/files/2480265/logman.zip)
I basically entered the three commands to start logging, then ran `wsl.exe` (which exited without outputting anything to the console), and typed the three commands  to stop the logging.
I hope that's the way to proceed.

And here's the output of the `ver` command, in case that helps in any way: Microsoft Windows [Version 10.0.17134.345]

**Comment by Biswa96** [comment]
I can reproduce your issue in my PC Windows 10 build 18247 Pro.  The main issue is from `/init` side. Here is the eye catching line in the logs: `ExecutablePath:mount Function:LxpSysFsUnexpectedLookupError Line:535 Message:Sysfs: Unsupported file /sys/fs/selinux`.

This issue may be related with https://github.com/Microsoft/WSL/issues/3592. But the new Debian9 Stretch works well. Try that as well. @benhillis may get more information from these logs.

Happy Linuxing!

**Comment by benhillis** [comment]
I may be wrong, but I'm almost positive we don't support xz archives, only gzip.

**Comment by semiaddict** [comment]
Thanx @Biswa96 and @benhillis for your insights.

Is there another way to get a Debian 7 working?
I'm trying to setup a test server that closely mimics the production one.

Otherwise I'll just stick with Debian 9 for the test server.

**Comment by Biswa96** [comment]
@semiaddict I found Debian [bug report about disabling legacy vsyscall](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874034). It mentioned a workaround with kernel commandline. But WSL may not support that. I tried to add `CONFIG_LEGACY_VSYSCALL_NONE=y` in `KernelCommandLine` registry but dosen't work. Stick with Debian9....

**Comment by semiaddict** [comment]
Thanx @Biswa96.
I'll stick with Debian 9 then.
