### ISSUE TITLE
Unable to change root as default user

### ISSUE THREAD

**Issue by viktorhbk** [DDoSolitary/LxRunOffline#62]
When I run `lxrunoffline run -n ubuntu-18.04-bionic` or `wsl.exe`  shell starts with a root user and every time I have to `su myusername` to start working. Is there a way to change default user on shell startup? 

Here's all I found in regards to this issue https://docs.microsoft.com/en-us/windows/wsl/user-support , but it doesn't work on distros installed with `lxrunoffline i`, only with one from MS Store.

lxrunoffline version - 3.3.0
OS - Win10, 1803
Distro - Ubuntu 18.04

**Comment by humix2** [comment]
For example, if the result of 'id myusername' is:
uid=1000(myusername) gid=1000(myusername)…
You run lxrunoffline su -n ubuntu-18.04-bionic -v 1000.
Type this command (lxrunoffline(only)) to see the options.

**Comment by viktorhbk** [comment]
@humix2 I took a look at the lxrunoffline earlier but didn't notice uid parameters somehow. Anyway here's the result:
zsh:
```
➜  run-length-encoding id vik
uid=1000(vik) gid=1000(vik) groups=1000(vik),27(sudo)
```

powershell:
```
PS C:\Users\Viktor> lxrunoffline list
Ubuntu-18.04 // these distros
ubuntu-old   // aren't relevant
ubuntu-18.04-bionic
PS C:\Users\Viktor> lxrunoffline su -n ubuntu-18.04-bionic -v 1000
PS C:\Users\Viktor> /* no error, nothing */
```

It doesn't error and I'm still inside powershell after command execution.

**Comment by humix2** [comment]
bash or wsl run.
user changed.

**Comment by viktorhbk** [comment]
```
PS C:\Users\Viktor> wsl
➜ ~ whoami
root
➜ ~ exit
PS C:\Users\Viktor> bash
root@vik-desktop:/mnt/c/Users/Viktor# whoami
root
root@vik-desktop:/mnt/c/Users/Viktor# exit
logout
PS C:\Users\Viktor> lxrunoffline run -n ubuntu-18.04-bionic
root@vik-desktop:/mnt/c/Users/Viktor# whoami
root
```

@humix2 Tried that as well, doesn't work.

**Comment by viktorhbk** [comment]
I did the reboot and it all works now. Thanks, closing.
