### ISSUE TITLE
[3.3.0] Microsoft Store installed filesystem not duplicated correctly.

### ISSUE THREAD

**Issue by patrickcarlohickman** [DDoSolitary/LxRunOffline#64]
I have Ubuntu installed through the Microsoft Store. It seems that the duplicate functionality doesn't appear to be picking up the filesystem version correctly. The `-v` option says that it uses the version of the source if it isn't specified.

The registry entry for the Store install shows Version 1.

When I duplicate with the `-v 1` option, everything appears to work fine.

When I duplicate without the `-v` option, it creates `cache`, `data`, `home`, `mnt`, and `root` directories as siblings of the `rootfs` directory. Inside the machine, everything in my `/home` directory is gone because it's looking at the `home` sibling, not `rootfs\home`.

I also get the same incorrect behavior if I duplicate with `-v 0`.

I don't know if this means anything, but if I duplicate with the `-v 2` option, attempting to run that instance results in "Error: 0x80070040". I'm not worried about this, just thought I'd mention it for extra information.

Thanks,
Patrick

**Comment by DDoSolitary** [comment]
It seems that the `Version` registry value is always incorrectly set to 0 if `-v` isn't specified. I just fixed it, please try the dev release, thanks. As for the error of `-v 2` I think it's because you're not on a Windows Insider build that supports the new WSL version.

**Comment by Biswa96** [comment]
How about this command: `wslconfig /upgrade <distro_name>`.

**Comment by DDoSolitary** [comment]
I doubt if this command will even exist on a build that doesn't support v2

**Comment by Biswa96** [comment]
I remember there were some builds where the upgrade option was implemented but not documented.
