### ISSUE TITLE
V3 non-ansi paths installation support

### ISSUE THREAD

**Issue by Domduv** [DDoSolitary/LxRunOffline#68]
Hello,

I had an image that I could install on Windows 1709 with V2.
But since 1803 and V3, the same image does not work anymore.

After debugging some, it seems that the peculiarity of that image is that it has openssl-server installed, and this package installs certificates that use non ansi character, like Ü.
V2 was ignoring these characters, but V3 just exits on them (I get it's related to the switch to libarchive).

As a workaround, removing the certificates produces a working image, but I thought others might have the same issue

**Comment by DDoSolitary** [comment]
Couldn't reproduce. I can install Unicode images properly. Could you please provide the error message and the image that you're having trouble with so that I can find out what's wrong?

**Comment by Domduv** [comment]
BTW, some more precision

- First I was mistaken, Ü works, but ğ does not (they're both part of the name of a turkish certificate).

- The exit comes (at the root) from the function archive_string_append_from_wcs_in_codepage in libarchive, where I end up getting into the tp_cp == CP_C_LOCALE case.
There, any non-ansi char will end up being translated as '?', and def_char being set to 1.
archive_entry_symlink  then detects the error code and return NULL.
The returned value is used by writer.write_symlink, and this crashes because of the null pointer.

**Comment by DDoSolitary** [comment]
I just tried your image and now I can reproduce it. It seems that libarchive returns the strings as-is by default but the image you provided has PAX headers so it is trying to perform some encoding conversion, which makes the things broken.

**Comment by DDoSolitary** [comment]
Fixed. You can try the dev builds mentioned in README.

**Comment by Domduv** [comment]
Hello,

this is indeed working now, thanks for the prompt fix!
