### ISSUE TITLE
"Parameter is incorrect" when installing to external HDD

### ISSUE THREAD

**Issue by steamp0rt** [DDoSolitary/LxRunOffline#69]
`lxrunoffline i -s -d D:\Programs\Ubuntu -n Ubuntu -f "C:\Users\Kitty\Downloads\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc\install.tar.gz"`

so, I tried to do that. but when I try to launch the installed distro, I just get `The parmeter is incorrect`. That's it.

**Comment by Dvbnhbq** [comment]
I moved the distribution of Ubuntu 18.04 installed from Microsoft Store to external HDD, and it starts no more. If I try to run a command with the `r` option, I get `The parameter is incorrect`.

**Comment by steamp0rt** [comment]
@DDoSolitary it's not an SD card, it's a storage space of several HDDs.

**Comment by steamp0rt** [comment]
Also, when using the VHD method, `Access is denied.`

Even tried doing `icacls W:\ /grant "kitty:(OI)(CI)(F)"`

**Comment by Biswa96** [comment]
Run the executable as admin and use `icacls W:\your-folder-path /grant "Everyone:(OI)(CI)(F)"`

**Comment by DDoSolitary** [comment]
@steamp0rt Unfortunately I can't create a storage space on my dev server which only has one HDD available to debug the program. As for the access denied error, I think it's because you installed to the root directory of the drive, which is known to cause issues. Please try to install to a subdirectory like W:\wsl.

**Comment by DDoSolitary** [comment]
Distros on storage spaces work well in my test VM. Please try the VHD method to see if the problem is with your environment.

// Closing due to no response

**Comment by steamp0rt** [comment]
Coming back to say running on storage spaces still doesn't work, with the latest release of LxRunOffline, with WSL2.

Logfiles zipped and attached.
[etl_logfiles.zip](https://github.com/DDoSolitary/LxRunOffline/files/3835783/etl_logfiles.zip)

**Comment by DDoSolitary** [comment]
Hello, according to your log, it seems that the disk drive is a mounted VeraCrypt volume. I suspect it is the root cause of the problem.

**Comment by steamp0rt** [comment]
also it turns out there's a way to just move the hard drive file to another disk

**Comment by DDoSolitary** [comment]
Yes, directly moving the files will work for WSL2

**Comment by DDoSolitary** [comment]
I've successfully reproduced this error using a VeraCrypt volume. Unfortunately, this is not something that I can fix. WSL requires a stable GUID (IOCTL_MOUNTDEV_QUERY_STABLE_GUID) on the drive that the distro is installed on, but VeraCrypt's filesystem driver doesn't support this ioctl. Probably you can ask Microsoft to remove this limitation or VeraCrypt to support the ioctl required.
