### ISSUE TITLE
Support for other distros including OpenSUSE

### ISSUE THREAD

**Issue by Biswa96** [DDoSolitary/LxRunOffline#7]
From Windows 10 v1709, Microsoft releases Ubuntu, OpenSUSE, SLES offline packages in this article [WSL Windows Server Installation Guide](https://msdn.microsoft.com/commandline/wsl/install-on-server). Like you've mentioned the Ubuntu Server Cloud-images for LxRunOffline, Are there any Cloud-images of the these distros?

-----

**Distribution Links:**
- Ubuntu:: https://aka.ms/wsl-ubuntu-1604/ redirects to https://wslstorestorage.blob.core.windows.net/wslblob/Ubuntu.1604.2017.711.0_v1.appx
- OpenSUSE:: https://aka.ms/wsl-opensuse-42/ redirects to https://wslstorestorage.blob.core.windows.net/wslblob/openSUSE-42_v1.appx
- SLES:: https://aka.ms/wsl-sles-12/ redirects to https://wslstorestorage.blob.core.windows.net/wslblob/SLES-12_v1.appx

-----

These .appx files can be opened with 7zip. _APPX packages contain_ some images in assets folder, _a distro UserSpace file in .tar.gz format_ like ubuntu.tar.gz, an a .exe file to install. 
LxRunOffline can install those .tar.gz file.

</END>

**Comment by DDoSolitary** [comment]
I haven't checked that, but I believe they have. In fact, I have a plan to write instructions to install other distros. But now my No.1 priority is to rewrite the code to make use of an undocumented API. This will get rid of hooking and LxRun.exe(this tool seems to be deprecated by Microsoft).

**Comment by Biswa96** [comment]
No, LxRun.exe is not deprecated till now, it presents in Windows 10 version 1709. Did you want to use the exe files packed in appx packages?
I am thinking about to replace `http://` strings with `file://` in LxRun.exe.

**Comment by DDoSolitary** [comment]
Yes the executable is still there, but on Insider Preview releases, if you run it, it will tell you something about deprecation. I'm afraid Microsoft might remove it in a future release.

> Did you want to use the exe files packed in appx packages?

No, but I'm trying to create a program that behaves like the exe files in appx packages, and support other distros as long as a tar.gz can be created.

>  I am thinking about to replace http:// strings with file:// in LxRun.exe.

I think it is be possible, I ran `strings.exe`(from Sysinternals Suite) on LxRun.exe and found out the download links are simply hard coded there: `https://go.microsoft.com/fwlink/?LinkID=827586` and `https://go.microsoft.com/fwlink/?LinkId=747853`, so they can be easily replaced.

**Comment by Biswa96** [comment]
>  LxRun.exe(this tool seems to be deprecated by Microsoft) 

Yes, you are right. When I ran `lxrun.exe` in Win10 v1709, it shows a warning. I find that warning in `lxrun.exe.mui` resources.
 
> Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution. Distributions can be installed by visiting the Windows Store: https://aka.ms/wslstore"

The tarball path has changed in new appx packages. In old lxrun.exe, path is `%APPDATA%\Microsoft\Windows\Start Menu\Programs\lxss.tar.gz`. In new ubuntu.exe, path is `.\install.tar.gz`.

**Comment by Biswa96** [comment]
Ok, I've not to change the http:// to file://. The ubuntu.exe in that .appx file may have the built in call to install.tar.gz. So it can easily install any .tar.gz file. I'll post that in Microsoft/WSL.

**Comment by DDoSolitary** [comment]
I just found out that the API in wslapi.dll is documented now.

**Comment by DDoSolitary** [comment]
I got some problems.

- `WslRegisterDistribution` installs the distribution into the same directory as the program which is invoking it. (according to my test, changing working directory doesn't work) So if I want to specify a target directory in command line, the only workaround I came up with is copying the executable and invoking it with the same command line arguments.

- I can't understand the meaning of `defaultEnvironmentVariables`, which is a parameter of `WslGetDistributionConfiguration`. When invoking the function, I got some strange characters out of ASCII range, and the string even changes if the function is called multiple times.

- I can't find a way to list all installed distros. I think it should be stored somewhere in the registry. I'll try to figure it out tomorrow.

@Biswa96 Any thoughts? Thanks!

**Comment by Biswa96** [comment]
First of all the exported functions can be listed using [Strings from SysInternals](https://docs.microsoft.com/en-us/sysinternals/downloads/strings). 

```
> strings.exe wslapi.dll | find "Wsl"
WslConfigureDistribution
WslGetDistributionConfiguration
WslIsDistributionRegistered
WslLaunch
WslLaunchInteractive
WslRegisterDistribution
WslUnregisterDistribution
```

The distro list saved in registry `HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss` with some UID associated with installed distro.  I can't say about the `defaultEnvironmentVariables` parameter. But in my [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) log, I see::<br>
When `wsl.exe` create user in WSL with the following commands, it searches the environment variables of Windows.

``` 
/usr/bin/id UserName &> /dev/null
/usr/sbin/adduser --quiet --force-badname --disabled-password --gecos '' UserName
/usr/sbin/usermod -aG
/usr/bin/passwd UserName
```

**Comment by DDoSolitary** [comment]
@Biswa96 Just got updated to v2.0.0, would you like to give it a try?

New interface:

```
LxRunOffline install <name> <path to .tar.gz> <target installation directory>
LxRunOffline uninstall <name>
LxRunOffline info <name>
LxRunOffline run <name>
LxRunOffline config <name> <UID of the default user> <WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP> <WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH> <WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING> 
LxRunOffline run <name> [command to run(defaults to "/bin/bash --login")]
```

Last three arguments are flags for [WSL_DISTRIBUTION_FLAGS](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826872(v=vs.85).aspx), zero means off, non-zero means on.
```

**Comment by Biswa96** [comment]
Yes, yes! It works! 🤩 Wow, You've mimic the executable file in Appx package! I find many similarities between LxRunOffline.exe and Ubuntu.exe. 😲

 I followed this https://github.com/Microsoft/WSL/issues/8#issuecomment-240026910 and LxRunOffline.exe successfully installs Arch Linux along with Ubuntu. But I've some problems and suggestions, may I post them?

![arch_installed](https://user-images.githubusercontent.com/31443074/32630149-9d3512fa-c5c1-11e7-9e8a-87cb68027f7d.PNG)

**Comment by DDoSolitary** [comment]
Of course, any suggestions are welcomed 😄

**Comment by Biswa96** [comment]
- How did you find all the WSL API documetations?
- Can the API be called with `rundll32.exe wslapi.dll` command?
- Is there any way to combine the two `PInvoke.cs` and `Program.cs` files in one cs file?
- Can it be run in lower than .NET 4.7 framework by modifying `LxRunOffline.exe.config`?

**Comment by DDoSolitary** [comment]
> How did you find all the WSL API documetations?

I just googled some of the function names and the web page is in the results.

> Can the API be called with rundll32.exe wslapi.dll command?

I don't know, I'm not familiar with rundll32

> Is there any way to combine the two PInvoke.cs and Program.cs files in one cs file?

Of course, but I split them intentionally to keep code clean.

> Can it be run in lower than .NET 4.7 framework by modifying LxRunOffline.exe.config?

It should be possible, I didn't use any v4.7-specific API in my code, but I don't think it makes sense. The project now only works with FCU, which has v4.7 already installed.

> Why do you choose rootfs folder as default for all distro? Has it some relation with wsapi.dll?

It is used by wslapi.dll and I can not change it. In fact, the actual installation directory is the parent directory of "rootfs", and when running the distribution, wslapi.dll will even create more directories (e.g. temp) alongside "rootfs".

> It would be better if there is some Console.ReadLine(); and Console.ForegroundColor();

`Console.ForegroundColor` and `--help` is planned but not `Console.ReadLine()`, which is not that friendly for automated scenarios #8

**Comment by Biswa96** [comment]
Can you tell me how to combine those two file? I'm making a minimalistic program to just install any tar.gz.

**Comment by Biswa96** [comment]
I make this minimal gist from your project https://gist.github.com/Biswa96/6c1eccda9c8b289d792a6ad14a5b2265 and compile it with csc.exe.

**Comment by Biswa96** [comment]
>I just googled some of the function names and the web page is in the results.

I can not find the API directly in Google Search or in the [Windows API Index](https://msdn.microsoft.com/en-us/library/windows/desktop/ff818516(v=vs.85).aspx). May be that WSL functions are not well documented.
