### ISSUE TITLE
The program flash out instantly

### ISSUE THREAD

**Issue by meijieru** [DDoSolitary/LxRunOffline#70]
When I open the `LxRunOffline.exe`, it open a cmd window and exit right away.
How could I solve it?
The version is `v3.3.2`

**Comment by DDoSolitary** [comment]
LxRunOffline is a command line program so you have to use it through a shell. Open cmd in the directory containing the executable and run `LxRunOffline help` to find out how to use it.

**Comment by meijieru** [comment]
thx
