### ISSUE TITLE
LxRunOffline export doesn't work

### ISSUE THREAD

**Issue by js-ch** [DDoSolitary/LxRunOffline#74]
Tried to export a rootfs, but got an error: 
[ERROR] Error occurred while processing the archive: Failed to clean up compressor

**Comment by DDoSolitary** [comment]
Can't reproduce, please provide more context,  like:

- Which Linux distribution are you trying to capture
- Is the rootfs a clean install, if not, please try capturing a clean one and tell me what happens.
- What is the exact command you run with LxRunOffline.exe

Thanks.

**Comment by Biswa96** [comment]
BTW, new Windows 10 insider build 18305 has import and export command options in wsl.exe. Those can be added in LxRunOffline, like

```c
int export(something)
{
    CreateProcess("wsl.exe --export ...", ...);
}
```

**Comment by djibe** [comment]
Hi.
I have a WSL with Ubuntu 1804 on my O: partition : O:\wsl\installed\Ubuntu1804\

Here is my command : lxrunoffline export -n Ubuntu1804 -f O:\wsl\installed
Command sends me : Error occured while processing the archive: failed to clean up compressor

I can send you the partition if you want.
Thanks for your help

**Comment by djibe** [comment]
OK sorry.
I fixed it with : lxrunoffline export -n Ubuntu18 -f O:\wsl\backup.tar.gz

Nice work guys. Awesome tool.
