### ISSUE TITLE
You need to add `openscoop` bucket  to install `lxrunoffline` ?

### ISSUE THREAD

**Issue by cswl** [DDoSolitary/LxRunOffline#76]
```
scoop install lxrunoffline   
 Couldn't find manifest for 'lxrunoffline'.  

```

After adding `openscoop` bucket with ..

`scoop bucket add openscoop http://github.com/kiedtl/open-scoop.git`

```
scoop install lxrunoffline 
Installing 'lxrunoffline' (3.3.2) [64bit]
Download: (OK):download completed.
Checking hash of LxRunOffline-v3.3.2.zip ... ok.
Extracting LxRunOffline-v3.3.2.zip ... done.
Linking ~\scoop\apps\lxrunoffline\current => ~\scoop\apps\lxrunoffline\3.3.2
Creating shim for 'LxRunOffline'.
```

**Comment by DDoSolitary** [comment]
I'm not a scoop user. Information about scoop was merged in #63. @danielloader Any thoughts?

**Comment by danielloader** [comment]
I'll check when I get to work but it's possible a documentation upgrade is needed to represent that requirement.

**Comment by DDoSolitary** [comment]
I think it's better to use the more "official" one: https://github.com/lukesampson/scoop-extras
