### ISSUE TITLE
Can I delete the folder under %LOCALAPPDATA% after moving a distro?

### ISSUE THREAD

**Issue by Line40** [DDoSolitary/LxRunOffline#79]
Hi,

I just used your tool for the first time, to move a distribution to a different drive, it worked great, thanks for this awesome tool!
However I noticed that the files that the original installation created under %LOCALAPPDATA% (Ubuntu in my case) are still present. I would like to delete them, since my system drive is rather small. Is it safe to do so?
Whichever the answer should be, I think it would be good to mention it somewhere. I imagine I'm not the only one wanting to save the space after moving the distro.

Cheers

Line40

**Comment by DDoSolitary** [comment]
Please provide names of the subdirectories in the installation directory so that I can tell if they are important.

**Comment by Biswa96** [comment]
DO NOT delete the old WSL/Linux distro installation with 'Delete key' or any Windows tools. Use `wslconfig.exe /u <distro_name>` command and wait some time to finish it.

Cause: There are many files (like socket, symbolic link etc.) Windows don't know about it's metadata. So sometimes when I tried to delete that rootfs folder `rd /s` (Windows command) shows many error. At last, I have to use The A-Bomb, `rm -rf ./rootfs` 🌋

**Comment by DDoSolitary** [comment]
@Biswa96 I don't think it's a good idea to use `wslconfig /u` because this will delete the distro which has been moved to the desired location instead of the files left behind, which OP actually wants to delete and is most likely to be some subtle auxiliary files like temp, .ico, etc.

**Comment by DDoSolitary** [comment]
I just notice that I forgot to delete the source directory after moving in some cases.
