### ISSUE TITLE
[bug] wsl can not install or move to a winbtrfs partition.

### ISSUE THREAD

**Issue by snowyu** [DDoSolitary/LxRunOffline#80]
The btrfs partition is alwasy case-sensitive.

```
[ERROR] Couldn't set the case sensitive attribute of the directory "\\?\D:\wsl\ubuntu18.04\rootfs\".
Reason: {Not Implemented}
The requested operation is not implemented.
```

* [WinBtrfs](https://github.com/maharmstone/btrfs)

**Comment by DDoSolitary** [comment]
It's expected because WSL relies on NTFS extended attributes so only NTFS partitions are supposed.
