### ISSUE TITLE
Is it safe to use before update to 1903 ?

### ISSUE THREAD

**Issue by eromoe** [DDoSolitary/LxRunOffline#84]
I am afraid 1903 update would break something , do you have a test ?

**Comment by DDoSolitary** [comment]
AFAIK, there aren't any major changes that will affect the project in ver 1903. I have been using it myself on a system with Inside Preview enabled (fast ring) and I didn't encounter any problems. I can't guarantee that it won't break anything but generally I consider it safe to upgrade.

**Comment by eromoe** [comment]
Thank you for your clarification
