### ISSUE TITLE
Recover previous intallation in another partition due to Windows failure

### ISSUE THREAD

**Issue by ertwro** [DDoSolitary/LxRunOffline#85]
My windows bootloader got corrupted so badly I had to install Windows again in another partition. Is there a way to recover the rootfs I had in that other partition(now D:\)? It would be a huge pain in the ass installing everything I had there again. No, I don't have a backup different to the rootfs in that partition.

I have `WIndows 10 pro 1809`, my lxrunoffline is the last version in scoop. My rootfs is in `D:\ArchWSL\{rootfs\,temp\,ArchWSL.exe,rootfs.tar.gz}`. When I installed Arch for the first time I conserved the original roofts.tar.gz, do I need to delete it since is not a backup but a clean install? my current windows drive is` C:\`. I have more than 20 gigabytes in there and I would hate to lose it or get the permissions corrupted.
- Copy it?
- Just move the rootfs?

**Comment by DDoSolitary** [comment]
Please try the following command:

```
LxRunOffline rg -d D:\ArchWSL -n whatever_name_you_like
```

It will re-register the directory in the registry.

**Comment by DDoSolitary** [comment]
If I understand correctly, now you have Windows in C: and Arch in D:, and you want to install Windows in D: while preserving the Arch installation. An I right? Also, can you boot into the current Windows installation and run LxRunOffline, or it's completely corrupt and unusable?

**Comment by ertwro** [comment]
Windows only Allows me tow wipe the entire previous install but the files in it are ok. I registered the roofts in `D:` and they work perfectly but since I want to keep the installation in the same partition, this being I want to move `D:\ArchWSL\` to `C:\ArchWSL` I tried to duplicate the roofts but I get a ton of `[WARNING] Ignoring an unsupported file "\\?\E:\ArchWSL\rootfs\tmp\ssh-VugCGTmKbLPl\agent.42" of type 0140000.` for hundreds of files. I'm scared of using `move`, shall I try with `export`.?

**Comment by DDoSolitary** [comment]
No need to worry about the warnings. The ignored files are most likely to be temporary files which will be created automatically if not present.

**Comment by ertwro** [comment]
I went for it and I had a lot of permissions from home and some configuration changes not working despite having the right ownership, group and permissions. I solved it by copying all my home directory in the other partition from that users shell. I think maybe lxrunoffline uses `cp` as root? anyway, it works and I can't thank you enough for your time. Thanks.
