### ISSUE TITLE
Error during installation "The system cannot find the path"

### ISSUE THREAD

**Issue by Buba5473** [DDoSolitary/LxRunOffline#86]
Hi,

I download the Debian Stretch package at https://lxrunoffline.apphb.com/download/Debian/stretch.
Next, perform:
LxRunOffline.exe i -n Debian -d c: \ Debian -f C: \Users\buba\Downloads\DebianGNULinux_1-1-3-0_x64__76v4gfsz19hv4.Appx -s
and get an error

[ERROR] Couldn't create the file "\\?\C:\Debian\rootfs\Assets\LargeTile.scale-125.png".
Reason: The system cannot find the path specified.

An empty C:\Debian\rootfs folder appears on the disk
What am I doing wrong?

**Comment by Biswa96** [comment]
That website downloads a rootfs.tar.gz file. But in command you've type Appx file.

**Comment by DDoSolitary** [comment]
You can't install the appx file in this way. You should use `Add-AppxPackage` to install an appx file and LxRunOffline to install a tar file containing the root filesystem.
