### ISSUE TITLE
[ERROR] Couldn't create the directory "\\?\c:\CentOS7\rootfs\.".

### ISSUE THREAD

**Issue by doublespaces** [DDoSolitary/LxRunOffline#87]
Tried running CMD and PS as admin:

C:\LxRunOffline-v3.3.3>LxRunOffline i -n CentOS7 -d c:\CentOS7 -f c:\LxRunOffline-v3.3.3\CentOS-7-x86_64-Minimal-1810.iso -s
[ERROR] Couldn't create the directory "\\?\c:\CentOS7\rootfs\.".
Reason: The filename, directory name, or volume label syntax is incorrect.

C:\LxRunOffline-v3.3.3>

**Comment by DDoSolitary** [comment]
You can't install an iso file using this tool. You need to use a tar file which you can download from the [wiki](https://github.com/DDoSolitary/LxRunOffline/wiki)
