### ISSUE TITLE
Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by pluveto** [DDoSolitary/LxRunOffline#88]
By `LxRunOffline.exe run -n centos-7` I connected to my centos.
And I wanted to do so by ssh. But when calling `systemctl xxx`, I got `Failed to get D-Bus connection: Operation not permitted`.
I googled it, and it's said that this is because the design of docker. If user does want to use `systemctl `, he must provide param `--privileged=true` for the docker launch command. But by using LxRunOffline, I'm not able to access docker directly. What should I do?

**Comment by DDoSolitary** [comment]
LxRunOffline has nothing to do with docker, it's just a management interface for Windows 10's WSL functionality. Currently WSL doesn't support systemd: Microsoft/WSL#994
