### ISSUE TITLE
[Request Feature]add open bash in context menu & windows terminal (preview) option

### ISSUE THREAD

**Issue by adamkenway007** [DDoSolitary/LxRunOffline#91]
i'm curious it's possible to add "open bash here" in context menu & windows terminal (Preview) for each distribution for more flexibility

**Comment by FreakLevel** [comment]
About the context menu for "Open bash here" I think is posible but also you can open a cmd or powershell and connect to subsystem you want. Think -Here is about me- if you use a lot of subsystems, the context menu could be so large.
Of the other option, is possible but you should question to microsoft team directly, using the repo of windows terminal, the other option is create a other project but the reach of this project isn't that.

**Comment by DDoSolitary** [comment]
It is possible to have a sub-menu in the context menu so menu size won't be a major issue.
However, if I use registry to implement this, the menu can easily goes out of sync with the actual installation list so I have to write a [shortcut menu handler](https://docs.microsoft.com/en-us/windows/win32/shell/context-menu-handlers)， which I have no experience in.

**Comment by DDoSolitary** [comment]
I agree that it's a good idea to create a separate project for this feature, if I decide to implement it.

**Comment by DDoSolitary** [comment]
So I finally decided to implement this feature as a part of this project, because this way I can re-use the code for finding distros. I'm sorry that it took so long before I can find some time to implement it.
