### ISSUE TITLE
-w not recognized

### ISSUE THREAD

**Issue by zzj0402** [DDoSolitary/LxRunOffline#97]
```bash
lxrunoffline -w -n someName
[ERROR] The action "-w" is not recognized.
```
>https://stackoverflow.com/questions/51584765/how-do-you-install-multiple-separate-instances-of-ubuntu-in-wsl

**Comment by DDoSolitary** [comment]
The command is wrong. `lxrunoffline r -w -n someName` is what you may want.

**Comment by FreakLevel** [comment]
I don't know if the question of stackoverflow is part of this; but the option `-w` only change the initial directory for the root home path at moment you connect.
That option doesn't create a clone or copy of the instance isolated. In that case you need duplicate the instance of distribution.
Whatever, you can see only typing the incomplete command for some description about the command and their options.
![imagen](https://user-images.githubusercontent.com/29663603/63428014-7e463180-c3e4-11e9-83a1-bcbf3ef47fed.png)
